import json

VERBS = [
    ("A1", "Глаголы", "anfangen", "начинать", "", "Wann fängt der Kurs an?", "Когда начинается курс?"),
    ("A1", "Глаголы", "anrufen", "звонить", "", "Ich rufe dich morgen an.", "Я позвоню тебе завтра."),
    ("A1", "Глаголы", "antworten", "отвечать", "", "Bitte antworten Sie schnell.", "Пожалуйста, ответьте быстро."),
    ("A1", "Глаголы", "arbeiten", "работать", "", "Ich arbeite als Lehrer.", "Я работаю учителем."),
    ("A1", "Глаголы", "aufhören", "прекращать", "", "Hör bitte auf damit!", "Прекрати это, пожалуйста!"),
    ("A1", "Глаголы", "aufstehen", "вставать", "", "Ich stehe um sieben Uhr auf.", "Я встаю в семь часов."),
    ("A1", "Глаголы", "bekommen", "получать", "", "Ich bekomme ein Geschenk.", "Я получаю подарок."),
    ("A1", "Глаголы", "bestellen", "заказывать", "", "Wir bestellen Pizza.", "Мы заказываем пиццу."),
    ("A1", "Глаголы", "bleiben", "оставаться", "", "Ich bleibe zu Hause.", "Я остаюсь дома."),
    ("A1", "Глаголы", "brauchen", "нуждаться", "", "Ich brauche Hilfe.", "Мне нужна помощь."),
    ("A1", "Глаголы", "bringen", "приносить", "", "Bringen Sie mir ein Glas Wasser.", "Принесите мне стакан воды."),
    ("A1", "Глаголы", "danken", "благодарить", "", "Ich danke Ihnen.", "Я благодарю вас."),
    ("A1", "Глаголы", "denken", "думать", "", "Was denkst du?", "Что ты думаешь?"),
    ("A1", "Глаголы", "essen", "есть", "", "Ich esse gern Fisch.", "Я люблю есть рыбу."),
    ("A1", "Глаголы", "fahren", "ехать", "", "Fährst du mit dem Auto?", "Ты поедешь на машине?"),
    ("A1", "Глаголы", "finden", "находить", "", "Ich finde den Schlüssel nicht.", "Я не нахожу ключ."),
    ("A1", "Глаголы", "fragen", "спрашивать", "", "Darf ich etwas fragen?", "Можно кое-что спросить?"),
    ("A1", "Глаголы", "geben", "давать", "", "Gib mir bitte das Brot.", "Дай мне, пожалуйста, хлеб."),
    ("A1", "Глаголы", "gehen", "идти", "", "Wir gehen ins Kino.", "Мы идем в кино."),
    ("A1", "Глаголы", "helfen", "помогать", "", "Kannst du mir helfen?", "Ты можешь мне помочь?"),
    ("A1", "Глаголы", "hören", "слушать", "", "Ich höre gern Musik.", "Я люблю слушать музыку."),
    ("A1", "Глаголы", "kaufen", "покупать", "", "Ich kaufe ein Buch.", "Я покупаю книгу."),
    ("A1", "Глаголы", "kochen", "готовить", "", "Meine Mutter kocht gut.", "Моя мама хорошо готовит."),
    ("A1", "Глаголы", "kommen", "приходить", "", "Kommst du morgen?", "Ты придешь завтра?"),
    ("A1", "Глаголы", "lernen", "учить", "", "Ich lerne Deutsch.", "Я учу немецкий."),
    ("A1", "Глаголы", "lesen", "читать", "", "Liest du die Zeitung?", "Ты читаешь газету?"),
    ("A1", "Глаголы", "machen", "делать", "", "Что ты делаешь?", "Was machst du?"),
    ("A1", "Глаголы", "nehmen", "брать", "", "Ich nehme einen Tee.", "Я возьму чай."),
    ("A1", "Глаголы", "schreiben", "писать", "", "Schreib mir eine E-Mail.", "Напиши мне имейл."),
    ("A1", "Глаголы", "sehen", "видеть", "", "Ich sehe dich.", "Я тебя вижу."),
    ("A1", "Глаголы", "spielen", "играть", "", "Die Kinder spielen im Garten.", "Дети играют в саду."),
    ("A1", "Глаголы", "sprechen", "говорить", "", "Sprechen Sie Deutsch?", "Вы говорите по-немецки?"),
    ("A1", "Глаголы", "trinken", "пить", "", "Möchten Sie etwas trinken?", "Хотите что-нибудь попить?"),
    ("A1", "Глаголы", "verstehen", "понимать", "", "Я тебя понимаю.", "Ich verstehe dich."),
    ("A1", "Глаголы", "warten", "ждать", "", "Warten Sie eine Minute.", "Подождите минуту."),
    ("A1", "Глаголы", "wohnen", "жить", "", "Ich wohne in Berlin.", "Я живу в Берлине."),
    
    ("A2", "Глаголы", "anfangen", "начинать", "", "Wann hat der Film angefangen?", "Когда начался фильм?"),
    ("A2", "Глаголы", "anprobieren", "примерять", "", "Ich möchte diese Hose anprobieren.", "Я хочу примерить эти брюки."),
    ("A2", "Глаголы", "anziehen", "одевать", "", "Zieh dir eine Jacke an.", "Надень куртку."),
    ("A2", "Глаголы", "aussehen", "выглядеть", "", "Du siehst gut aus.", "Ты хорошо выглядишь."),
    ("A2", "Глаголы", "baden", "купаться", "", "Im Sommer baden wir im See.", "Летом мы купаемся в озере."),
    ("A2", "Глаголы", "bedeuten", "означать", "", "Was bedeutet das Wort?", "Что означает это слово?"),
    ("A2", "Глаголы", "beeilen", "торопиться", "", "Beeil dich, wir sind spät!", "Торопись, мы опаздываем!"),
    ("A2", "Глаголы", "beginnen", "начинать", "", "Das Konzert beginnt um acht.", "Концерт начинается в восемь."),
    ("A2", "Глаголы", "beschreiben", "описывать", "", "Kannst du den Weg beschreiben?", "Можешь описать дорогу?"),
    ("A2", "Глаголы", "besuchen", "посещать", "", "Wir besuchen unsere Freunde.", "Мы посетим наших друзей."),
    ("A2", "Глаголы", "bezahlen", "оплачивать", "", "Ich bezahle die Rechnung.", "Я оплачу счет."),
    ("A2", "Глаголы", "buchen", "бронировать", "", "Hast du das Hotel gebucht?", "Ты забронировал отель?"),
    ("A2", "Глаголы", "diskutieren", "обсуждать", "", "Wir diskutieren über Politik.", "Мы спорим о политике."),
    ("A2", "Глаголы", "drucken", "печатать", "", "Kannst du das Dokument drucken?", "Можешь напечатать документ?"),
    ("A2", "Глаголы", "duschen", "принимать душ", "", "Ich dusche morgens.", "Я принимаю душ по утрам."),
    ("A2", "Глаголы", "einkaufen", "закупаться", "", "Am Samstag kaufen wir ein.", "В субботу мы делаем покупки."),
    ("A2", "Глаголы", "einladen", "приглашать", "", "Ich lade dich zu meiner Party ein.", "Приглашаю тебя на вечеринку."),
    ("A2", "Глаголы", "erinnern", "вспоминать", "", "Erinnerst du dich an mich?", "Ты меня помнишь?"),
    ("A2", "Глаголы", "erklären", "объяснять", "", "Der Lehrer erklärt die Regel.", "Учитель объясняет правило."),
    ("A2", "Глаголы", "erlauben", "разрешать", "", "Meine Eltern erlauben es nicht.", "Мои родители этого не разрешают."),
    ("A2", "Глаголы", "erzählen", "рассказывать", "", "Opa erzählt eine Geschichte.", "Дедушка рассказывает историю."),
    ("A2", "Глаголы", "feiern", "праздновать", "", "Wir feiern heute Nacht.", "Сегодня мы празднуем всю ночь."),
    ("A2", "Глаголы", "fühlen", "чувствовать", "", "Wie fühlst du dich?", "Как ты себя чувствуешь?"),
    ("A2", "Глаголы", "gehören", "принадлежать", "", "Wem gehört das Auto?", "Кому принадлежит эта машина?"),
    ("A2", "Глаголы", "glauben", "верить/думать", "", "Ich glaube, es regnet bald.", "Я думаю, скоро пойдет дождь."),
    ("A2", "Глаголы", "gratulieren", "поздравлять", "", "Ich gratuliere dir zum Geburtstag.", "Поздравляю тебя с днем рождения."),
    ("A2", "Глаголы", "heiraten", "жениться/выходить замуж", "", "Sie heiraten im Juni.", "Они женятся в июне."),
    ("A2", "Глаголы", "hoffen", "надеяться", "", "Ich hoffe auf gutes Wetter.", "Надеюсь на хорошую погоду."),
    ("A2", "Глаголы", "holen", "приносить/забирать", "", "Ich hole dich vom Bahnhof ab.", "Я заберу тебя с вокзала."),
    ("A2", "Глаголы", "kennen", "знать/быть знакомым", "", "Kennst du diesen Mann?", "Знаешь этого человека?"),
    ("A2", "Глаголы", "lächeln", "улыбаться", "", "Sie lächelt immer.", "Она всегда улыбается."),
    ("A2", "Глаголы", "lachen", "смеяться", "", "Wir lachen viel.", "Мы много смеемся."),
    ("A2", "Глаголы", "legen", "класть", "", "Leg das Buch auf den Tisch.", "Положи книгу на стол."),
    ("A2", "Глаголы", "leihen", "одалживать", "", "Kannst du mir Geld leihen?", "Можешь одолжить мне денег?"),
    ("A2", "Глаголы", "lieben", "любить", "", "Ich liebe dich.", "Я тебя люблю."),
    ("A2", "Глаголы", "liegen", "лежать", "", "Das Buch liegt unter dem Bett.", "Книга лежит под кроватью."),
    ("A2", "Глаголы", "meinen", "иметь в виду/считать", "", "Was meinst du damit?", "Что ты имеешь в виду?"),
    ("A2", "Глаголы", "mieten", "арендовать", "", "Wir mieten eine Wohnung.", "Мы снимаем квартиру."),
    ("A2", "Глаголы", "mitnehmen", "брать с собой", "", "Nimm deinen Schirm mit.", "Возьми с собой зонт."),
    ("A2", "Глаголы", "öffnen", "открывать", "", "Öffne bitte das Fenster.", "Открой, пожалуйста, окно."),
    ("A2", "Глаголы", "passen", "подходить", "", "Die Hose passt mir nicht.", "Брюки мне не подходят."),
    ("A2", "Глаголы", "passieren", "происходить", "", "Was ist passiert?", "Что случилось?"),
    ("A2", "Глаголы", "probieren", "пробовать", "", "Probier mal die Suppe.", "Попробуй суп."),
    ("A2", "Глаголы", "putzen", "чистить", "", "Ich putze meine Zähne.", "Я чищу зубы."),
    ("A2", "Глаголы", "reisen", "путешествовать", "", "Wir reisen nach Spanien.", "Мы едем в Испанию."),
    ("A2", "Глаголы", "reparieren", "ремонтировать", "", "Mein Fahrrad ist kaputt, ich muss es reparieren.", "Мой велик сломан, мне нужно его починить."),
    ("A2", "Глаголы", "rufen", "звать/кричать", "", "Ich rufe dich später an.", "Я позвоню тебе позже."),
    ("A2", "Глаголы", "sammeln", "собирать", "", "Ich sammле монеты.", "Я собираю монеты."),
    ("A2", "Глаголы", "schenken", "дарить", "", "Was schenkst du ihr?", "Что ты ей подаришь?"),
    ("A2", "Глаголы", "schicken", "отправлять", "", "Ich schicke dir ein Paket.", "Я отправлю тебе посылку."),
    ("A2", "Глаголы", "schließen", "закрывать", "", "Schließ bitte die Tür.", "Закрой, пожалуйста, дверь."),
    ("A2", "Глаголы", "schmecken", "быть на вкус", "", "Das Essen schmeckt lecker.", "Еда очень вкусная."),
    ("A2", "Глаголы", "schneiden", "резать", "", "Schneid das Brot.", "Порежь хлеб."),
    ("A2", "Глаголы", "schwimmen", "плавать", "", "Ich schwimme jeden Morgen.", "Я плаваю каждое утро."),
    ("A2", "Глаголы", "spazieren", "гулять", "", "Wir gehen spazieren.", "Мы идем гулять."),
    ("A2", "Глаголы", "stehlen", "красть", "", "Jemand hat mein Handy gestohlen.", "Кто-то украл мой мобильник."),
    ("A2", "Глаголы", "steigen", "подниматься", "", "Wir steigen auf den Berg.", "Мы поднимаемся на гору."),
    ("A2", "Глаголы", "stellen", "ставить", "", "Stell die Vase auf den Tisch.", "Поставь вазу на стол."),
    ("A2", "Глаголы", "suchen", "искать", "", "Ich suche meine Brille.", "Я ищу свои очки."),
    ("A2", "Глаголы", "tanzen", "танцевать", "", "Möchtest du tanzen?", "Хочешь потанцевать?"),
    ("A2", "Глаголы", "treffen", "встречать", "", "Wir treffen uns um acht.", "Мы встретимся в восемь."),
    ("A2", "Глаголы", "vergessen", "забывать", "", "Ich habe meine Hausaufgaben vergessen.", "Я забыл домашку."),
    ("A2", "Глаголы", "verlieren", "терять", "", "Ich habe meinen Schlüssel verloren.", "Я потерял ключ."),
    ("A2", "Глаголы", "versuchen", "пытаться", "", "Ich versuche es еще раз.", "Я попробую еще раз."),
    ("A2", "Глаголы", "wählen", "выбирать", "", "Wähle eine Nummer.", "Выбери номер."),
    ("A2", "Глаголы", "waschen", "мыть/стирать", "", "Ich wasche mein Auto.", "Я мою свою машину."),
    ("A2", "Глаголы", "wünschen", "желать", "", "Ich wünsche dir viel Glück.", "Желаю тебе удачи."),
    ("A2", "Глаголы", "zeigen", "показывать", "", "Zeig mir deine Fotos.", "Покажи мне свои фотки."),

    ("B1", "Глаголы", "anerkennen", "признавать", "", "Sein Erfolg wurde anerkannt.", "Его успех был признан."),
    ("B1", "Глаголы", "beantragen", "подавать заявление", "", "Ich muss ein Visum beantragen.", "Мне нужно подать на визу."),
    ("B1", "Глаголы", "beeinflussen", "влиять", "", "Das Wetter beeinflusst meine Laune.", "Погода влияет на мое настроение."),
    ("B1", "Глаголы", "behaupten", "утверждать", "", "Er behauptet, dass er es nicht war.", "Он утверждает, что это был не он."),
    ("B1", "Глаголы", "berichten", "сообщать", "", "Die Zeitung berichtet über den Unfall.", "Газета сообщает о происшествии."),
    ("B1", "Глаголы", "beschädigen", "повреждать", "", "Das Auto wurde beschädigt.", "Машина была повреждена."),
    ("B1", "Глаголы", "beschweren", "жаловаться", "", "Ich möchte mich beschweren.", "Я хочу пожаловаться."),
    ("B1", "Глаголы", "bestätigen", "подтверждать", "", "Können Sie den Termin bestätigen?", "Можете подтвердить дату/время?"),
    ("B1", "Глаголы", "beteiligen", "участвовать/участвоваться", "", "Wir beteiligen uns an dem Projekt.", "Мы участвуем в проекте."),
    ("B1", "Глаголы", "betragen", "составлять (сумму)", "", "Die Kosten betragen 50 Euro.", "Расходы составляют 50 евро."),
    ("B1", "Глаголы", "bewerten", "оценивать", "", "Wie bewerten Sie das Hotel?", "Как вы оцениваете отель?"),
    ("B1", "Глаголы", "beziehen", "относиться/ссылаться", "", "Ich beziehe mich auf Ihr Schreiben.", "Я ссылаюсь на ваше письмо."),
    ("B1", "Глаголы", "darstellen", "представлять/изображать", "", "Das Bild stellt eine Stadt dar.", "Картина изображает город."),
    ("B1", "Глаголы", "empfehlen", "рекомендовать", "", "Was können Sie empfehlen?", "Что вы можете порекомендовать?"),
    ("B1", "Глаголы", "entscheiden", "решать", "", "Du musst dich jetzt entscheiden.", "Ты должен сейчас решить."),
    ("B1", "Глаголы", "entwickeln", "развивать/разрабатывать", "", "Wir entwickeln neue Ideen.", "Мы разрабатываем новые идеи."),
    ("B1", "Глаголы", "erfordern", "требовать", "", "Das erfordert viel Arbeit.", "Это требует много работы."),
    ("B1", "Глаголы", "erfüllen", "выполнять/исполнять", "", "Er hat seinen Traum erfüllt.", "Он исполнил свою мечту."),
    ("B1", "Глаголы", "erhalten", "получать/сохранять", "", "Ich habe Ihre E-Mail erhalten.", "Я получил ваш имейл."),
    ("B1", "Глаголы", "erhöhen", "повишать", "", "Die Preise wurden erhöht.", "Цены были повышены."),
    ("B1", "Глаголы", "erinnern", "напоминать", "", "Erinnern Sie mich bitte an den Termin.", "Напомните мне, пожалуйста, о встрече."),
    ("B1", "Глаголы", "erledigen", "выполнять/улаживать", "", "Ich muss noch etwas erledigen.", "Мне нужно еще кое-что сделать."),
    ("B1", "Глаголы", "ermöglichen", "делать возможным", "", "Das Internet ermöglicht schnelles Lernen.", "Интернет делает возможным быстрое обучение."),
    ("B1", "Глаголы", "ersetzen", "заменять", "", "Wir müssen das Teil ersetzen.", "Нам нужно заменить деталь."),
    ("B1", "Глаголы", "erwarten", "ожидать", "", "Ich erwarte einen Anruf.", "Я жду звонка."),
    ("B1", "Глаголы", "fordern", "требовать", "", "Sie fordern mehr Lohn.", "Они требуют больше зарплаты."),
    ("B1", "Глаголы", "fördern", "способствовать/поддерживать", "", "Sport fördert die Gesundheit.", "Спорт способствует здоровью."),
    ("B1", "Глаголы", "gelingen", "удаваться", "", "Es ist mir gelungen.", "Мне это удалось."),
    ("B1", "Глаголы", "genießen", "наслаждаться", "", "Ich genieße den Urlaub.", "Я наслаждаюсь отпуском."),
    ("B1", "Глаголы", "handeln", "торговать/действовать", "", "Wir müssen sofort handeln.", "Мы должны действовать немедленно."),
    ("B1", "Глаголы", "lösen", "решать (проблему)", "", "Wir haben das Problem gelöst.", "Мы решили проблему."),
    ("B1", "Глаголы", "meiden", "избегать", "", "Vermeiden Sie Stress.", "Избегайте стресса."),
    ("B1", "Глаголы", "pflegen", "ухаживать", "", "Sie pflegt ihre kranke Mutter.", "Она ухаживает за больной матерью."),
    ("B1", "Глаголы", "profitieren", "получать выгоду", "", "Wir profitieren von der Erfahrung.", "Мы извлекаем выгоду из опыта."),
    ("B1", "Глаголы", "schützen", "защищать", "", "Wir müssen die Umwelt schützen.", "Мы должны защищать среду."),
    ("B1", "Глаголы", "übernehmen", "брать на себя", "", "Ich übernehme die Verantwortung.", "Я беру на себя ответственность."),
    ("B1", "Глаголы", "überzeugen", "убеждать", "", "Er hat mich überzeugt.", "Он меня убедил."),
    ("B1", "Глаголы", "unterscheiden", "различать", "", "Wir unterscheiden zwei Typen.", "Мы различаем два типа."),
    ("B1", "Глаголы", "unterstützen", "поддерживать", "", "Ich unterstütze dich.", "Я тебя поддержу."),
    ("B1", "Глаголы", "vergleichen", "сравнивать", "", "Vergleichen Sie die Angebote.", "Сравните предложения."),
    ("B1", "Глаголы", "verhindern", "предотвращать", "", "Wir müssen den Unfall verhindern.", "Мы должны предотвратить аварию."),
    ("B1", "Глаголы", "vermeiden", "избегать", "", "Ich vermeide Fehler.", "Я избегаю ошибок."),
    ("B1", "Глаголы", "verpassen", "пропускать", "", "Ich habe den Bus verpasst.", "Я опоздал на автобус."),
    ("B1", "Глаголы", "versprechen", "обещать", "", "Versprich mir das.", "Пообещай мне это."),
    ("B1", "Глаголы", "verursachen", "вызывать/быть причиной", "", "Der Sturm hat Schäden verursacht.", "Шторм вызвал повреждения."),
    ("B1", "Глаголы", "verzichten", "отказываться", "", "Ich verzichte auf Zucker.", "Я отказываюсь от сахара."),
]

ADJECTIVES = [
    ("A1", "Прилагательные", "alt", "старый", "", "Mein Auto ist alt.", "Моя машина старая."),
    ("A1", "Прилагательные", "billig", "дешевый", "", "Das bread ist billig.", "Хлеб дешевый."),
    ("A1", "Прилагательные", "blau", "синий", "", "Der Himmel ist blau.", "Небо синее."),
    ("A1", "Прилагательные", "dick", "толстый", "", "Das Buch ist dick.", "Книга толстая."),
    ("A1", "Прилагательные", "dunkel", "темный", "", "Es ist schon dunkel.", "Уже темно."),
    ("A1", "Прилагательные", "einfach", "простой", "", "Deutsch ist nicht einfach.", "Немецкий не прост."),
    ("A1", "Прилагательные", "falsch", "неправильный", "", "Das ist falsch.", "Это неправильно."),
    ("A1", "Прилагательные", "fertig", "готовый", "", "Das Essen ist fertig.", "Еда готова."),
    ("A1", "Прилагательные", "frei", "свободный", "", "Ist dieser Platz frei?", "Это место свободно?"),
    ("A1", "Прилагательные", "gesund", "здоровый", "", "Obst ist gesund.", "Фрукты полезны."),
    ("A1", "Прилагательные", "groß", "большой", "", "Die Stadt ist groß.", "Город большой."),
    ("A1", "Прилагательные", "gut", "хороший", "", "Das ist eine gute Idee.", "Это хорошая идея."),
    ("A1", "Прилагательные", "hell", "светлый", "", "Mein Zimmer ist hell.", "Моя комната светлая."),
    ("A1", "Прилагательные", "heiß", "горячий", "", "Der Kaffee ist heiß.", "Кофе горячий."),
    ("A1", "Прилагательные", "jung", "молодой", "", "Der Mann ist jung.", "Мужчина молодой."),
    ("A1", "Прилагательные", "kalt", "холодный", "", "Das Wasser ist kalt.", "Вода холодная."),
    ("A1", "Прилагательные", "kaputt", "сломанный", "", "Mein Handy ist kaputt.", "Мой мобильник сломан."),
    ("A1", "Прилагательные", "klein", "маленький", "", "Das Zimmer ist klein.", "Комната маленькая."),
    ("A1", "Прилагательные", "lang", "длинный", "", "Die Reise ist lang.", "Путешествие долгое."),
    ("A1", "Прилагательные", "langsam", "медленный", "", "Fahren Sie bitte langsam.", "Пожалуйста, медленно."),
    ("A1", "Прилагательные", "laut", "громкий", "", "Die Musik ist zu laut.", "Музыка слишком громкая."),
    ("A1", "Прилагательные", "lecker", "вкусный", "", "Der Kuchen ist lecker.", "Пирог вкусный."),
    ("A1", "Прилагательные", "leise", "тихий", "", "Sei bitte leise.", "Тише, пожалуйста."),
    ("A1", "Прилагательные", "lustig", "веселый", "", "Der Film ist lustig.", "Фильм веселый."),
    ("A1", "Прилагательные", "müde", "усталый", "", "Ich bin müde.", "Я устал."),
    ("A1", "Прилагательные", "neu", "новый", "", "Ich habe ein neues Auto.", "У меня новая машина."),
    ("A1", "Прилагательные", "nett", "милый/приятный", "", "Sie ist sehr nett.", "Она очень милая."),
    ("A1", "Прилагательные", "richtig", "правильный", "", "Das ist richtig.", "Это верно."),
    ("A1", "Прилагательные", "rot", "красный", "", "Das ist ein roter Apfel.", "Это красное яблоко."),
    ("A1", "Прилагательные", "ruhig", "тихий/спокойный", "", "Es ist hier sehr ruhig.", "Здесь очень тихо."),
    ("A1", "Прилагательные", "sauber", "чистый", "", "Die Wohnung ist sauber.", "В квартире чисто."),
    ("A1", "Прилагательные", "schnell", "быстрый", "", "Das Auto ist schnell.", "Машина быстрая."),
    ("A1", "Прилагательные", "schön", "красивый", "", "Das Wetter ist schön.", "Погода прекрасная."),
    ("A1", "Прилагательные", "schwer", "тяжелый", "", "Der Koffer ist schwer.", "Чемодан тяжелый."),
    ("A1", "Прилагательные", "teuer", "дорогой", "", "Das Kleid ist zu teuer.", "Платье слишком дорогое."),
    ("A1", "Прилагательные", "warm", "теплый", "", "Mir ist warm.", "Мне тепло."),
    
    ("A2", "Прилагательные", "allein", "один", "", "Ich bin heute allein.", "Я сегодня один."),
    ("A2", "Прилагательные", "bekannt", "известный", "", "Er ist ein bekannter Autor.", "Он известный автор."),
    ("A2", "Прилагательные", "beliebt", "популярный", "", "Fußball ist sehr beliebt.", "Футбол очень популярен."),
    ("A2", "Прилагательные", "bequem", "удобный", "", "Der Sessel ist bequem.", "Кресло удобное."),
    ("A2", "Прилагательные", "breit", "широкий", "", "Die Straße ist breit.", "Улица широкая."),
    ("A2", "Прилагательные", "dumm", "глупый", "", "Das war eine dumme Idee.", "Это была глупая идея."),
    ("A2", "Прилагательные", "echt", "настоящий", "", "Ist das echtes Gold?", "Это настоящее золото?"),
    ("A2", "Прилагательные", "einsam", "одинокий", "", "Er fühlt sich einsam.", "Он чувствует себя одиноким."),
    ("A2", "Прилагательные", "eng", "тесный/узкий", "", "Die Hose ist zu eng.", "Брюки слишком тесные."),
    ("A2", "Прилагательные", "entfernt", "удаленный", "", "Berlin ist weit entfernt.", "Берлин далеко."),
    ("A2", "Прилагательные", "ernst", "серьезный", "", "Das ist ein ernstes Thema.", "Это серьезная тема."),
    ("A2", "Прилагательные", "faul", "ленивый", "", "Sei nicht so faul!", "Не будь таким лентяем!"),
    ("A2", "Прилагательные", "fleißig", "прилежный", "", "Sie ist eine fleißige Schülerin.", "Она прилежная ученица."),
    ("A2", "Прилагательные", "fremд", "чужой", "", "Ich bin fremd hier.", "Я здесь чужой."),
    ("A2", "Прилагательные", "freundlich", "дружелюбный", "", "Das Personal ist freundlich.", "Персонал дружелюбный."),
    ("A2", "Прилагательные", "froh", "рад", "", "Ich bin froh, dich zu sehen.", "Я рад тебя видеть."),
    ("A2", "Прилагательные", "gefährlich", "опасный", "", "Das ist gefährlich.", "Это опасно."),
    ("A2", "Прилагательные", "genau", "точный", "", "Sag mir die genaue Zeit.", "Скажи мне точное время."),
    ("A2", "Прилагательные", "glücklich", "счастливый", "", "Ich bin sehr glücklich.", "Я очень счастлив."),
    ("A2", "Прилагательные", "hart", "жесткий", "", "Das Brot ist hart.", "Хлеб черствый/жесткий."),
    ("A2", "Прилагательные", "höflich", "вежливый", "", "Sei bitte höflich.", "Будь вежлив, пожалуйста."),
    ("A2", "Прилагательные", "hübsch", "симпатичный", "", "Sie ist ein hübsches Mädchen.", "Она симпатичная девушка."),
    ("A2", "Прилагательные", "interessant", "интересный", "", "Der Film ist interessant.", "Фильм интересный."),
    ("A2", "Прилагательные", "klug", "умный", "", "Das ist ein kluger Plan.", "Это умный план."),
    ("A2", "Прилагательные", "krank", "больной", "", "Ich bin heute krank.", "Я сегодня болен."),
    ("A2", "Прилагательные", "langweilig", "скучный", "", "Die Vorlesung war langweilig.", "Лекция была скучной."),
    ("A2", "Прилагательные", "modern", "современный", "", "Das Haus ist modern.", "Дом современный."),
    ("A2", "Прилагательные", "möglich", "возможный", "", "Es ist möglich.", "Это возможно."),
    ("A2", "Прилагательные", "mutig", "смелый", "", "Das war sehr mutig.", "Это было очень смело."),
    ("A2", "Прилагательные", "nass", "мокрый", "", "Meine Kleidung ist nass.", "Моя одежда мокрая."),
    ("A2", "Прилагательные", "natürlich", "естественный", "", "Das ist ganz natürlich.", "Это совершенно естественно."),
    ("A2", "Прилагательные", "nervös", "нервный", "", "Sei nicht so nervös.", "Не нервничай так."),
    ("A2", "Прилагательные", "pünktlich", "пунктуальный", "", "Sei bitte pünktlich.", "Пожалуйста, будь вовремя."),
    ("A2", "Прилагательные", "reich", "богатый", "", "Er ist ein reicher Mann.", "Он богатый человек."),
    ("A2", "Прилагательные", "schmutzig", "грязный", "", "Das Auto ist schmutzig.", "Машина грязная."),
    ("A2", "Прилагательные", "selten", "редкий", "", "Das passiert nur selten.", "Это случается редко."),
    ("A2", "Прилагательные", "sicher", "уверенный/безопасный", "", "Bist du sicher?", "Ты уверен?"),
    ("A2", "Прилагательные", "spannend", "захватывающий", "", "Das Buch ist spannend.", "Книга захватывающая."),
    ("A2", "Прилагательные", "stark", "сильный", "", "Er ist ein starker Mann.", "Он сильный человек."),
    ("A2", "Прилагательные", "süß", "сладкий/милый", "", "Der Tee ist zu süß.", "Чай слишком сладкий."),
    ("A2", "Прилагательные", "traurig", "грустный", "", "Warum bist du traurig?", "Почему ты грустный?"),
    ("A2", "Прилагательные", "wahr", "истинный", "", "Das ist leider wahr.", "Это, к сожалению, правда."),
    ("A2", "Прилагательные", "wichtig", "важный", "", "Das ist eine wichtige Nachricht.", "Это важная новость."),
    ("A2", "Прилагательные", "zufrieden", "довольный", "", "Ich bin zufrieden.", "Я доволен."),

    ("B1", "Прилагательные", "allgemein", "общий", "", "Das ist ein allgemeines Problem.", "Это общая проблема."),
    ("B1", "Прилагательные", "anspruchsvoll", "требовательный", "", "Das ist eine anspruchsvolle Aufgabe.", "Это требовательная задача."),
    ("B1", "Прилагательные", "ausführlich", "подробный", "", "Können Sie das ausführlich erklären?", "Можете объяснить это подробно?"),
    ("B1", "Прилагательные", "bewusst", "сознательный", "", "Das war eine bewusste Entscheidung.", "Это было осознанное решение."),
    ("B1", "Прилагательные", "deutlich", "четкий", "", "Sprich bitte deutlich.", "Говори четко, пожалуйста."),
    ("B1", "Прилагательные", "ehrlich", "честный", "", "Sei ehrlich zu mir.", "Будь честен со мной."),
    ("B1", "Прилагательные", "eindeutig", "однозначный", "", "Das Ergebnis ist eindeutig.", "Результат однозначен."),
    ("B1", "Прилагательные", "empfindlich", "чувствительный", "", "Sie ist sehr empfindlich.", "Она очень чувствительна."),
    ("B1", "Прилагательные", "erfolgreich", "успешный", "", "Das Projekt war erfolgreich.", "Проект был успешным."),
    ("B1", "Прилагательные", "erforderlich", "необходимый", "", "Fachkenntnisse sind erforderlich.", "Требуются специальные знания."),
    ("B1", "Прилагательные", "erstaunlich", "удивительный", "", "Das ist ein erstaunliches Ergebnis.", "Это удивительный результат."),
    ("B1", "Прилагательные", "fest", "твердый/крепкий", "", "Wir haben einen festen Plan.", "У нас есть твердый план."),
    ("B1", "Прилагательные", "flüssig", "жидкий/беглый", "", "Er spricht flüssig Deutsch.", "Он бегло говорит по-немецки."),
    ("B1", "Прилагательные", "gelegentlich", "случайный/изредка", "", "Wir haben gelegentlich Kontakt.", "Мы изредка контактируем."),
    ("B1", "Прилагательные", "gemeinsam", "общий", "", "Wir haben ein gemeinsames Ziel.", "У нас общая цель."),
    ("B1", "Прилагательные", "gering", "незначительный", "", "Das Risiko ist gering.", "Риск невелик."),
    ("B1", "Прилагательные", "gewöhnlich", "обычный", "", "Das ist ein gewöhnlicher Tag.", "Это обычный день."),
    ("B1", "Прилагательные", "häufig", "частый", "", "Das ist ein частый ошибка.", "Это частая ошибка."),
    ("B1", "Прилагательные", "höflich", "вежливый", "", "Seien Sie bitte höflich.", "Будьте вежливы."),
    ("B1", "Прилагательные", "kompliziert", "сложный", "", "Das ist kompliziert.", "Это сложно."),
    ("B1", "Прилагательные", "kritisch", "критический", "", "Er ist ein kritischer Mensch.", "Он критичный человек."),
    ("B1", "Прилагательные", "künftig", "будущий", "", "Unsere künftigen Pläne.", "Наши будущие планы."),
    ("B1", "Прилагательные", "neugierig", "любопытный", "", "Kinder sind oft neugierig.", "Дети часто любопытны."),
    ("B1", "Прилагательные", "notwendig", "необходимый", "", "Es ist notwendig.", "Это необходимо."),
    ("B1", "Прилагательные", "nützlich", "полезный", "", "Das ist ein nützliches Werkzeug.", "Это полезный инструмент."),
    ("B1", "Прилагательные", "offensichtlich", "очевидный", "", "Das ist offensichtlich.", "Это очевидно."),
    ("B1", "Прилагательные", "öffentlich", "публичный", "", "Öffentliche Verkehrsmittel.", "Общественный транспорт."),
    ("B1", "Прилагательные", "praktisch", "практичный", "", "Das ist sehr практично.", "Это очень практично."),
    ("B1", "Прилагательные", "selbstverständlich", "само собой разумеющийся", "", "Das ist selbstverständlich.", "Это само собой разумеется."),
    ("B1", "Прилагательные", "sinnvoll", "осмысленный", "", "Das ist eine sinnvolle Aufgabe.", "Это осмысленная задача."),
    ("B1", "Прилагательные", "ständig", "постоянный", "", "Er redet ständig.", "Он постоянно болтает."),
    ("B1", "Прилагательные", "umfangreich", "обширный", "", "Das ist ein обширный тема.", "Это обширная тема."),
    ("B1", "Прилагательные", "unangenehm", "неприятный", "", "Das war eine unangenehme Situation.", "Это была неприятная ситуация."),
    ("B1", "Прилагательные", "unabhängig", "независимый", "", "Wir sind независимо.", "Мы независимы."),
    ("B1", "Прилагательные", "unvermeidbar", "неизбежный", "", "Das war unvermeidbar.", "Это было неизбежно."),
    ("B1", "Прилагательные", "verantwortlich", "ответственный", "", "Wer ist ответственный?", "Кто ответственный?"),
    ("B1", "Прилагательные", "vergleichbar", "сравнимый", "", "Das ist nicht сравнимо.", "Это несравнимо."),
    ("B1", "Прилагательные", "vollständig", "полный/завершенный", "", "Die Liste ist полная.", "Список полон."),
    ("B1", "Прилагательные", "wesentlich", "существенный", "", "Das ist ein существенный пункт.", "Это существенный пункт."),
    ("B1", "Прилагательные", "wirksam", "эффективный", "", "Das Medikament ist эффективно.", "Лекарство эффективно."),
    ("B1", "Прилагательные", "zufällig", "случайный", "", "Das war ein случайное встреча.", "Это была случайная встреча."),
    ("B1", "Прилагательные", "zuverlässig", "надежный", "", "Mein Auto ist надежно.", "Моя машина надежна."),
]

all_words = []

for item in VERBS:
    level, topic, de, ru, article, ex_de, ex_ru = item
    all_words.append({
        "level": level,
        "topic": topic,
        "de": de,
        "ru": ru,
        "article": article,
        "example_de": ex_de,
        "example_ru": ex_ru
    })

for item in ADJECTIVES:
    level, topic, de, ru, article, ex_de, ex_ru = item
    all_words.append({
        "level": level,
        "topic": topic,
        "de": de,
        "ru": ru,
        "article": article,
        "example_de": ex_de,
        "example_ru": ex_ru
    })

content = "# Balanced Verbs and Adjectives Expansion\n\n"
content += "GOETHE_VERBS_ADJ = " + json.dumps(all_words, ensure_ascii=False, indent=4) + "\n"

with open("api/goethe_verbs_adj.py", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated {len(all_words)} words in api/goethe_verbs_adj.py")
