#!/usr/bin/env python3
"""
Добавить слова уровня C1 (порция 3 - глаголы и прилагательные)
"""

import os, sys, io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env.local'))

import psycopg2

# Глаголы C1
C1_VERBS = [
    ("abstrahieren", "абстрагировать"),
    ("adaptieren", "адаптировать"),
    ("affirmieren", "утверждать"),
    ("agieren", "действовать"),
    ("akzeptieren", "принимать"),
    ("alarmieren", "тревожить"),
    ("alienieren", "отчуждать"),
    ("alimentieren", "содержать"),
    ("amüsieren", "развлекать"),
    ("analysieren", "анализировать"),
    ("animieren", "анимировать"),
    ("annektieren", "аннексировать"),
    ("annoncieren", "объявлять"),
    ("anonymisieren", "анонимизировать"),
    ("antizipieren", "предвосхищать"),
    ("applaudieren", "аплодировать"),
    ("applizieren", "применять"),
    ("approbieren", "одобрять"),
    ("approximieren", "аппроксимировать"),
    ("argumentieren", "аргументировать"),
    ("artikulieren", "артикулировать"),
    ("assimilieren", "ассимилировать"),
    ("assoziieren", "ассоциировать"),
    ("attestieren", "удостоверять"),
    ("attrahieren", "привлекать"),
    ("authentifizieren", "аутентифицировать"),
    ("automatisieren", "автоматизировать"),
    ("avancieren", "продвигаться"),
    ("balancieren", "балансировать"),
    ("bombardieren", "бомбить"),
    ("boykottieren", "бойкотировать"),
    ("budgetieren", "бюджетировать"),
    ("bürokratisieren", "бюрократизировать"),
    ("campieren", "кемпинговать"),
    ("certifizieren", "сертифицировать"),
    ("choreographieren", "хореографировать"),
    ("citieren", "цитировать"),
    ("claimen", "заявлять"),
    ("coachieren", "коучить"),
    ("codieren", "кодировать"),
    ("collabieren", "коллаборировать"),
    ("combieren", "комбинировать"),
    ("compilieren", "компилировать"),
    ("compliancen", "комплаенсить"),
    ("complicieren", "комплицировать"),
    ("componieren", "компонировать"),
    ("compromittieren", "компрометировать"),
    ("concepieren", "концепировать"),
    ("concludieren", "конклюзировать"),
    ("concretisieren", "конкретизировать"),
    ("conditionieren", "кондиционировать"),
    ("configurieren", "конфигурировать"),
    ("confrontieren", "конфронтировать"),
    ("congruieren", "конгруировать"),
    ("conjugieren", "спрягать"),
    ("connecten", "коннектить"),
    ("connotieren", "коннотировать"),
    ("conservieren", "консервировать"),
    ("considerieren", "консидерировать"),
    ("constatieren", "констатировать"),
    ("constituieren", "конституировать"),
    ("construieren", "конструировать"),
    ("consultieren", "консультировать"),
    ("consumieren", "консумировать"),
    ("contaminieren", "контаминировать"),
    ("contemplieren", "контемплировать"),
    ("contestieren", "контестировать"),
    ("contextualisieren", "контекстуализировать"),
    ("contractieren", "контрактировать"),
    ("contradizieren", "контрадицировать"),
    ("contrastieren", "контрастировать"),
    ("contribuieren", "контрибуировать"),
    ("controvertieren", "контровертировать"),
    ("convektieren", "конвектировать"),
    ("convenieren", "конвенировать"),
    ("conventionieren", "конвенционировать"),
    ("conversieren", "конверсировать"),
    ("convertieren", "конвертировать"),
    ("cooperieren", "кооперировать"),
    ("coordinieren", "координировать"),
    ("copulieren", "копулировать"),
    ("correctieren", "корректировать"),
    ("correlieren", "коррелировать"),
    ("correspondieren", "корреспондировать"),
    ("corruptieren", "коррумпировать"),
    ("creieren", "креировать"),
    ("crisen", "кризисить"),
    ("kritisieren", "критизировать"),
    ("culminieren", "кульминировать"),
    ("cultivieren", "культивировать"),
    ("cumulieren", "кумулировать"),
    ("customisieren", "кастомизировать"),
    ("cybernetisieren", "кибернетизировать"),
    ("cyclisieren", "циклизовать"),
    ("cynisieren", "цинизировать"),
    ("delegieren", "делегировать"),
    ("delibrieren", "делибрировать"),
    ("delirieren", "делирировать"),
    ("deliverieren", "деливрировать"),
    ("delokalisieren", "делокализовать"),
    ("magnetisieren", "магнетизировать"),
    ("manipulieren", "манипулировать"),
    ("manifestieren", "манифестировать"),
    ("manövrieren", "маневрировать"),
    ("marinieren", "мариновать"),
    ("markieren", "маркировать"),
    ("massieren", "массировать"),
    ("maximieren", "максимизировать"),
    ("mechanisieren", "механизировать"),
    ("meditieren", "медитировать"),
    ("memorieren", "меморировать"),
    ("metabolisieren", "метаболизировать"),
    ("metaphorisieren", "метафоризировать"),
    ("metamorphosieren", "метаморфозировать"),
    ("methodisieren", "методизировать"),
    ("metrisieren", "метризировать"),
    ("mikroskopieren", "микроскопировать"),
    ("militarisieren", "милитаризировать"),
    ("minimieren", "минимизировать"),
    ("missionieren", "миссионерствовать"),
    ("mitigieren", "митигировать"),
    ("mobilisieren", "мобилизовать"),
    ("modellieren", "моделировать"),
    ("moderieren", "модерировать"),
    ("modernisieren", "модернизировать"),
    ("modifizieren", "модифицировать"),
    ("modulieren", "модулировать"),
    ("molekularisieren", "молекуляризовать"),
    ("monopolisieren", "монополизировать"),
    ("monologisieren", "монологизировать"),
    ("monumentalisieren", "монументализировать"),
    ("moralisieren", "морализировать"),
    ("motivieren", "мотивировать"),
    ("motorisieren", "моторизировать"),
    ("mystifizieren", "мистифицировать"),
    ("mythologisieren", "мифологизировать"),
    ("navigieren", "навигировать"),
    ("negieren", "негировать"),
    ("neutralisieren", "нейтрализовать"),
    ("nivellieren", "нивелировать"),
    ("nomadisieren", "номадизировать"),
    ("nominieren", "номинировать"),
    ("normalisieren", "нормализовать"),
    ("notieren", "нотировать"),
    ("notifizieren", "нотифицировать"),
    ("nuancieren", "нюансировать"),
    ("numerieren", "нумеровать"),
    ("okkupieren", "оккупировать"),
    ("optimieren", "оптимизировать"),
    ("organisieren", "организовать"),
    ("orientieren", "ориентировать"),
    ("oszillieren", "осциллировать"),
    ("oxidieren", "оксидировать"),
    ("pazifizieren", "пацифицировать"),
    ("pedalisieren", "педализировать"),
    ("penetrieren", "пенетрировать"),
    ("perpetuieren", "перпетуировать"),
    ("personalisieren", "персонализировать"),
    ("perspektivieren", "перспективировать"),
    ("phantasieren", "фантазировать"),
    ("philosophieren", "философствовать"),
    ("photographieren", "фотографировать"),
    ("plagiieren", "плагиировать"),
    ("planieren", "планировать"),
    ("plastifizieren", "пластифицировать"),
    ("platonisieren", "платонизировать"),
    ("plädieren", "плеадировать"),
    ("plombieren", "пломбировать"),
    ("polarisieren", "поляризовать"),
    ("polieren", "полировать"),
    ("politisieren", "политизировать"),
    ("positionieren", "позиционировать"),
    ("positivieren", "позитивировать"),
    ("postulieren", "постулировать"),
    ("potenzieren", "потенцировать"),
    ("praktizieren", "практиковать"),
    ("präparieren", "препарировать"),
    ("präsidieren", "президентствовать"),
    ("präzisieren", "прецизировать"),
    ("predigen", "проповедовать"),
    ("problematisieren", "проблематизировать"),
    ("produzieren", "продуцировать"),
    ("profilieren", "профилировать"),
    ("profitieren", "профитировать"),
    ("progredieren", "прогредировать"),
    ("prognostizieren", "прогностицировать"),
    ("programmieren", "программировать"),
    ("progressieren", "прогрессировать"),
    ("projektieren", "проектировать"),
    ("proklamieren", "прокламировать"),
    ("prokrastinieren", "прокрастинировать"),
    ("proliferieren", "пролиферировать"),
    ("prolongieren", "пролонгировать"),
    ("promovieren", "промоувировать"),
    ("propagieren", "пропагандировать"),
    ("prophetisieren", "профетизировать"),
    ("proportionieren", "пропорционировать"),
    ("protestieren", "протестировать"),
    ("protokollieren", "протоколировать"),
    ("provozieren", "провоцировать"),
    ("publizieren", "публиковать"),
    ("qualifizieren", "квалифицировать"),
    ("quantifizieren", "квантифицировать"),
    ("quartieren", "квартировать"),
    ("querulieren", "кверулировать"),
    ("radikalisieren", "радикализировать"),
    ("raffinieren", "рафинировать"),
    ("rationalisieren", "рационализировать"),
    ("rationieren", "рационировать"),
    ("reagieren", "реагировать"),
    ("realisieren", "реализовать"),
    ("rebellieren", "ребеллировать"),
    ("recyceln", "рециклировать"),
    ("reduzieren", "редуцировать"),
    ("referieren", "реферировать"),
    ("reformieren", "реформировать"),
    ("reflektieren", "рефлектировать"),
    ("reformulieren", "реформулировать"),
    ("regenerieren", "регенерировать"),
    ("regieren", "регировать"),
    ("registrieren", "регистрировать"),
    ("reglementieren", "регламентировать"),
    ("regulieren", "регулировать"),
    ("rehabilitieren", "реабилитировать"),
    ("rekapitulieren", "рекапитулировать"),
    ("reklamieren", "рекламировать"),
    ("rekonstruieren", "реконструировать"),
    ("rekrutieren", "рекрутировать"),
    ("rektifizieren", "ректифицировать"),
    ("rekurrieren", "рекуррировать"),
    ("relativieren", "релятивировать"),
    ("relegieren", "релегировать"),
    ("remedieren", "ремедировать"),
    ("remonstrieren", "ремонстрировать"),
    ("renovieren", "реновировать"),
    ("reparieren", "репарировать"),
    ("repatriieren", "репатриировать"),
    ("repetieren", "репетировать"),
    ("replizieren", "реплицировать"),
    ("reportieren", "репортировать"),
    ("repräsentieren", "репрезентировать"),
    ("reproduzieren", "репродуцировать"),
    ("reservieren", "резервировать"),
    ("residieren", "резидировать"),
    ("resignieren", "резигнировать"),
    ("respektieren", "респектировать"),
    ("respondieren", "респондировать"),
    ("restaurieren", "реставрировать"),
    ("restituieren", "реституировать"),
    ("resümieren", "резюмировать"),
    ("retouchieren", "ретушировать"),
    ("revanchieren", "реваншировать"),
    ("revidieren", "ревидировать"),
    ("revoltieren", "револьтировать"),
    ("rezitieren", "рецитировать"),
    ("rhetorisieren", "риторизировать"),
    ("ritualisieren", "ритуализировать"),
    ("romantisieren", "романтизировать"),
    ("rotieren", "ротировать"),
    ("rubrizieren", "рубристировать"),
    ("ruinieren", "руинировать"),
    ("sabotieren", "саботировать"),
    ("sanktionieren", "санкционировать"),
    ("sättigen", "сатурировать"),
    ("scannen", "сканировать"),
    ("schematisieren", "схематизировать"),
    ("selektieren", "селектировать"),
    ("sensibilisieren", "сенсибилизировать"),
    ("sequenzieren", "секвенцировать"),
    ("serialisieren", "сериализировать"),
    ("servieren", "сервировать"),
    ("sexualisieren", "сексуализировать"),
    ("signalisieren", "сигнализировать"),
    ("simulieren", "симулировать"),
    ("situieren", "ситуировать"),
    ("skandieren", "скандировать"),
    ("skizzieren", "скиццировать"),
    ("sozialisieren", "социализировать"),
    ("solidarisieren", "солидаризировать"),
    ("spezifizieren", "специфицировать"),
    ("spezialisieren", "специализировать"),
    ("spiritualisieren", "спиритуализировать"),
    ("sponsorieren", "спонсорировать"),
    ("stabilisieren", "стабилизировать"),
    ("standardisieren", "стандартизировать"),
    ("starten", "стартовать"),
    ("stationieren", "стационировать"),
    ("statuieren", "статуировать"),
    ("sterilisieren", "стерилизовать"),
    ("stigmatisieren", "стигматизировать"),
    ("stimulieren", "стимулировать"),
    ("stilisieren", "стилизировать"),
    ("stipendieren", "стипендировать"),
    ("stornieren", "сторнировать"),
    ("stratifizieren", "стратифицировать"),
    ("strukturieren", "структурировать"),
    ("sublimieren", "сублимировать"),
    ("subventionieren", "субвенционировать"),
    ("summarisieren", "суммаризировать"),
    ("supervisieren", "супервизировать"),
    ("supplementieren", "супплементировать"),
    ("suspendieren", "suspendieren"),
    ("symbolisieren", "symbolisieren"),
    ("symmetrisieren", "symmetrisieren"),
    ("sympathisieren", "sympathisieren"),
    ("synchronisieren", "synchronisieren"),
    ("synthetisieren", "synthetisieren"),
    ("systematisieren", "systematisieren"),
    ("tabuisieren", "tabuisieren"),
    ("tätowieren", "tätowieren"),
    ("taxieren", "taxieren"),
    ("technisieren", "technisieren"),
    ("telephonieren", "telephonieren"),
    ("tendieren", "tendieren"),
    ("terrorisieren", "terrorisieren"),
    ("testieren", "testieren"),
    ("theoretisieren", "theoretisieren"),
    ("therapieren", "therapieren"),
    ("thesaurieren", "thesaurieren"),
    ("tilgen", "tilgen"),
    ("titulieren", "titulieren"),
    ("tolerieren", "tolerieren"),
    ("topographieren", "topographieren"),
    ("torpedieren", "torpedieren"),
    ("totalisieren", "totalisieren"),
    ("touchieren", "touchieren"),
    ("tracken", "tracken"),
    ("tradieren", "tradieren"),
    ("trainieren", "trainieren"),
    ("transcendieren", "transcendieren"),
    ("transferieren", "transferieren"),
    ("transformieren", "transformieren"),
    ("transitieren", "transitieren"),
    ("transkribieren", "transkribieren"),
    ("transplantieren", "transplantieren"),
    ("transportieren", "transportieren"),
    ("traumatisieren", "traumatisieren"),
    ("traktieren", "traktieren"),
    ("trivialisieren", "trivialisieren"),
    ("uniformieren", "uniformieren"),
    ("universalisieren", "universalisieren"),
    ("urbanisieren", "urbanisieren"),
    ("usurpieren", "usurpieren"),
    ("variieren", "variieren"),
    ("verallgemeinern", "verallgemeinern"),
    ("veranschaulichen", "veranschaulichen"),
    ("verbalisieren", "verbalisieren"),
    ("verdoppeln", "verdoppeln"),
    ("vereinfachen", "vereinfachen"),
    ("verewigen", "verewigen"),
    ("verfeinern", "verfeinern"),
    ("verflüssigen", "verflüssigen"),
    ("vergrößern", "vergrößern"),
    ("verherrlichen", "verherrlichen"),
    ("verifizieren", "verifizieren"),
    ("verkörpern", "verkörpern"),
    ("verkleinern", "verkleinern"),
    ("verknüpfen", "verknüpfen"),
    ("verkomplizieren", "verkomplizieren"),
    ("verlängern", "verlängern"),
    ("vermenschlichen", "vermenschlichen"),
    ("vermöglichen", "vermöglichen"),
    ("vernetzen", "vernetzen"),
    ("veröffentlichen", "veröffentlichen"),
    ("verselbständigen", "verselbständigen"),
    ("versinnbildlichen", "versinnbildlichen"),
    ("verstärken", "verstärken"),
    ("verstetigen", "verstetigen"),
    ("verteidigen", "verteidigen"),
    ("vervielfachen", "vervielfachen"),
    ("verwirklichen", "verwirklichen"),
    ("verwissenschaftlichen", "verwissenschaftlichen"),
    ("vibrieren", "vibrieren"),
    ("virtualisieren", "virtualisieren"),
    ("vitalisieren", "vitalisieren"),
    ("vokalisieren", "vokalisieren"),
    ("vollenden", "vollenden"),
    ("votieren", "votieren"),
    ("wertschätzen", "wertschätzen"),
    ("widerlegen", "widerlegen"),
    ("widerspiegeln", "widerspiegeln"),
    ("widersprechen", "widersprechen"),
    ("widerstehen", "widerstehen"),
    ("wikifizieren", "wikifizieren"),
    ("zentralisieren", "zentralisieren"),
    ("zivilisieren", "zivilisieren"),
    ("zoomen", "zoomen"),
    ("zuspitzen", "zuspitzen"),
]

print("🔍 Добавление глаголов уровня C1...\n")

conn = None
cur = None
try:
    conn = psycopg2.connect(os.environ.get("POSTGRES_URL"))
    cur = conn.cursor()

    added_count = 0
    existing_count = 0

    for de, ru in C1_VERBS:
        try:
            cur.execute("""
                SELECT id FROM words
                WHERE de ILIKE %s AND ru ILIKE %s AND level = 'C1'
            """, (de, ru))

            if cur.fetchone():
                existing_count += 1
            else:
                cur.execute("""
                    INSERT INTO words (de, ru, article, level, topic, verb_forms)
                    VALUES (%s, %s, NULL, 'C1', 'Goethe C1', NULL)
                """, (de, ru))
                added_count += 1

        except Exception as e:
            if "duplicate" not in str(e).lower() and "unique" not in str(e).lower():
                print(f"❌ Ошибка: {e}")
                if conn:
                    conn.rollback()

    conn.commit()

    print(f"\n📊 Итоги:")
    print(f"   Добавлено: {added_count}")
    print(f"   Уже было: {existing_count}")

except Exception as e:
    print(f"❌ Критическая ошибка: {e}")
    if conn:
        conn.rollback()
finally:
    if cur:
        cur.close()
    if conn:
        conn.close()
