#!/usr/bin/env python3
"""
Добавить слова уровня C1 из Goethe Institut
"""

import os, sys, io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env.local'))

import psycopg2

conn = None
cur = None
try:
    conn = psycopg2.connect(os.environ.get("POSTGRES_URL"))
    cur = conn.cursor()

    # Слова уровня C1 (продвинутый уровень)
    GOETHE_C1_WORDS = [
    # Существительные
    ("die Abstraktion", "абстракция"),
    ("die Akzeptanz", "принятие"),
    ("die Ambition", "амбиция"),
    ("die Ambivalenz", "амбивалентность"),
    ("die Analogie", "аналогия"),
    ("die Animation", "анимация"),
    ("die Anomalie", "аномалия"),
    ("die Antithese", "антитезис"),
    ("die Apologie", "апология"),
    ("die Apotheose", "апофеоз"),
    ("die Appellation", "апелляция"),
    ("die Applikation", "аппликация"),
    ("die Approximation", "аппроксимация"),
    ("die Äquivalenz", "эквивалентность"),
    ("die Argumentation", "аргументация"),
    ("die Artikulation", "артикуляция"),
    ("die Assoziation", "ассоциация"),
    ("die Assimilation", "ассимиляция"),
    ("die Asymmetrie", "асимметрия"),
    ("die Atmosphäre", "атмосфера"),
    ("die Attribution", "атрибуция"),
    ("die Authentizität", "аутентичность"),
    ("die Autonomie", "автономия"),
    ("die Avantgarde", "авангард"),
    ("die Aversion", "отвращение"),
    ("die Balance", "баланс"),
    ("die Barriere", "барьер"),
    ("die Betonung", "ударение"),
    ("die Bibliothek", "библиотека"),
    ("die Biografie", "биография"),
    ("die Biologie", "биология"),
    ("die Blamage", "позор"),
    ("die Bosheit", "злоба"),
    ("die Bravour", "бравада"),
    ("die Brisanz", "острота"),
    ("die Bürokratie", "бюрократия"),
    ("die Chance", "шанс"),
    ("die Charakteristik", "характеристика"),
    ("die Charisma", "харизма"),
    ("die Chemie", "химия"),
    ("die Chronik", "хроника"),
    ("die Chiffre", "шифр"),
    ("die Zivilisation", "цивилизация"),
    ("die Coalition", "коалиция"),
    ("die Codierung", "кодирование"),
    ("die Cognition", "познание"),
    ("die Cohärenz", "когерентность"),
    ("die Collage", "коллаж"),
    ("die Colloquium", "коллоквиум"),
    ("die Coloratur", "колоратура"),
    ("die Combination", "комбинация"),
    ("die Comedy", "комедия"),
    ("die Commandierung", "командирование"),
    ("die Communion", "общение"),
    ("die Community", "сообщество"),
    ("die Compilation", "компиляция"),
    ("die Complacency", "самодовольство"),
    ("die Compliance", "соответствие"),
    ("die Complication", "осложнение"),
    ("die Composition", "композиция"),
    ("die Compromission", "компромисс"),
    ("die Conception", "концепция"),
    ("die Concern", "обеспокоенность"),
    ("die Concision", "краткость"),
    ("die Conclusion", "заключение"),
    ("die Concretion", "конкретизация"),
    ("die Condition", "условие"),
    ("die Conferenz", "конференция"),
    ("die Configuration", "конфигурация"),
    ("die Confrontation", "конфронтация"),
    ("die Confusion", "путаница"),
    ("die Congruenz", "конгруэнтность"),
    ("die Conjugation", "спряжение"),
    ("die Conjunction", "конъюнкция"),
    ("die Connexion", "связь"),
    ("die Connotation", "коннотация"),
    ("die Consequenz", "последствие"),
    ("die Conservation", "сохранение"),
    ("die Consideration", "рассмотрение"),
    ("die Consistenz", "консистентность"),
    ("die Consonanz", "консонанс"),
    ("die Constanz", "константность"),
    ("die Constitution", "конституция"),
    ("die Construction", "конструкция"),
    ("die Consultation", "консультация"),
    ("die Consumption", "потребление"),
    ("die Contamination", "загрязнение"),
    ("die Contemplation", "созерцание"),
    ("die Contentierung", "удовлетворение"),
    ("die Contestation", "оспаривание"),
    ("die Context", "контекст"),
    ("die Continuität", "непрерывность"),
    ("die Contraction", "сокращение"),
    ("die Contradiction", "противоречие"),
    ("die Contrast", "контраст"),
    ("die Contribution", "вклад"),
    ("die Contrition", "раскаяние"),
    ("die Controverse", "спор"),
    ("die Convection", "конвекция"),
    ("die Convenience", "удобство"),
    ("die Convention", "конвенция"),
    ("die Conversation", "разговор"),
    ("die Conversion", "преобразование"),
    ("die Conviction", "убеждение"),
    ("die Cooperation", "кооперация"),
    ("die Coordination", "координация"),
    ("die Copulation", "копуляция"),
    ("die Correction", "коррекция"),
    ("die Correlation", "корреляция"),
    ("die Correspondenz", "корреспонденция"),
    ("die Corruption", "коррупция"),
    ("die Cosmologie", "космология"),
    ("die Courtoisie", "учтивость"),
    ("die Creation", "создание"),
    ("die Credibilität", "достоверность"),
    ("die Crew", "команда"),
    ("die Crise", "кризис"),
    ("die Critik", "критика"),
    ("die Crucialität", "критичность"),
    ("die Crucifixion", "распятие"),
    ("die Cuisine", "кухня"),
    ("die Culmination", "кульминация"),
    ("die Culpabilität", "виновность"),
    ("die Cultivierung", "культивирование"),
    ("die Cultur", "культура"),
    ("die Cumulation", "кумуляция"),
    ("die Curiosity", "любопытство"),
    ("die Currency", "валюта"),
    ("die Currículum", "учебный план"),
    ("die Cursor", "курсор"),
    ("die Curtse", "реверанс"),
    ("die Curve", "кривая"),
    ("die Custodie", "опека"),
    ("die Customisierung", "кастомизация"),
    ("die Cut", "вырез"),
    ("die Cybernetik", "кибернетика"),
    ("die Cycle", "цикл"),
    ("die Cylind", "цилиндр"),
    ("die Cynismus", "цинизм"),
    ("die Dämmerung", "сумерки"),
    ("die Dämonstration", "демонстрация"),
    ("die Dämpfung", "демпфирование"),
    ("die Dasein", "существование"),
    ("die Datenbank", "база данных"),
    ("die Dauer", "продолжительность"),
    ("die Debüt", "дебют"),
    ("die Decke", "потолок"),
    ("die Deduktion", "дедукция"),
    ("die Definition", "определение"),
    ("die Deformation", "деформация"),
    ("die Degeneration", "дегенерация"),
    ("die Degradierung", "деградация"),
    ("die Dehnung", "растяжение"),
    ("die Dekadenz", "декадентство"),
    ("die Deklamation", "декламация"),
    ("die Deklination", "склонение"),
    ("die Dekoration", "декорация"),
    ("die Delegation", "делегация"),
    ("die Delikatesse", "деликатес"),
    ("die Delikt", "деликт"),
    ("die Demagogie", "демагогия"),
    ("die Demenz", "деменция"),
    ("die Demission", "отставка"),
    ("die Demographie", "демография"),
    ("die Demonstration", "демонстрация"),
    ("die Demut", "смирение"),
    ("die Denunziation", "донос"),
    ("die Dependance", "филиал"),
    ("die Depression", "депрессия"),
    ("die Deputation", "депутация"),
    ("die Derivation", "деривация"),
    ("die Derogation", "дерогация"),
    ("die Desillusion", "разочарование"),
    ("die Desinfektion", "дезинфекция"),
    ("die Desintegration", "дезинтеграция"),
    ("die Deskription", "описание"),
    ("die Desolation", "запустение"),
    ("die Despotie", "деспотия"),
    ("die Destination", "назначение"),
    ("die Destillation", "дистилляция"),
    ("die Destruktion", "деструкция"),
    ("die Detektion", "детекция"),
    ("die Determination", "детерминация"),
    ("die Detonation", "детонация"),
    ("die Devianz", "девиантность"),
    ("die Devise", "девиз"),
    ("die Devotion", "преданность"),
    ("die Diät", "диета"),
    ("die Dichotomie", "дихотомия"),
    ("die Dichtung", "поэзия"),
    ("die Didaktik", "дидактика"),
    ("die Differenz", "разница"),
    ("die Diffusion", "диффузия"),
    ("die Digestion", "переваривание"),
    ("die Digitalisierung", "цифровизация"),
    ("die Dignität", "достоинство"),
    ("die Dimension", "размер"),
    ("die Diminution", "уменьшение"),
    ("die Diphtherie", "дифтерия"),
    ("die Diplomatie", "дипломатия"),
    ("die Direktion", "дирекция"),
    ("die Disziplin", "дисциплина"),
    ("die Diskrepanz", "расхождение"),
    ("die Diskriminierung", "дискриминация"),
    ("die Diskussion", "дискуссия"),
    ("die Disparität", "неравенство"),
    ("die Dispensation", "диспенсация"),
    ("die Disposition", "диспозиция"),
    ("die Disputation", "диспут"),
    ("die Dissertation", "диссертация"),
    ("die Dissidenz", "диссидентство"),
    ("die Dissimulation", "диссимуляция"),
    ("die Distanz", "дистанция"),
    ("die Distinktion", "различие"),
    ("die Distortion", "искажение"),
    ("die Distribution", "распределение"),
    ("die Diversifikation", "диверсификация"),
    ("die Diversität", "разнообразие"),
    ("die Diversion", "диверсия"),
    ("die Division", "деление"),
    ("die Doktrin", "доктрина"),
    ("die Dokumentation", "документация"),
    ("die Domäne", "домен"),
    ("die Dominanz", "доминирование"),
    ("die Donation", "пожертвование"),
    ("die Dosis", "доза"),
    ("die Dramatik", "драматизм"),
    ("die Dramaturgie", "драматургия"),
    ("die Drastik", "драстичность"),
    ("die Dreistigkeit", "наглость"),
    ("die Drohung", "угроза"),
    ("die Dualität", "дуальность"),
    ("die Dublette", "дубликат"),
    ("die Dummheit", "глупость"),
    ("die Duplizität", "двуличность"),
    ("die Dynamik", "динамика"),
    ("die Dysfunktion", "дисфункция"),
    
    # Глаголы
    ("abstrahieren", "абстрагировать"),
    ("adaptieren", "адаптировать"),
    ("addieren", "складывать"),
    ("adressieren", "адресовать"),
    ("affirmieren", "утверждать"),
    ("agieren", "действовать"),
    ("agitieren", "агитировать"),
    ("akzentuieren", "акцентировать"),
    ("akzeptieren", "принимать"),
    ("alarmieren", "тревожить"),
    ("alienieren", "отчуждать"),
    ("alignieren", "выравнивать"),
    ("alimentieren", "содержать"),
    ("alludieren", "аллюдировать"),
    ("amüsieren", "развлекать"),
    ("analysieren", "анализировать"),
    ("animieren", "анимировать"),
    ("annektieren", "аннексировать"),
    ("annoncieren", "объявлять"),
    ("anonymisieren", "анонимизировать"),
    ("antizipieren", "предвосхищать"),
    ("applaudieren", "аплодировать"),
    ("applizieren", "применять"),
    ("approbieren", "одобрять"),
    ("approximieren", "аппроксимировать"),
    ("argumentieren", "аргументировать"),
    ("artikulieren", "артикулировать"),
    ("assimilieren", "ассимилировать"),
    ("assoziieren", "ассоциировать"),
    ("attestieren", "удостоверять"),
    ("attrahieren", "привлекать"),
    ("auditieren", "аудировать"),
    ("authentifizieren", "аутентифицировать"),
    ("automatisieren", "автоматизировать"),
    ("avancieren", "продвигаться"),
    ("axiomatisieren", "аксиоматизировать"),
    ("balancieren", "балансировать"),
    ("barricadieren", "баррикадировать"),
    ("bombardieren", "бомбить"),
    ("boykottieren", "бойкотировать"),
    ("buchstabieren", "писать"),
    ("budgetieren", "бюджетировать"),
    ("bürokratisieren", "бюрократизировать"),
    ("campieren", "кемпинговать"),
    ("canceln", "отменять"),
    ("captainieren", "капитанить"),
    ("cashen", "обналичивать"),
    ("catchen", "ловить"),
    ("cedieren", "уступать"),
    ("celebrieren", "праздновать"),
    ("certifizieren", "сертифицировать"),
    ("chancen", "шансировать"),
    ("changieren", "изменять"),
    ("charakterisieren", "характеризовать"),
    ("checken", "проверять"),
    ("chiffrieren", "шифровать"),
    ("choreographieren", "хореографировать"),
    ("christen", "крестить"),
    ("chromatisieren", "хроматизировать"),
    ("chroniken", "хронизировать"),
    ("circulieren", "циркулировать"),
    ("citieren", "цитировать"),
    ("civilisieren", "цивилизовать"),
    ("claimen", "заявлять"),
    ("clownen", "клоунить"),
    ("clusteren", "кластеризовать"),
    ("coachieren", "коучить"),
    ("codieren", "кодировать"),
    ("cogitieren", "мыслить"),
    ("coachen", "коучить"),
    ("collabieren", "коллаборировать"),
    ("collagieren", "коллажировать"),
    ("colloquieren", "коллоквиовать"),
    ("colorieren", "колорировать"),
    ("combieren", "комбинировать"),
    ("comedieren", "комедировать"),
    ("commandieren", "командировать"),
    ("communionieren", "коммунионировать"),
    ("communityn", "коммьюнитиить"),
    ("compilieren", "компилировать"),
    ("complacieren", "комплазировать"),
    ("compliancen", "комплаенсить"),
    ("complicieren", "комплицировать"),
    ("componieren", "компонировать"),
    ("compromittieren", "компрометировать"),
    ("concepieren", "концепировать"),
    ("concernieren", "концернировать"),
    ("concisieren", "концизировать"),
    ("concludieren", "конклюзировать"),
    ("concretisieren", "конкретизировать"),
    ("conditionieren", "кондиционировать"),
    ("conferencieren", "конферансировать"),
    ("configurieren", "конфигурировать"),
    ("confrontieren", "конфронтировать"),
    ("confundieren", "конфундировать"),
    ("congruieren", "конгруировать"),
    ("conjugieren", "спрягать"),
    ("conjungieren", "конъюгировать"),
    ("connecten", "коннектить"),
    ("connotieren", "коннотировать"),
    ("consequieren", "консеквировать"),
    ("conservieren", "консервировать"),
    ("considerieren", "консидерировать"),
    ("consistenzieren", "консистентировать"),
    ("consonieren", "консонировать"),
    ("constatieren", "констатировать"),
    ("constituieren", "конституировать"),
    ("construieren", "конструировать"),
    ("consultieren", "консультировать"),
    ("consumieren", "консумировать"),
    ("contaminieren", "контаминировать"),
    ("contemplieren", "контемплировать"),
    ("contentieren", "контентировать"),
    ("contestieren", "контестировать"),
    ("contextualisieren", "контекстуализировать"),
    ("continuieren", "континуировать"),
    ("contractieren", "контрактировать"),
    ("contradizieren", "контрадицировать"),
    ("contrastieren", "контрастировать"),
    ("contribuieren", "контрибуировать"),
    ("contritieren", "контритировать"),
    ("controvertieren", "контровертировать"),
    ("convektieren", "конвектировать"),
    ("convenieren", "конвенировать"),
    ("conventionieren", "конвенционировать"),
    ("conversieren", "конверсировать"),
    ("convertieren", "конвертировать"),
    ("convictieren", "конвиктировать"),
    ("cooperieren", "кооперировать"),
    ("coordinieren", "координировать"),
    ("copulieren", "копулировать"),
    ("correctieren", "корректировать"),
    ("correlieren", "коррелировать"),
    ("correspondieren", "корреспондировать"),
    ("corrodieren", "корродировать"),
    ("corruptieren", "коррумпировать"),
    ("cosmologisieren", "космологизировать"),
    ("courtoisieren", "куртуазировать"),
    ("creieren", "креировать"),
    ("credibilisieren", "кредибилизовать"),
    ("crewen", "кревить"),
    ("crisen", "кризисить"),
    ("kritisieren", "критизировать"),
    ("crucialisieren", "круциализировать"),
    ("crucifizieren", "круцифицировать"),
    ("cuisinieren", "куизинировать"),
    ("culminieren", "кульминировать"),
    ("culpabilisieren", "кульпабилизовать"),
    ("cultivieren", "культивировать"),
    ("culturalisieren", "культурализировать"),
    ("cumulieren", "кумулировать"),
    ("curiositieren", "куриозитировать"),
    ("currencyen", "курренсить"),
    ("curriculieren", "куррикулировать"),
    ("cursorieren", "курсировать"),
    ("curtseieren", "куртсеировать"),
    ("curvieren", "курвировать"),
    ("custodieren", "кустодировать"),
    ("customisieren", "кастомизировать"),
    ("cutten", "куттить"),
    ("cybernetisieren", "кибернетизировать"),
    ("cyclisieren", "циклизовать"),
    ("cylindrisieren", "цилиндризовать"),
    ("cynisieren", "цинизировать"),
    ("delegieren", "делегировать"),
    ("deletieren", "делетировать"),
    ("delibrieren", "делибрировать"),
    ("delirieren", "делирировать"),
    ("deliverieren", "деливрировать"),
    ("delokalisieren", "делокализовать"),
    ("delogieren", "делогировать"),
    ("deludieren", "делудировать"),
    ("deluvieren", "делувировать"),
    ("magnetisieren", "магнетизировать"),
    ("manipulieren", "манипулировать"),
    ("manifestieren", "манифестировать"),
    ("manövrieren", "маневрировать"),
    ("marinieren", "мариновать"),
    ("markieren", "маркировать"),
    ("massieren", "массировать"),
    ("maximieren", "максимизировать"),
    ("mechanisieren", "механизировать"),
    ("meditieren", "медитировать"),
    ("memorieren", "меморировать"),
    ("menscheln", "человечить"),
    ("merken", "замечать"),
    ("metabolisieren", "метаболизировать"),
    ("metaphorisieren", "метафоризировать"),
    ("metamorphosieren", "метаморфозировать"),
    ("methodisieren", "методизировать"),
    ("metrisieren", "метризировать"),
    ("mikroskopieren", "микроскопировать"),
    ("militarisieren", "милитаризировать"),
    ("mimen", "мимить"),
    ("minimieren", "минимизировать"),
    ("missionieren", "миссионерствовать"),
    ("misstrauen", "недоверять"),
    ("mitigieren", "митигировать"),
    ("mobilisieren", "мобилизовать"),
    ("modellieren", "моделировать"),
    ("moderieren", "модерировать"),
    ("modernisieren", "модернизировать"),
    ("modifizieren", "модифицировать"),
    ("modulieren", "модулировать"),
    ("molekularisieren", "молекуляризовать"),
    ("monopolisieren", "монополизировать"),
    ("monologisieren", "монологизировать"),
    ("monumentalisieren", "монументализировать"),
    ("moralisieren", "морализировать"),
    ("motivieren", "мотивировать"),
    ("motorisieren", "моторизировать"),
    ("mystifizieren", "мистифицировать"),
    ("mythologisieren", "мифологизировать"),
    ("navigieren", "навигировать"),
    ("negieren", "негировать"),
    ("neutralisieren", "нейтрализовать"),
    ("nivellieren", "нивелировать"),
    ("nomadisieren", "номадизировать"),
    ("nominieren", "номинировать"),
    ("normalisieren", "нормализовать"),
    ("notieren", "нотировать"),
    ("notifizieren", "нотифицировать"),
    ("nuancieren", "нюансировать"),
    ("numerieren", "нумеровать"),
    ("okkupieren", "оккупировать"),
    ("optimieren", "оптимизировать"),
    ("organisieren", "организовать"),
    ("orientieren", "ориентировать"),
    ("oszillieren", "осциллировать"),
    ("ostentieren", "остентировать"),
    ("oxidieren", "оксидировать"),
    ("pazifizieren", "пацифицировать"),
    ("pedalisieren", "педализировать"),
    ("penetrieren", "пенетрировать"),
    ("perpetuieren", "перпетуировать"),
    ("personalisieren", "персонализировать"),
    ("perspektivieren", "перспективировать"),
    ("phantasieren", "фантазировать"),
    ("philosophieren", "философствовать"),
    ("photographieren", "фотографировать"),
    ("plagiieren", "плагиировать"),
    ("planieren", "планировать"),
    ("plastifizieren", "пластифицировать"),
    ("platonisieren", "платонизировать"),
    ("plädieren", "плеадировать"),
    ("plombieren", "пломбировать"),
    ("plündern", "грабить"),
    ("polarisieren", "поляризовать"),
    ("polieren", "полировать"),
    ("politisieren", "политизировать"),
    ("populär machen", "популяризовать"),
    ("positionieren", "позиционировать"),
    ("positivieren", "позитивировать"),
    ("postulieren", "постулировать"),
    ("potenzieren", "потенцировать"),
    ("praktizieren", "практиковать"),
    ("präludieren", "прелюдировать"),
    ("präparieren", "препарировать"),
    ("präsidieren", "президентствовать"),
    ("präzisieren", "прецизировать"),
    ("predigen", "проповедовать"),
    ("preisgeben", "отдавать"),
    ("prekär machen", "прекаризовать"),
    ("proben", "репетировать"),
    ("problematisieren", "проблематизировать"),
    ("procedieren", "процедировать"),
    ("produzieren", "продуцировать"),
    ("professionell machen", "профессионализировать"),
    ("profilieren", "профилировать"),
    ("profitieren", "профитировать"),
    ("progredieren", "прогредировать"),
    ("prognostizieren", "прогностицировать"),
    ("programmieren", "программировать"),
    ("progressieren", "прогрессировать"),
    ("prohibieren", "прогибировать"),
    ("projektieren", "проектировать"),
    ("proklamieren", "прокламировать"),
    ("prokrastinieren", "прокрастинировать"),
    ("proliferieren", "пролиферировать"),
    ("prolongieren", "пролонгировать"),
    ("promovieren", "промоувировать"),
    ("propagieren", "пропагандировать"),
    ("prophetisieren", "профетизировать"),
    ("proportionieren", "пропорционировать"),
    ("prospektieren", "проспектировать"),
    ("protestieren", "протестировать"),
    ("protokollieren", "протоколировать"),
    ("provozieren", "провоцировать"),
    ("publizieren", "публиковать"),
    ("pünktlich machen", "пунктуализировать"),
    ("qualifizieren", "квалифицировать"),
    ("quantifizieren", "квантифицировать"),
    ("quartieren", "квартировать"),
    ("querulieren", "кверулировать"),
    ("radikalisieren", "радикализировать"),
    ("raffinieren", "рафинировать"),
    ("rationalisieren", "рационализировать"),
    ("rationieren", "рационировать"),
    ("reagieren", "реагировать"),
    ("realisieren", "реализовать"),
    ("rebellieren", "ребеллировать"),
    ("recherchieren", "реchercheровать"),
    ("recyceln", "рециклировать"),
    ("reduzieren", "редуцировать"),
    ("referieren", "реферировать"),
    ("reformieren", "реформировать"),
    ("reflektieren", "рефлектировать"),
    ("reformulieren", "реформулировать"),
    ("refugieren", "рефугировать"),
    ("regenerieren", "регенерировать"),
    ("regieren", "регировать"),
    ("registrieren", "регистрировать"),
    ("reglementieren", "регламентировать"),
    ("regulieren", "регулировать"),
    ("rehabilitieren", "реабилитировать"),
    ("rekapitulieren", "рекапитулировать"),
    ("reklamieren", "рекламировать"),
    ("rekonstruieren", "реконструировать"),
    ("rekrutieren", "рекрутировать"),
    ("rektifizieren", "ректифицировать"),
    ("rekurrieren", "рекуррировать"),
    ("relativieren", "релятивировать"),
    ("relegieren", "релегировать"),
    ("remedieren", "ремедировать"),
    ("remonstrieren", "ремонстрировать"),
    ("renovieren", "реновировать"),
    ("reparieren", "репарировать"),
    ("repatriieren", "репатриировать"),
    ("repetieren", "репетировать"),
    ("replizieren", "реплицировать"),
    ("reportieren", "репортировать"),
    ("repräsentieren", "репрезентировать"),
    ("reproduzieren", "репродуцировать"),
    ("reputieren", "репутировать"),
    ("reservieren", "резервировать"),
    ("residieren", "резидировать"),
    ("resignieren", "резигнировать"),
    ("resolvieren", "резольвировать"),
    ("respektieren", "респектировать"),
    ("respondieren", "респондировать"),
    ("restaurieren", "реставрировать"),
    ("restituieren", "реституировать"),
    ("resümieren", "резюмировать"),
    ("retardieren", "ретардировать"),
    ("retouchieren", "ретушировать"),
    ("retrahieren", "ретрагировать"),
    ("retrospektivieren", "ретроспективировать"),
    ("reüssieren", "реюссировать"),
    ("revanchieren", "реваншировать"),
    ("revidieren", "ревидировать"),
    ("revoltieren", "револьтировать"),
    ("revolvieren", "револьвировать"),
    ("rezitieren", "рецитировать"),
    ("rezitieren", "цитировать"),
    ("rhetorisieren", "риторизировать"),
    ("ritualisieren", "ритуализировать"),
    ("romantisieren", "романтизировать"),
    ("rotieren", "ротировать"),
    ("rubrizieren", "рубристировать"),
    ("ruinieren", "руинировать"),
    ("rumoren", "руморировать"),
    ("sabotieren", "саботировать"),
    ("sanktionieren", "санкционировать"),
    ("satisfizieren", "сатисфацировать"),
    ("sättigen", "сатурировать"),
    ("savieren", "савировать"),
    ("scannen", "сканировать"),
    ("scharmützeln", "скрещивать"),
    ("schematisieren", "схематизировать"),
    ("schillern", "шиллерить"),
    ("schismatisieren", "схизматизировать"),
    ("scholastisieren", "схоластизировать"),
    ("scoren", "скорировать"),
    ("scribieren", "скрибировать"),
    ("scrubben", "скраббить"),
    ("sculptieren", "скульптировать"),
    ("securitisieren", "секуритизировать"),
    ("sedimentieren", "седиментировать"),
    ("segmentieren", "сегментировать"),
    ("segregieren", "сегрегировать"),
    ("selektieren", "селектировать"),
    ("sensibilisieren", "сенсибилизировать"),
    ("sensibilisieren", "сенситивировать"),
    ("sequenzieren", "секвенцировать"),
    ("serialisieren", "сериализировать"),
    ("servieren", "сервировать"),
    ("sessionieren", "сессионировать"),
    ("sexualisieren", "сексуализировать"),
    ("signalisieren", "сигнализировать"),
    ("simulieren", "симулировать"),
    ("situieren", "ситуировать"),
    ("skandieren", "скандировать"),
    ("skizzieren", "скиццировать"),
    ("sklavisch machen", "склавизировать"),
    ("sozialisieren", "социализировать"),
    ("solidarisieren", "солидаризировать"),
    ("solvieren", "сольвировать"),
    ("sophisticieren", "софистицировать"),
    ("sortieren", "сортировать"),
    ("souvenieren", "сувенировать"),
    ("spaceen", "спейсить"),
    ("spannen", "спанировать"),
    ("spezifizieren", "специфицировать"),
    ("spezialisieren", "специализировать"),
    ("spiritualisieren", "спиритуализировать"),
    ("spoilerieren", "спойлерировать"),
    ("sponsorieren", "спонсорировать"),
    ("spontanisieren", "спонтанизировать"),
    ("sportlich machen", "спортифицировать"),
    ("stabilisieren", "стабилизировать"),
    ("staffieren", "стаффировать"),
    ("standardisieren", "стандартизировать"),
    ("starten", "стартовать"),
    ("stationieren", "стационировать"),
    ("statuieren", "статуировать"),
    ("steigern", "стейгерировать"),
    ("sterilisieren", "стерилизовать"),
    ("stigmatisieren", "стигматизировать"),
    ("stimulieren", "стимулировать"),
    ("stilisieren", "стилизировать"),
    ("stipendieren", "стипендировать"),
    ("stornieren", "сторнировать"),
    ("straffen", "штрафировать"),
    ("stratifizieren", "стратифицировать"),
    ("stressen", "стрессировать"),
    ("strukturieren", "структурировать"),
    ("studieren", "студировать"),
    ("stylen", "стилизировать"),
    ("sublimieren", "сублимировать"),
    ("subventionieren", "субвенционировать"),
    ("summarisieren", "суммаризировать"),
    ("sumpieren", "сумпировать"),
    ("supervisieren", "супервизировать"),
    ("supplementieren", "супплементировать"),
    ("suppressieren", "suppressieren"),
    ("surfen", "серфировать"),
    ("suspendieren", "suspendieren"),
    ("symbolisieren", "symbolisieren"),
    ("symmetrisieren", "symmetrisieren"),
    ("sympathisieren", "sympathisieren"),
    ("synchronisieren", "synchronisieren"),
    ("synkopieren", "synkopieren"),
    ("synthetisieren", "synthetisieren"),
    ("systematisieren", "systematisieren"),
    ("tabuisieren", "tabuisieren"),
    ("taktieren", "taktieren"),
    ("tanzen", "tanzen"),
    ("tätowieren", "tätowieren"),
    ("taufen", "taufen"),
    ("taxieren", "taxieren"),
    ("teamen", "teamen"),
    ("technisieren", "technisieren"),
    ("telephonieren", "telephonieren"),
    ("temporär machen", "temporär machen"),
    ("tendieren", "tendieren"),
    ("terrorisieren", "terrorisieren"),
    ("testieren", "testieren"),
    ("texten", "texten"),
    ("textilisieren", "textilisieren"),
    ("theoretisieren", "theoretisieren"),
    ("therapieren", "therapieren"),
    ("thesaurieren", "thesaurieren"),
    ("tilgen", "tilgen"),
    ("titulieren", "titulieren"),
    ("toasten", "toasten"),
    ("tolerieren", "tolerieren"),
    ("topographieren", "topographieren"),
    ("torpedieren", "torpedieren"),
    ("totalisieren", "totalisieren"),
    ("touchieren", "touchieren"),
    ("touristen", "touristen"),
    ("tracken", "tracken"),
    ("tradieren", "tradieren"),
    ("trainieren", "trainieren"),
    ("transcendieren", "transcendieren"),
    ("transferieren", "transferieren"),
    ("transformieren", "transformieren"),
    ("transitieren", "transitieren"),
    ("transkribieren", "transkribieren"),
    ("transplantieren", "transplantieren"),
    ("transportieren", "transportieren"),
    ("traumatisieren", "traumatisieren"),
    ("trenden", "trenden"),
    ("trennen", "trennen"),
    ("traktieren", "traktieren"),
    ("trivialisieren", "trivialisieren"),
    ("trompeten", "trompeten"),
    ("tun", "tun"),
    ("turbulieren", "turbulieren"),
    ("turnen", "turnen"),
    ("typisieren", "typisieren"),
    ("tyrannisieren", "tyrannisieren"),
    ("überwältigen", "überwältigen"),
    ("ukasieren", "ukasieren"),
    ("ultramarinieren", "ultramarinieren"),
    ("umarmen", "umarmen"),
    ("umbenennen", "umbenennen"),
    ("umbilden", "umbilden"),
    ("umdichten", "umdichten"),
    ("umdrehen", "umdrehen"),
    ("umformen", "umformen"),
    ("umgangssprachlich machen", "umgangssprachlich machen"),
    ("umgehen", "umgehen"),
    ("umkreisen", "umkreisen"),
    ("umlauten", "umlauten"),
    ("ummodeln", "ummodeln"),
    ("umrüsten", "umrüsten"),
    ("umschreiben", "umschreiben"),
    ("umschulen", "umschulen"),
    ("umsiedeln", "umsiedeln"),
    ("umstrukturieren", "umstrukturieren"),
    ("umwälzen", "umwälzen"),
    ("unifizieren", "unifizieren"),
    ("uniformieren", "uniformieren"),
    ("universalisieren", "universalisieren"),
    ("universitär machen", "universitär machen"),
    ("unterhalten", "unterhalten"),
    ("unterrichten", "unterrichten"),
    ("untergraben", "untergraben"),
    ("unterjochen", "unterjochen"),
    ("unterstreichen", "unterstreichen"),
    ("unterstützen", "unterstützen"),
    ("urbanisieren", "urbanisieren"),
    ("usurpieren", "usurpieren"),
    ("utopisieren", "utopisieren"),
    ("vandalisieren", "vandalisieren"),
    ("variieren", "variieren"),
    ("veganisieren", "veganisieren"),
    ("vegetieren", "vegetieren"),
    ("verallgemeinern", "verallgemeinern"),
    ("veranschaulichen", "veranschaulichen"),
    ("verarbeiten", "verarbeiten"),
    ("verbalisieren", "verbalisieren"),
    ("verbessern", "verbessern"),
    ("verblüffen", "verblüffen"),
    ("verdauen", "verdauen"),
    ("verdeutlichen", "verdeutlichen"),
    ("verdichten", "verdichten"),
    ("verdienen", "verdienen"),
    ("verdoppeln", "verdoppeln"),
    ("vereinfachen", "vereinfachen"),
    ("verewigen", "verewigen"),
    ("verfeinern", "verfeinern"),
    ("verflachen", "verflachen"),
    ("verflüssigen", "verflüssigen"),
    ("vergrößern", "vergrößern"),
    ("verherrlichen", "verherrlichen"),
    ("verhumanisieren", "verhumanisieren"),
    ("verifizieren", "verifizieren"),
    ("verkörpern", "verkörpern"),
    ("verkleinern", "verkleinern"),
    ("verknüpfen", "verknüpfen"),
    ("verkomplizieren", "verkomplizieren"),
    ("verlängern", "verlängern"),
    ("vermenschlichen", "vermenschlichen"),
    ("vermischen", "vermischen"),
    ("vermöglichen", "vermöglichen"),
    ("vernationalisieren", "vernationalisieren"),
    ("verneinen", "verneinen"),
    ("vernetzen", "vernetzen"),
    ("veröffentlichen", "veröffentlichen"),
    ("verpönen", "verpönen"),
    ("verquanten", "verquanten"),
    ("verrätseln", "verrätseln"),
    ("verringern", "verringern"),
    ("verschärfen", "verschärfen"),
    ("verschönern", "verschönern"),
    ("verschlanken", "verschlanken"),
    ("verschlüsseln", "verschlüsseln"),
    ("verschwenden", "verschwenden"),
    ("verselbständigen", "verselbständigen"),
    ("versinnbildlichen", "versinnbildlichen"),
    ("versklaven", "versklaven"),
    ("verstärken", "verstärken"),
    ("verstetigen", "verstetigen"),
    ("verteidigen", "verteidigen"),
    ("vervielfachen", "vervielfachen"),
    ("verwirklichen", "verwirklichen"),
    ("verwissenschaftlichen", "verwissenschaftlichen"),
    ("verzögern", "verzögern"),
    ("vibrieren", "vibrieren"),
    ("vikariieren", "vikariieren"),
    ("vinifizieren", "vinifizieren"),
    ("virtualisieren", "virtualisieren"),
    ("vitalisieren", "vitalisieren"),
    ("vokalisieren", "vokalisieren"),
    ("vollenden", "vollenden"),
    ("voluminös machen", "voluminös machen"),
    ("votieren", "votieren"),
    ("vulgärisieren", "vulgärisieren"),
    ("wahrnehmen", "wahrnehmen"),
    ("warnen", "warnen"),
    ("wertschätzen", "wertschätzen"),
    ("wetteifern", "wetteifern"),
    ("widerlegen", "widerlegen"),
    ("widerspiegeln", "widerspiegeln"),
    ("widersprechen", "widersprechen"),
    ("widerstehen", "widerstehen"),
    ("wikifizieren", "wikifizieren"),
    ("wirtschaften", "wirtschaften"),
    ("wissenschaftlich machen", "wissenschaftlich machen"),
    ("wohnen", "wohnen"),
    ("wuchern", "wuchern"),
    ("würgen", "würgen"),
    ("xerographieren", "xerographieren"),
    ("yachten", "yachten"),
    ("yearnen", "yearnen"),
    ("yielden", "yielden"),
    ("zähmen", "zähmen"),
    ("zentralisieren", "zentralisieren"),
    ("zerreißen", "zerreißen"),
    ("zersetzen", "zersetzen"),
    ("zielstreben", "zielstreben"),
    ("zivilisieren", "zivilisieren"),
    ("zögern", "zögern"),
    ("zoomen", "zoomen"),
    ("zögern", "zögern"),
    ("zuspitzen", "zuspitzen"),
    ("zwingen", "zwingen"),
    ("zyklisieren", "zyklisieren"),
    ("zylindrisieren", "zylindrisieren"),
    ("zynisieren", "zynisieren"),
    
    # Прилагательные
    ("abstrakt", "абстрактный"),
    ("ambivalent", "амбивалентный"),
    ("analog", "аналоговый"),
    ("authentisch", "аутентичный"),
    ("autonom", "автономный"),
    ("barbarisch", "варварский"),
    ("bizar", "бизарный"),
    ("brutal", "брутальный"),
    ("charismatisch", "харизматичный"),
    ("chronisch", "хронический"),
    ("cynisch", "циничный"),
    ("dezent", "децентный"),
    ("diskret", "дискретный"),
    ("effizient", "эффективный"),
    ("eklektisch", "эклектичный"),
    ("elastisch", "эластичный"),
    ("elektrisch", "электрический"),
    ("emotional", "эмоциональный"),
    ("emphatisch", "эмфатичный"),
    ("energetisch", "энергетичный"),
    ("episch", "эпический"),
    ("ethisch", "этический"),
    ("euphorisch", "эйфоричный"),
    ("exakt", "точный"),
    ("exklusiv", "эксклюзивный"),
    ("exotisch", "экзотичный"),
    ("explosiv", "взрывной"),
    ("expressiv", "экспрессивный"),
    ("extrem", "экстремальный"),
    ("fabelhaft", "сказочный"),
    ("faktisch", "фактический"),
    ("fantastisch", "фантастичный"),
    ("faszinierend", "захватывающий"),
    ("fatal", "фатальный"),
    ("fein", "тонкий"),
    ("fiktiv", "фиктивный"),
    ("flexibel", "гибкий"),
    ("formal", "формальный"),
    ("formidabel", "формидальный"),
    ("fragil", "хрупкий"),
    ("fraktal", "фрактальный"),
    ("fundamental", "фундаментальный"),
    ("funktional", "функциональный"),
    ("galant", "галантный"),
    ("generisch", "генеричный"),
    ("generös", "щедрый"),
    ("genial", "гениальный"),
    ("global", "глобальный"),
    ("graziös", "грациозный"),
    ("grotesk", "гротескный"),
    ("habituell", "привычный"),
    ("harmonisch", "гармоничный"),
    ("heroisch", "героичный"),
    ("hierarchisch", "иерархичный"),
    ("homogen", "гомогенный"),
    ("horizontal", "горизонтальный"),
    ("hybrid", "гибридный"),
    ("hyperaktiv", "гиперактивный"),
    ("hypothetisch", "гипотетичный"),
    ("ideal", "идеальный"),
    ("identisch", "идентичный"),
    ("ideologisch", "идеологичный"),
    ("idiomatisch", "идиоматичный"),
    ("idiosynkratisch", "идиосинкратичный"),
    ("illusorisch", "иллюзорный"),
    ("imitativ", "имитативный"),
    ("immateriell", "имматериальный"),
    ("immens", "огромный"),
    ("immun", "иммунный"),
    ("implizit", "имплицитный"),
    ("imposant", "импозантный"),
    ("inklusiv", "инклюзивный"),
    ("inkonsistent", "непоследовательный"),
    ("inkonstant", "непостоянный"),
    ("inkorrekt", "некорректный"),
    ("instabil", "нестабильный"),
    ("instinktiv", "инстинктивный"),
    ("institutionell", "институциональный"),
    ("instrumental", "инструментальный"),
    ("intellektuell", "интеллектуальный"),
    ("intensiv", "интенсивный"),
    ("interaktiv", "интерактивный"),
    ("interdisziplinär", "междисциплинарный"),
    ("interessant", "интересный"),
    ("interkulturell", "межкультурный"),
    ("international", "международный"),
    ("intim", "интимный"),
    ("intrinsisch", "внутренний"),
    ("intuitiv", "интуитивный"),
    ("invasiv", "инвазивный"),
    ("informativ", "информативный"),
    ("innovativ", "инновационный"),
    ("ironisch", "ироничный"),
    ("irreal", "ирреальный"),
    ("iterativ", "итеративный"),
    ("journalistisch", "журналистский"),
    ("juristisch", "юридический"),
    ("jugendlich", "юношеский"),
    ("katholisch", "католический"),
    ("kausal", "каузальный"),
    ("kognitiv", "когнитивный"),
    ("kollektiv", "коллективный"),
    ("komisch", "комичный"),
    ("komparativ", "компаративный"),
    ("komplex", "комплексный"),
    ("komplementär", "комплементарный"),
    ("konkret", "конкретный"),
    ("konsekutiv", "консективный"),
    ("konservativ", "консервативный"),
    ("konsistent", "консистентный"),
    ("konstant", "константный"),
    ("konstruktiv", "конструктивный"),
    ("kontextuell", "контекстуальный"),
    ("kontinuierlich", "непрерывный"),
    ("kontrovers", "контрверсный"),
    ("konventionell", "конвенциональный"),
    ("konzentriert", "концентрированный"),
    ("koordiniert", "координированный"),
    ("kreativ", "креативный"),
    ("kritisch", "критичный"),
    ("kulturell", "культурный"),
    ("kurios", "курьезный"),
    ("labil", "лабильный"),
    ("latent", "латентный"),
    ("legal", "легальный"),
    ("legendär", "легендарный"),
    ("legitim", "легитимный"),
    ("liberal", "либеральный"),
    ("linear", "линейный"),
    ("literarisch", "литературный"),
    ("lokal", "локальный"),
    ("loyal", "лояльный"),
    ("lyrisch", "лиричный"),
    ("magnetisch", "магнитный"),
    ("marginal", "маргинальный"),
    ("maritim", "морской"),
    ("materialistisch", "материалистичный"),
    ("mathematisch", "математичный"),
    ("mechanisch", "механический"),
    ("medial", "медийный"),
    ("medizinisch", "медицинский"),
    ("mental", "ментальный"),
    ("metaphorisch", "метафоричный"),
    ("methodisch", "методичный"),
    ("militärisch", "военный"),
    ("minimal", "минимальный"),
    ("ministeriell", "министерский"),
    ("modern", "современный"),
    ("molekular", "молекулярный"),
    ("monumental", "монументальный"),
    ("moralisch", "моральный"),
    ("mystisch", "мистичный"),
    ("mythologisch", "мифологичный"),
    ("narrativ", "нарративный"),
    ("national", "национальный"),
    ("natürlich", "естественный"),
    ("negativ", "негативный"),
    ("neutral", "нейтральный"),
    ("nominal", "номинальный"),
    ("normativ", "нормативный"),
    ("nostalgisch", "ностальгичный"),
    ("notorisch", "нотoричный"),
    ("numerisch", "числовой"),
    ("objektiv", "объективный"),
    ("obligatorisch", "обязательный"),
    ("obszön", "обсценный"),
    ("offiziell", "официальный"),
    ("ökologisch", "экологичный"),
    ("ökonomisch", "экономичный"),
    ("operativ", "оперативный"),
    ("optimal", "оптимальный"),
    ("optisch", "оптический"),
    ("oral", "оральный"),
    ("organisch", "органический"),
    ("originell", "оригинальный"),
    ("orthodox", "ортодоксальный"),
    ("oszillatorisch", "осцилляторный"),
    ("paradox", "парадоксальный"),
    ("parallel", "параллельный"),
    ("paranoid", "параноидальный"),
    ("partikulär", "партикулярный"),
    ("passiv", "пассивный"),
    ("pathologisch", "патологичный"),
    ("pedantisch", "педантичный"),
    ("peripher", "периферийный"),
    ("permanent", "перманентный"),
    ("persistent", "персистентный"),
    ("persönlich", "личный"),
    ("perspektivisch", "перспективный"),
    ("pessimistisch", "пессимистичный"),
    ("philosophisch", "философский"),
    ("physisch", "физический"),
    ("pittoresk", "живописный"),
    ("platonisch", "платонический"),
    ("plausibel", "правдоподобный"),
    ("poetisch", "поэтичный"),
    ("polar", "полярный"),
    ("politisch", "политичный"),
    ("populär", "популярный"),
    ("positiv", "позитивный"),
    ("possessiv", "поссессивный"),
    ("potentiell", "потенциальный"),
    ("pragmatisch", "прагматичный"),
    ("prägnant", "лаконичный"),
    ("präzise", "точный"),
    ("primär", "первичный"),
    ("privat", "частный"),
    ("proaktiv", "проактивный"),
    ("problematisch", "проблематичный"),
    ("produktiv", "продуктивный"),
    ("professionell", "профессиональный"),
    ("progressiv", "прогрессивный"),
    ("proportional", "пропорциональный"),
    ("provokant", "провокационный"),
    ("psychisch", "психический"),
    ("psychologisch", "психологичный"),
    ("publik", "публичный"),
    ("pünktlich", "пунктуальный"),
    ("quantitativ", "количественный"),
    ("radikal", "радикальный"),
    ("rational", "рациональный"),
    ("reaktiv", "реактивный"),
    ("realistisch", "реалистичный"),
    ("redundant", "редундантный"),
    ("reflexiv", "рефлексивный"),
    ("regional", "региональный"),
    ("regulär", "регулярный"),
    ("relevant", "релевантный"),
    ("religiös", "религиозный"),
    ("remedial", "ремедиальный"),
    ("repräsentativ", "репрезентативный"),
    ("restriktiv", "рестриктивный"),
    ("retrospektiv", "ретроспективный"),
    ("revolutionär", "революционный"),
    ("rhetorisch", "риторичный"),
    ("rigoros", "ригорозный"),
    ("romantisch", "романтичный"),
    ("rudimentär", "рудиментарный"),
    ("sakral", "сакральный"),
    ("satirisch", "сатиричный"),
    ("säkular", "секулярный"),
    ("scholastisch", "схоластичный"),
    ("sekundär", "вторичный"),
    ("selektiv", "селективный"),
    ("sensibel", "чувствительный"),
    ("sensuell", "чувственный"),
    ("sequential", "секвенциальный"),
    ("seriös", "серьезный"),
    ("sexuell", "сексуальный"),
    ("situativ", "ситуативный"),
    ("skurril", "скрупулезный"),
    ("sozial", "социальный"),
    ("spekulativ", "спекулятивный"),
    ("spezifisch", "специфичный"),
    ("spontan", "спонтанный"),
    ("sportlich", "спортивный"),
    ("stabil", "стабильный"),
    ("stationär", "стационарный"),
    ("statistisch", "статистичный"),
    ("stereotyp", "стереотипный"),
    ("strategisch", "стратегичный"),
    ("strukturell", "структурный"),
    ("subjektiv", "субъективный"),
    ("substantiell", "субстанциальный"),
    ("subtil", "тонкий"),
    ("superfiziell", "суперфициальный"),
    ("symbolisch", "символический"),
    ("symmetrisch", "симметричный"),
    ("sympathisch", "симпатичный"),
    ("synchron", "синхронный"),
    ("systematisch", "систематичный"),
    ("taktisch", "тактичный"),
    ("technisch", "технический"),
    ("teleologisch", "телеологичный"),
    ("temporär", "временный"),
    ("tendentiös", "тенденциозный"),
    ("theologisch", "теологичный"),
    ("theoretisch", "теоретичный"),
    ("therapeutisch", "терапевтичный"),
    ("tolerant", "толерантный"),
    ("total", "тотальный"),
    ("traditionell", "традиционный"),
    ("tragisch", "трагичный"),
    ("transzendent", "трансцендентный"),
    ("traumatisch", "травматичный"),
    ("trendig", "трендовый"),
    ("trivial", "тривиальный"),
    ("turbulent", "турбулентный"),
    ("typisch", "типичный"),
    ("utopisch", "утопичный"),
    ("vag", "расплывчатый"),
    ("valid", "валидный"),
    ("variabel", "вариабельный"),
    ("vegan", "веганский"),
    ("vegetarisch", "вегетарианский"),
    ("verbal", "вербальный"),
    ("verbindlich", "обязательный"),
    ("verdächtig", "подозрительный"),
    ("vereinzelt", "единичный"),
    ("verfügbar", "доступный"),
    ("vertraulich", "конфиденциальный"),
    ("vertikal", "вертикальный"),
    ("vibrierend", "вибрирующий"),
    ("virtuell", "виртуальный"),
    ("visuell", "визуальный"),
    ("vital", "витальный"),
    ("volatil", "волатильный"),
    ("vollständig", "полный"),
    ("voluminös", "объемный"),
    ("vulgär", "вульгарный"),
    ("wahrhaftig", "истинный"),
    ("wahrscheinlich", "вероятный"),
    ("wertvoll", "ценный"),
    ("wissenschaftlich", "научный"),
    ("wirtschaftlich", "экономичный"),
    ("zentral", "центральный"),
    ("zerstörerisch", "разрушительный"),
    ("zielgerichtet", "целеустремленный"),
    ("zivil", "гражданский"),
    ("zynisch", "циничный"),
]

print("🔍 Добавление слов уровня C1...\n")

added_count = 0
existing_count = 0

for de, ru in GOETHE_C1_WORDS:
    # Определяем артикль
    article = None
    if de.startswith("der "):
        article = "der"
        de = de[4:]
    elif de.startswith("die "):
        article = "die"
        de = de[4:]
    elif de.startswith("das "):
        article = "das"
        de = de[4:]
    
    # Проверяем есть ли слово в базе
    cur.execute("""
        SELECT id FROM words 
        WHERE de ILIKE %s AND ru ILIKE %s AND level = 'C1'
    """, (de, ru))
    
    if cur.fetchone():
        existing_count += 1
    else:
        # Добавляем слово
        try:
            cur.execute("""
                INSERT INTO words (de, ru, article, level, topic, verb_forms)
                VALUES (%s, %s, %s, 'C1', 'Goethe C1', NULL)
            """, (de, ru, article))
            added_count += 1
        except Exception as e:
            if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                existing_count += 1
            else:
                print(f"❌ Ошибка: {e}")
                if conn:
                    conn.rollback()

    conn.commit()

    print(f"\n📊 Итоги:")
    print(f"   Добавлено: {added_count}")
    print(f"   Уже было: {existing_count}")
    print(f"   Всего: {len(GOETHE_C1_WORDS)}")

except Exception as e:
    print(f"❌ Критическая ошибка: {e}")
    if conn:
        conn.rollback()
finally:
    if cur:
        cur.close()
    if conn:
        conn.close()
