#!/usr/bin/env python3
"""
Проверить и добавить слова Goethe Institut для всех уровней (A2, B1, B2, C1)
"""

import os, sys, io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env.local'))

import psycopg2

conn = psycopg2.connect(os.environ.get("POSTGRES_URL"))
cur = conn.cursor()

# Словарь Goethe Institut по уровням
GOETHE_WORDS = {
    'A2': [
        # Существительные
        ("die Abteilung", "отдел"),
        ("der Abschluss", "завершение"),
        ("die Aktivität", "активность"),
        ("die Aktion", "акция"),
        ("die Alternative", "альтернатива"),
        ("die Analyse", "анализ"),
        ("die Anerkennung", "признание"),
        ("die Anzeige", "объявление"),
        ("die Apotheke", "аптека"),
        ("die Anwendung", "применение"),
        ("die Arbeitsstelle", "рабочее место"),
        ("die Ausbildung", "образование"),
        ("die Auskunft", "информация"),
        ("der Ausdruck", "выражение"),
        ("die Aufgabe", "задача"),
        ("die Aufführung", "представление"),
        ("die Ausbildung", "обучение"),
        ("der Aufenthalt", "пребывание"),
        ("die Ausstellung", "выставка"),
        ("die Ausnahme", "исключение"),
        ("die Aussage", "высказывание"),
        ("die Auswahl", "выбор"),
        ("die Beziehung", "отношение"),
        ("die Bearbeitung", "обработка"),
        ("die Berechtigung", "разрешение"),
        ("die Beschreibung", "описание"),
        ("die Beschwerde", "жалоба"),
        ("die Besprechung", "совещание"),
        ("die Bewerbung", "заявка"),
        ("die Beteiligung", "участие"),
        ("die Bewegung", "движение"),
        ("die Bibliothek", "библиотека"),
        ("die Bildung", "образование"),
        ("die Bitte", "просьба"),
        ("die Bilanz", "баланс"),
        ("die Biografie", "биография"),
        ("die Bühne", "сцена"),
        ("die Burg", "замок"),
        ("die Börse", "биржа"),
        ("das Baby", "ребенок"),
        ("das Bad", "ванная"),
        ("das Bankkonto", "банковский счет"),
        ("das Bauernhaus", "фермерский дом"),
        ("das Beamte", "чиновник"),
        ("das Bedauern", "сожаление"),
        ("das Bedürfnis", "потребность"),
        ("das Bein", "нога"),
        ("das Beispiel", "пример"),
        ("das Bekannt", "знакомый"),
        ("das Benzin", "бензин"),
        ("das Beratung", "консультация"),
        ("das Berg", "гора"),
        ("das Bericht", "отчет"),
        ("das Besitz", "владение"),
        ("das Beton", "бетон"),
        ("das Bibliothek", "библиотека"),
        ("das Bier", "пиво"),
        ("das Billett", "билет"),
        ("das Bindung", "связь"),
        ("das Biologie", "биология"),
        ("das Bischof", "епископ"),
        ("das Blatt", "лист"),
        ("das Blau", "синий"),
        ("das Blech", "лист металла"),
        ("das Blick", "взгляд"),
        ("das Block", "блок"),
        ("das Blume", "цветок"),
        ("das Blut", "кровь"),
        ("das Boden", "пол"),
        ("das Bohrer", "сверло"),
        ("das Bombe", "бомба"),
        ("das Bonbon", "конфета"),
        ("das Boot", "лодка"),
        ("das Bord", "борт"),
        ("das Bote", "посланник"),
        ("das Box", "коробка"),
        ("das Branche", "отрасль"),
        ("das Brand", "пожар"),
        ("das Brot", "хлеб"),
        ("das Brücke", "мост"),
        ("das Buch", "книга"),
        ("das Bühne", "сцена"),
        ("das Bund", "союз"),
        ("das Burg", "замок"),
        ("das Bus", "автобус"),
        ("das Büro", "офис"),
        
        # Глаголы
        ("abbauen", "сокращать"),
        ("abfahren", "отправляться"),
        ("abgeben", "сдавать"),
        ("abhängen", "зависеть"),
        ("abheben", "снимать"),
        ("abholen", "забирать"),
        ("absagen", "отменять"),
        ("abschließen", "завершать"),
        ("absenden", "отправлять"),
        ("abstellen", "ставить"),
        ("abstürzen", "падать"),
        ("abtrocknen", "вытирать"),
        ("abwaschen", "мыть"),
        ("abwenden", "отворачивать"),
        ("ahnen", "предчувствовать"),
        ("akzeptieren", "принимать"),
        ("aktivieren", "активировать"),
        ("alarmieren", "тревожить"),
        ("analysieren", "анализировать"),
        ("anbieten", "предлагать"),
        ("andenken", "думать"),
        ("anerkannt", "признавать"),
        ("anfangen", "начинать"),
        ("anfragen", "спрашивать"),
        ("angeben", "указывать"),
        ("angewöhnen", "привыкать"),
        ("anklicken", "нажимать"),
        ("ankommen", "прибывать"),
        ("ankündigen", "объявлять"),
        ("anmelden", "регистрировать"),
        ("annehmen", "принимать"),
        ("anpassen", "приспосабливать"),
        ("anrufen", "звонить"),
        ("anschauen", "смотреть"),
        ("anschließen", "подключать"),
        ("anschreiben", "писать"),
        ("ansehen", "смотреть"),
        ("ansprechen", "обращаться"),
        ("anstrengen", "напрягать"),
        ("antreffen", "встречать"),
        ("anvertrauen", "доверять"),
        ("anwenden", "применять"),
        ("anzeigen", "показывать"),
        ("arbeiten", "работать"),
        ("argern", "сердить"),
        ("atmen", "дышать"),
        ("attrahieren", "привлекать"),
        ("aufbauen", "строить"),
        ("aufbewahren", "хранить"),
        ("aufbieten", "призывать"),
        ("aufbrechen", "вскрывать"),
        ("auffallen", "бросаться"),
        ("auffordern", "требовать"),
        ("aufführen", "исполнять"),
        ("aufgeben", "сдаваться"),
        ("aufhalten", "останавливать"),
        ("aufheben", "поднимать"),
        ("aufhören", "прекращать"),
        ("aufladen", "заряжать"),
        ("auflösen", "растворять"),
        ("aufmachen", "открывать"),
        ("aufmerksam", "внимательный"),
        ("aufnehmen", "принимать"),
        ("aufräumen", "убирать"),
        ("aufrufen", "вызывать"),
        ("aufrichten", "поднимать"),
        ("aufsagen", "отменять"),
        ("aufschreiben", "записывать"),
        ("aufstehen", "вставать"),
        ("auftauchen", "появляться"),
        ("auftragen", "наносить"),
        ("aufwachen", "просыпаться"),
        ("ausbilden", "обучать"),
        ("ausdrucken", "печатать"),
        ("auseinander", "раздельно"),
        ("ausfüllen", "заполнять"),
        ("ausgehen", "выходить"),
        ("aushalten", "выдерживать"),
        ("auskennen", "знать"),
        ("auslöschen", "стирать"),
        ("ausmachen", "выключать"),
        ("ausnutzen", "использовать"),
        ("ausprobieren", "пробовать"),
        ("ausreichen", "хватать"),
        ("ausrufen", "восклицать"),
        ("aussagen", "заявлять"),
        ("ausschalten", "выключать"),
        ("ausschließen", "исключать"),
        ("ausschreiben", "выписывать"),
        ("aussehen", "выглядеть"),
        ("aussortieren", "сортировать"),
        ("aussprechen", "произносить"),
        ("ausstellen", "выставлять"),
        ("aussteigen", "выходить"),
        ("austauschen", "обменивать"),
        ("austeilen", "раздавать"),
        ("austragen", "выносить"),
        ("austreten", "выходить"),
        ("ausüben", "осуществлять"),
        ("auswählen", "выбирать"),
        ("auswandern", "эмигрировать"),
        ("ausweichen", "избегать"),
        ("auswerten", "оценивать"),
        ("ausziehen", "снимать"),
        ("backen", "печь"),
        ("bahnen", "прокладывать"),
        ("balance", "балансировать"),
        ("bandagieren", "бинтовать"),
        ("bändigen", "укрощать"),
        ("bankrott", "банкрот"),
        ("bar", "наличный"),
        ("basteln", "мастерить"),
        ("bauen", "строить"),
        ("baumeln", "болтаться"),
        ("beachten", "соблюдать"),
        ("beantragen", "заявлять"),
        ("beantworten", "отвечать"),
        ("bearbeiten", "обрабатывать"),
        ("beauftragen", "поручать"),
        ("beobachten", "наблюдать"),
        ("begeistern", "восхищать"),
        ("beginnen", "начинать"),
        ("begraben", "хоронить"),
        ("begründen", "обосновывать"),
        ("begrüßen", "приветствовать"),
        ("behalten", "сохранять"),
        ("behaupten", "утверждать"),
        ("behandeln", "лечить"),
        ("beherrschen", "владеть"),
        ("behalten", "держать"),
        ("behindern", "мешать"),
        ("beibringen", "обучать"),
        ("beichten", "исповедовать"),
        ("beifügen", "прилагать"),
        ("begeistern", "восторгать"),
        ("begleiten", "сопровождать"),
        ("begnügen", "довольствоваться"),
        ("begutachten", "оценивать"),
        ("beherbergen", "размещать"),
        ("behindern", "препятствовать"),
        ("bejahen", "подтверждать"),
        ("bekämpfen", "бороться"),
        ("bekannt", "известный"),
        ("bekommen", "получать"),
        ("belasten", "нагружать"),
        ("beleidigen", "оскорблять"),
        ("belegen", "занимать"),
        ("belehren", "поучать"),
        ("belieben", "нравиться"),
        ("bemerken", "замечать"),
        ("bemühen", "стараться"),
        ("benachrichtigen", "уведомлять"),
        ("benennen", "переименовывать"),
        ("benutzen", "использовать"),
        ("beobachten", "наблюдать"),
        ("beraten", "консультировать"),
        ("berechnen", "вычислять"),
        ("bereiten", "готовить"),
        ("berichten", "сообщать"),
        ("berücksichtigen", "учитывать"),
        ("berufen", "призывать"),
        ("berühren", "касаться"),
        ("beschädigen", "повреждать"),
        ("beschäftigen", "занимать"),
        ("beschließen", "решать"),
        ("beschreiben", "описывать"),
        ("beschützen", "защищать"),
        ("beschweren", "жаловаться"),
        ("beseitigen", "устранять"),
        ("besichtigen", "осматривать"),
        ("besitzen", "владеть"),
        ("besorgen", "доставать"),
        ("besprechen", "обсуждать"),
        ("besser", "лучше"),
        ("bestätigen", "подтверждать"),
        ("bestehen", "состоять"),
        ("bestellen", "заказывать"),
        ("bestimmen", "определять"),
        ("bestrafen", "наказывать"),
        ("besuchen", "посещать"),
        ("beteiligen", "участвовать"),
        ("betonen", "подчеркивать"),
        ("betragen", "составлять"),
        ("betreuen", "заботиться"),
        ("betreten", "входить"),
        ("betrügen", "обманывать"),
        ("beurteilen", "оценивать"),
        ("bevölkern", "населить"),
        ("bewahren", "сохранять"),
        ("bewegen", "двигать"),
        ("beweisen", "доказывать"),
        ("bewerben", "подавать"),
        ("bewirken", "вызывать"),
        ("bewohnen", "жить"),
        ("bezahlen", "платить"),
        ("bezeichnen", "обозначать"),
        ("beziehen", "относить"),
        ("bezweifeln", "сомневаться"),
        ("biegen", "гнуть"),
        ("bieten", "предлагать"),
        ("binden", "связывать"),
        ("bitten", "просить"),
        ("blättern", "листать"),
        ("blasen", "дуть"),
        ("bleiben", "оставаться"),
        ("blenden", "ослеплять"),
        ("blicken", "смотреть"),
        ("blitzen", "сверкать"),
        ("blockieren", "блокировать"),
        ("blühen", "цвести"),
        ("bohren", "сверлить"),
        ("bombardieren", "бомбить"),
        ("borgen", "занимать"),
        ("boxen", "боксировать"),
        ("braten", "жарить"),
        ("brauchen", "нуждаться"),
        ("brechen", "ломать"),
        ("brennen", "гореть"),
        ("bringen", "приносить"),
        ("brüllen", "реветь"),
        ("buchstabieren", "писать"),
        ("bücken", "наклоняться"),
        ("buddeln", "копать"),
        ("büßen", "искупать"),
        ("bürgen", "гарантировать"),
        ("bürsten", "чистить"),
        
        # Прилагательные
        ("abenteuerlich", "приключенческий"),
        ("abhängig", "зависимый"),
        ("abstrakt", "абстрактный"),
        ("aktuell", "актуальный"),
        ("allgemein", "общий"),
        ("allein", "одинокий"),
        ("angenehm", "приятный"),
        ("ängstlich", "боязливый"),
        ("anstrengend", "утомительный"),
        ("angenehm", "приятный"),
        ("ärmlich", "бедный"),
        ("attraktiv", "привлекательный"),
        ("aufmerksam", "внимательный"),
        ("ausführlich", "подробный"),
        ("ausländisch", "иностранный"),
        ("ausreichend", "достаточный"),
        ("ausgezeichnet", "отличный"),
        ("äußerlich", "внешний"),
        ("automatisch", "автоматический"),
        ("begeistert", "восторженный"),
        ("bekannt", "известный"),
        ("beliebt", "популярный"),
        ("beruflich", "профессиональный"),
        ("beschäftigt", "занятый"),
        ("besonders", "особенный"),
        ("besser", "лучший"),
        ("beteiligt", "участвующий"),
        ("bewusst", "осознанный"),
        ("billig", "дешевый"),
        ("blond", "блондин"),
        ("blau", "синий"),
        ("breit", "широкий"),
        ("brillant", "блестящий"),
        ("brutto", "брутто"),
        ("buchstäblich", "буквальный"),
        ("bürgerlich", "гражданский"),
        ("charmant", "очаровательный"),
        ("chemisch", "химический"),
        ("christlich", "христианский"),
        ("chronisch", "хронический"),
        ("klassisch", "классический"),
        ("klar", "ясный"),
        ("klein", "маленький"),
        ("klug", "умный"),
        ("komisch", "странный"),
        ("komplett", "полный"),
        ("konkret", "конкретный"),
        ("kostenlos", "бесплатный"),
        ("krank", "больной"),
        ("kritisch", "критический"),
        ("kurz", "короткий"),
        ("kulturell", "культурный"),
        ("künftig", "будущий"),
        ("künstlich", "искусственный"),
        ("lang", "длинный"),
        ("langsam", "медленный"),
        ("laut", "громкий"),
        ("lebendig", "живой"),
        ("lediglich", "лишь"),
        ("leer", "пустой"),
        ("legal", "легальный"),
        ("leicht", "легкий"),
        ("leise", "тихий"),
        ("lernfähig", "способный"),
        ("letzt", "последний"),
        ("liberal", "либеральный"),
        ("lieb", "милый"),
        ("links", "левый"),
        ("literarisch", "литературный"),
        ("logisch", "логический"),
        ("lohnend", "выгодный"),
        ("loyal", "лояльный"),
        ("luftig", "воздушный"),
        ("lustig", "веселый"),
        ("mager", "худой"),
        ("männlich", "мужской"),
        ("materiell", "материальный"),
        ("medizinisch", "медицинский"),
        ("mehrfach", "многократный"),
        ("menschlich", "человеческий"),
        ("militärisch", "военный"),
        ("minimal", "минимальный"),
        ("modern", "современный"),
        ("möglich", "возможный"),
        ("monatlich", "ежемесячный"),
        ("müde", "усталый"),
        ("mündlich", "устный"),
        ("musikalisch", "музыкальный"),
        ("mütterlich", "материнский"),
        ("nachhaltig", "устойчивый"),
        ("naiv", "наивный"),
        ("natürlich", "естественный"),
        ("neben", "рядом"),
        ("negativ", "негативный"),
        ("neu", "новый"),
        ("neugierig", "любопытный"),
        ("niedlich", "милый"),
        ("nützlich", "полезный"),
        ("normal", "нормальный"),
        ("notwendig", "необходимый"),
        ("öffentlich", "общественный"),
        ("offen", "открытый"),
        ("optimistisch", "оптимистичный"),
        ("ordentlich", "опрятный"),
        ("organisch", "органический"),
        ("örtlich", "местный"),
        ("ökologisch", "экологический"),
        ("ökonomisch", "экономический"),
        ("paar", "пара"),
        ("parallel", "параллельный"),
        ("persönlich", "личный"),
        ("pfiffig", "сообразительный"),
        ("pflicht", "обязанный"),
        ("physisch", "физический"),
        ("politisch", "политический"),
        ("populär", "популярный"),
        ("positiv", "позитивный"),
        ("praktisch", "практичный"),
        ("präzise", "точный"),
        ("privat", "частный"),
        ("produktiv", "продуктивный"),
        ("professionell", "профессиональный"),
        ("psychisch", "психический"),
        ("publik", "публичный"),
        ("pünktlich", "пунктуальный"),
        ("qualifiziert", "квалифицированный"),
        ("quantitativ", "количественный"),
        ("radikal", "радикальный"),
        ("rational", "рациональный"),
        ("realistisch", "реалистичный"),
        ("rechtlich", "правовой"),
        ("regelmäßig", "регулярный"),
        ("reich", "богатый"),
        ("rein", "чистый"),
        ("relativ", "относительный"),
        ("relevant", "релевантный"),
        ("religiös", "религиозный"),
        ("romantisch", "романтичный"),
        ("rosa", "розовый"),
        ("rot", "красный"),
        ("ruhig", "спокойный"),
        ("rund", "круглый"),
        ("sauber", "чистый"),
        ("schlecht", "плохой"),
        ("schön", "красивый"),
        ("schwer", "тяжелый"),
        ("schnell", "быстрый"),
        ("schwarz", "черный"),
        ("sehr", "очень"),
        ("selbst", "сам"),
        ("selten", "редкий"),
        ("sensibel", "чувствительный"),
        ("sexuell", "сексуальный"),
        ("sicher", "безопасный"),
        ("sichtbar", "видимый"),
        ("sozial", "социальный"),
        ("spezifisch", "специфический"),
        ("spontan", "спонтанный"),
        ("stabil", "стабильный"),
        ("stark", "сильный"),
        ("stationär", "стационарный"),
        ("statistisch", "статистический"),
        ("stolz", "гордый"),
        ("streng", "строгий"),
        ("strukturiert", "структурированный"),
        ("subjektiv", "субъективный"),
        ("substantiell", "существенный"),
        ("symbolisch", "символический"),
        ("sympathisch", "приятный"),
        ("systematisch", "систематический"),
        ("taktisch", "тактический"),
        ("tatsächlich", "фактический"),
        ("technisch", "технический"),
        ("teuer", "дорогой"),
        ("theoretisch", "теоретический"),
        ("tief", "глубокий"),
        ("tolerant", "толерантный"),
        ("total", "полный"),
        ("traditionell", "традиционный"),
        ("traurig", "грустный"),
        ("treu", "верный"),
        ("trocken", "сухой"),
        ("typisch", "типичный"),
        ("überflüssig", "лишний"),
        ("überzeugt", "убежденный"),
        ("üblich", "обычный"),
        ("ungewöhnlich", "необычный"),
        ("unabhängig", "независимый"),
        ("unendlich", "бесконечный"),
        ("unerwartet", "неожиданный"),
        ("unglaublich", "невероятный"),
        ("unklar", "неясный"),
        ("unmöglich", "невозможный"),
        ("unruhig", "беспокойный"),
        ("unschuldig", "невинный"),
        ("unsicher", "неуверенный"),
        ("unterschiedlich", "различный"),
        ("unzufrieden", "недовольный"),
        ("verantwortlich", "ответственный"),
        ("verbindlich", "обязательный"),
        ("vereinbart", "договоренный"),
        ("verfügbar", "доступный"),
        ("vergnügt", "веселый"),
        ("verheiratet", "женатый"),
        ("verletzt", "раненый"),
        ("verlobt", "помолвленный"),
        ("verrückt", "сумасшедший"),
        ("verschieden", "разный"),
        ("verspätet", "опоздавший"),
        ("verstorben", "покойный"),
        ("vertraut", "знакомый"),
        ("verwandt", "родственный"),
        ("verzweifelt", "отчаянный"),
        ("voll", "полный"),
        ("vollständig", "полный"),
        ("vorbereitet", "подготовленный"),
        ("voraussichtlich", "предполагаемый"),
        ("vorhanden", "имеющийся"),
        ("vorläufig", "временный"),
        ("vornehm", "знатный"),
        ("vorsichtig", "осторожный"),
        ("vorteilhaft", "выгодный"),
        ("warm", "теплый"),
        ("wahr", "истинный"),
        ("wahrscheinlich", "вероятный"),
        ("wach", "бодрый"),
        ("wanderlustig", "странствующий"),
        ("weich", "мягкий"),
        ("weise", "мудрый"),
        ("weit", "далекий"),
        ("weiter", "дальнейший"),
        ("weltlich", "светский"),
        ("wenig", "малый"),
        ("wertvoll", "ценный"),
        ("wichtig", "важный"),
        ("wild", "дикий"),
        ("wirtschaftlich", "экономический"),
        ("wissenschaftlich", "научный"),
        ("witzig", "остроумный"),
        ("wöchentlich", "еженедельный"),
        ("wohnlich", "уютный"),
        ("wunderbar", "замечательный"),
        ("wütend", "разгневанный"),
        ("zahlreich", "многочисленный"),
        ("zart", "нежный"),
        ("zeitlich", "временный"),
        ("zielstrebig", "целеустремленный"),
        ("ziemlich", "довольный"),
        ("zufällig", "случайный"),
        ("zufrieden", "довольный"),
        ("zugänglich", "доступный"),
        ("zukünftig", "будущий"),
        ("zulässig", "допустимый"),
        ("zunehmend", "возрастающий"),
        ("zuständig", "ответственный"),
        ("zuverlässig", "надежный"),
        ("zweckmäßig", "целесообразный"),
        ("zweifelhaft", "сомнительный"),
        ("zwanglos", "непринужденный"),
        ("zwischen", "между"),
        ("zwölf", "двенадцать"),
    ],
    
    'B1': [
        # Существительные
        ("die Abhängigkeit", "зависимость"),
        ("die Ablehnung", "отказ"),
        ("die Abmachung", "договоренность"),
        ("die Abrechnung", "расчет"),
        ("die Absicht", "намерение"),
        ("die Abreise", "отъезд"),
        ("die Absage", "отказ"),
        ("die Abschlussprüfung", "выпускной экзамен"),
        ("die Abtei", "аббатство"),
        ("die Abteilung", "отдел"),
        ("die Abwechslung", "разнообразие"),
        ("die Abwesenheit", "отсутствие"),
        ("die Achsel", "плечо"),
        ("die Achtung", "уважение"),
        ("die Adresse", "адрес"),
        ("die Agentur", "агентство"),
        ("die Aggression", "агрессия"),
        ("die Ahnung", "предчувствие"),
        ("die Akademie", "академия"),
        ("die Akte", "дело"),
        ("die Aktion", "акция"),
        ("die Aktivität", "активность"),
        ("die Aktie", "акция"),
        ("die Aktualität", "актуальность"),
        ("die Akzeptanz", "принятие"),
        ("die Alarmierung", "тревога"),
        ("die Alkohol", "алкоголь"),
        ("die Allianz", "альянс"),
        ("die Allgemeinheit", "общественность"),
        ("die Allergie", "аллергия"),
        ("die Alternative", "альтернатива"),
        ("die Analyse", "анализ"),
        ("die Andeutung", "намек"),
        ("die Anerkennung", "признание"),
        ("die Änderung", "изменение"),
        ("die Anzeige", "объявление"),
        ("die Angelegenheit", "дело"),
        ("die Anpassung", "адаптация"),
        ("die Antwort", "ответ"),
        ("die Anweisung", "инструкция"),
        ("die Anzahl", "количество"),
        ("die Anmeldung", "регистрация"),
        ("die Anmerkung", "замечание"),
        ("die Anordnung", "распоряжение"),
        ("die Anreise", "приезд"),
        ("die Ansicht", "мнение"),
        ("die Anspannung", "напряжение"),
        ("die Anstellung", "работа"),
        ("die Anstrengung", "усилие"),
        ("die Antwort", "ответ"),
        ("die Anzeige", "объявление"),
        ("die Apotheke", "аптека"),
        ("die App", "приложение"),
        ("die Applikation", "аппликация"),
        ("die Anwendung", "применение"),
        ("die Arbeit", "работа"),
        ("die Arbeitslosigkeit", "безработица"),
        ("die Arbeitsstelle", "рабочее место"),
        ("die Arbeitszeit", "рабочее время"),
        ("die Architektur", "архитектура"),
        ("die Arena", "арена"),
        ("die Argumentation", "аргументация"),
        ("die Armut", "бедность"),
        ("die Armee", "армия"),
        ("die Aroma", "аромат"),
        ("die Arrangement", "расположение"),
        ("die Arrest", "арест"),
        ("die Artikel", "статья"),
        ("die Artist", "артист"),
        ("die Arznei", "лекарство"),
        ("die Asche", "пепел"),
        ("die Askese", "аскеза"),
        ("die Asphalt", "асфальт"),
        ("die Assimilation", "ассимиляция"),
        ("die Assoziation", "ассоциация"),
        ("die Astronomie", "астрономия"),
        ("die Atmosphäre", "атмосфера"),
        ("die Attacke", "атака"),
        ("die Aufmerksamkeit", "внимание"),
        ("die Aufführung", "представление"),
        ("die Aufgabe", "задача"),
        ("die Aufklärung", "просвещение"),
        ("die Auflage", "тираж"),
        ("die Auflösung", "разрешение"),
        ("die Aufmerksamkeit", "внимание"),
        ("die Aufnahme", "прием"),
        ("die Aufrichtigkeit", "искренность"),
        ("die Aufschrift", "надпись"),
        ("die Aussicht", "вид"),
        ("die Aufstellung", "список"),
        ("die Aufregung", "волнение"),
        ("die Ausbildung", "образование"),
        ("die Ausdehnung", "расширение"),
        ("die Auseinandersetzung", "разбор"),
        ("die Äußerung", "высказывание"),
        ("die Ausfahrt", "выезд"),
        ("die Ausfuhr", "экспорт"),
        ("die Ausgabe", "расход"),
        ("die Auskunft", "информация"),
        ("die Ausländer", "иностранец"),
        ("die Auslegung", "толкование"),
        ("die Auslieferung", "выдача"),
        ("die Ausrede", "отговорка"),
        ("die Aussage", "высказывание"),
        ("die Aussicht", "перспектива"),
        ("die Aussetzung", "прекращение"),
        ("die Ausstellung", "выставка"),
        ("die Aussteuer", "приданое"),
        ("die Ausübung", "осуществление"),
        ("die Auszahlung", "выплата"),
        ("die Ausnahme", "исключение"),
        ("die Auswertung", "оценка"),
        ("die Auswirkung", "последствие"),
        ("die Auszeichnung", "награда"),
        ("die Autorität", "авторитет"),
        ("die Autobahn", "автобан"),
        ("die Autonomie", "автономия"),
        ("die Avantgarde", "авангард"),
        ("die Avenue", "авеню"),
        ("die Axial", "осевой"),
        ("die Azubi", "ученик"),
        
        # Глаголы
        ("abbauen", "сокращать"),
        ("abdanken", "отказываться"),
        ("abdrucken", "печатать"),
        ("aberkennen", "отнимать"),
        ("abfertigen", "обслуживать"),
        ("abfragen", "спрашивать"),
        ("abgrenzen", "разграничивать"),
        ("abhaken", "отмечать"),
        ("abhängen", "зависеть"),
        ("abheben", "снимать"),
        ("abhören", "подслушивать"),
        ("abkühlen", "остывать"),
        ("abkürzen", "сокращать"),
        ("ablegen", "откладывать"),
        ("ablehnen", "отклонять"),
        ("ableiten", "выводить"),
        ("ablenken", "отвлекать"),
        ("abmelden", "выписываться"),
        ("abnehmen", "уменьшать"),
        ("abnutzen", "изнашивать"),
        ("abrechnen", "рассчитывать"),
        ("abreißen", "сносить"),
        ("abriegeln", "блокировать"),
        ("abrufen", "вызывать"),
        ("absagen", "отменять"),
        ("abschalten", "выключать"),
        ("abschätzen", "оценивать"),
        ("abscheiden", "выделять"),
        ("abschicken", "отправлять"),
        ("abschließen", "завершать"),
        ("abschneiden", "отрезать"),
        ("abschreiben", "списывать"),
        ("absichern", "обеспечивать"),
        ("absolvieren", "завершать"),
        ("absorbieren", "поглощать"),
        ("abspeichern", "сохранять"),
        ("abstimmen", "согласовывать"),
        ("abstoßen", "отталкивать"),
        ("abstürzen", "падать"),
        ("abstempeln", "штамповать"),
        ("abstellen", "ставить"),
        ("abstürzen", "падать"),
        ("abtasten", "ощупывать"),
        ("abtransportieren", "вывозить"),
        ("abtrocknen", "вытирать"),
        ("abtun", "отмахиваться"),
        ("abwägen", "взвешивать"),
        ("abwarten", "ждать"),
        ("abwehren", "отражать"),
        ("abweichen", "отклоняться"),
        ("abwenden", "отворачивать"),
        ("abwerfen", "сбрасывать"),
        ("abwesend", "отсутствующий"),
        ("abwischen", "вытирать"),
        ("abzählen", "считать"),
        ("abziehen", "вычитать"),
        ("abzielen", "нацеливать"),
        ("achseln", "пожимать"),
        ("achten", "уважать"),
        ("achten", "следить"),
        ("aktivieren", "активировать"),
        ("adaptieren", "адаптировать"),
        ("addieren", "складывать"),
        ("adressieren", "адресовать"),
        ("affirmativ", "утвердительный"),
        ("agieren", "действовать"),
        ("agitieren", "агитировать"),
        ("ähnlich", "похожий"),
        ("ahnen", "предчувствовать"),
        ("akzeptieren", "принимать"),
        ("alarmieren", "тревожить"),
        ("alienieren", "отчуждать"),
        ("alignieren", "выравнивать"),
        ("alimentieren", "содержать"),
        ("allgemein", "общий"),
        ("allokieren", "распределять"),
        ("amüsieren", "развлекать"),
        ("analysieren", "анализировать"),
        ("andauern", "продолжаться"),
        ("andeuten", "намекать"),
        ("andocken", "стыковать"),
        ("aneignen", "присваивать"),
        ("anerkennen", "признавать"),
        ("anfahren", "подъезжать"),
        ("anfangen", "начинать"),
        ("anfechten", "оспаривать"),
        ("anfertigen", "изготавливать"),
        ("anfragen", "спрашивать"),
        ("anfügen", "прилагать"),
        ("angeben", "указывать"),
        ("angehen", "касаться"),
        ("angewöhnen", "привыкать"),
        ("angleichen", "приравнивать"),
        ("angst", "бояться"),
        ("anhören", "слушать"),
        ("animieren", "анимировать"),
        ("anklicken", "нажимать"),
        ("ankommen", "прибывать"),
        ("ankündigen", "объявлять"),
        ("ankuppeln", "сцеплять"),
        ("anmelden", "регистрировать"),
        ("annehmen", "принимать"),
        ("anordnen", "распоряжаться"),
        ("anpassen", "приспосабливать"),
        ("anprobieren", "примерять"),
        ("anrechnen", "засчитывать"),
        ("anregen", "возбуждать"),
        ("anrichten", "причинять"),
        ("anrufen", "звонить"),
        ("anschaffen", "приобретать"),
        ("anschauen", "смотреть"),
        ("anscheinend", "видимо"),
        ("anschließen", "подключать"),
        ("anschreiben", "писать"),
        ("anschuldigen", "обвинять"),
        ("ansehen", "смотреть"),
        ("ansiedeln", "поселять"),
        ("anspannen", "напрягать"),
        ("ansprechen", "обращаться"),
        ("anstacheln", "подстегивать"),
        ("anstellen", "нанимать"),
        ("anstrengen", "напрягать"),
        ("antasten", "трогать"),
        ("antreffen", "встречать"),
        ("antreiben", "понукать"),
        ("antreten", "вступать"),
        ("antun", "причинять"),
        ("antworten", "отвечать"),
        ("anvertrauen", "доверять"),
        ("anwenden", "применять"),
        ("anwerben", "вербовать"),
        ("anwesend", "присутствующий"),
        ("anzapfen", "подключать"),
        ("anzeigen", "показывать"),
        ("anziehen", "одевать"),
        ("anzweifeln", "сомневаться"),
        ("apologize", "извиняться"),
        ("apparieren", "появляться"),
        ("applaudieren", "аплодировать"),
        ("applizieren", "применять"),
        ("approbieren", "одобрять"),
        ("arbeiten", "работать"),
        ("archivieren", "архивировать"),
        ("argumentieren", "аргументировать"),
        ("arrestieren", "арестовывать"),
        ("artikulieren", "артикулировать"),
        ("ascendieren", "подниматься"),
        ("assimilieren", "ассимилировать"),
        ("assoziieren", "ассоциировать"),
        ("astieren", "действовать"),
        ("atackieren", "атаковать"),
        ("atmen", "дышать"),
        ("attachieren", "прилагать"),
        ("attestieren", "удостоверять"),
        ("attrahieren", "привлекать"),
        ("auditieren", "аудировать"),
        ("augmentieren", "увеличивать"),
        ("ausbilden", "обучать"),
        ("ausbleiben", "отсутствовать"),
        ("ausbrüten", "высиживать"),
        ("ausdehnen", "расширять"),
        ("auseinander", "раздельно"),
        ("ausführen", "выполнять"),
        ("ausfüllen", "заполнять"),
        ("ausgehen", "выходить"),
        ("aushalten", "выдерживать"),
        ("aushandeln", "выговаривать"),
        ("ausharren", "терпеть"),
        ("ausholen", "размахиваться"),
        ("auskennen", "знать"),
        ("ausklammern", "исключать"),
        ("auskosten", "испытывать"),
        ("ausladen", "выгружать"),
        ("auslegen", "толковать"),
        ("ausliefern", "выдавать"),
        ("ausloten", "зондировать"),
        ("ausmachen", "выключать"),
        ("ausnutzen", "использовать"),
        ("ausprobieren", "пробовать"),
        ("ausreichen", "хватать"),
        ("ausrufen", "восклицать"),
        ("ausrüsten", "снаряжать"),
        ("aussagen", "заявлять"),
        ("ausschalten", "выключать"),
        ("ausschließen", "исключать"),
        ("ausschreiben", "выписывать"),
        ("aussortieren", "сортировать"),
        ("aussprechen", "произносить"),
        ("aussteigen", "выходить"),
        ("ausstellen", "выставлять"),
        ("austauschen", "обменивать"),
        ("austeilen", "раздавать"),
        ("austragen", "выносить"),
        ("austreten", "выходить"),
        ("ausüben", "осуществлять"),
        ("auswählen", "выбирать"),
        ("auswandern", "эмигрировать"),
        ("ausweichen", "избегать"),
        ("auswerten", "оценивать"),
        ("ausziehen", "снимать"),
        ("authentifizieren", "аутентифицировать"),
        ("automatisieren", "автоматизировать"),
        ("avancieren", "продвигаться"),
        ("axiomatisch", "аксиоматический"),
        ("backen", "печь"),
        ("badenden", "купаться"),
        ("bahnen", "прокладывать"),
        ("balance", "балансировать"),
        ("banalisieren", "банализировать"),
        ("bannen", "запрещать"),
        ("bar", "наличный"),
        ("barrikadieren", "баррикадировать"),
        ("basteln", "мастерить"),
        ("bauen", "строить"),
        ("baumeln", "болтаться"),
        ("beachten", "соблюдать"),
        ("beantragen", "заявлять"),
        ("beantworten", "отвечать"),
        ("bearbeiten", "обрабатывать"),
        ("beauftragen", "поручать"),
        ("beobachten", "наблюдать"),
        ("begeistern", "восхищать"),
        ("beginnen", "начинать"),
        ("begraben", "хоронить"),
        ("begründen", "обосновывать"),
        ("begrüßen", "приветствовать"),
        ("behalten", "сохранять"),
        ("behaupten", "утверждать"),
        ("behandeln", "лечить"),
        ("beherrschen", "владеть"),
        ("behalten", "держать"),
        ("behindern", "мешать"),
        ("beibringen", "обучать"),
        ("beichten", "исповедовать"),
        ("beifügen", "прилагать"),
        ("begeistern", "восторгать"),
        ("begleiten", "сопровождать"),
        ("begnügen", "довольствоваться"),
        ("begutachten", "оценивать"),
        ("beherbergen", "размещать"),
        ("behindern", "препятствовать"),
        ("bejahen", "подтверждать"),
        ("bekämpfen", "бороться"),
        ("bekannt", "известный"),
        ("bekommen", "получать"),
        ("belasten", "нагружать"),
        ("beleidigen", "оскорблять"),
        ("belegen", "занимать"),
        ("belehren", "поучать"),
        ("belieben", "нравиться"),
        ("bemerken", "замечать"),
        ("bemühen", "стараться"),
        ("benachrichtigen", "уведомлять"),
        ("benennen", "переименовывать"),
        ("benutzen", "использовать"),
        ("beobachten", "наблюдать"),
        ("beraten", "консультировать"),
        ("berechnen", "вычислять"),
        ("bereiten", "готовить"),
        ("berichten", "сообщать"),
        ("berücksichtigen", "учитывать"),
        ("berufen", "призывать"),
        ("berühren", "касаться"),
        ("beschädigen", "повреждать"),
        ("beschäftigen", "занимать"),
        ("beschließen", "решать"),
        ("beschreiben", "описывать"),
        ("beschützen", "защищать"),
        ("beschweren", "жаловаться"),
        ("beseitigen", "устранять"),
        ("besichtigen", "осматривать"),
        ("besitzen", "владеть"),
        ("besorgen", "доставать"),
        ("besprechen", "обсуждать"),
        ("besser", "лучше"),
        ("bestätigen", "подтверждать"),
        ("bestehen", "состоять"),
        ("bestellen", "заказывать"),
        ("bestimmen", "определять"),
        ("bestrafen", "наказывать"),
        ("besuchen", "посещать"),
        ("beteiligen", "участвовать"),
        ("betonen", "подчеркивать"),
        ("betragen", "составлять"),
        ("betreuen", "заботиться"),
        ("betreten", "входить"),
        ("betrügen", "обманывать"),
        ("beurteilen", "оценивать"),
        ("bevölkern", "населить"),
        ("bewahren", "сохранять"),
        ("bewegen", "двигать"),
        ("beweisen", "доказывать"),
        ("bewerben", "подавать"),
        ("bewirken", "вызывать"),
        ("bewohnen", "жить"),
        ("bezahlen", "платить"),
        ("bezeichnen", "обозначать"),
        ("beziehen", "относить"),
        ("bezweifeln", "сомневаться"),
        ("biegen", "гнуть"),
        ("bieten", "предлагать"),
        ("binden", "связывать"),
        ("bitten", "просить"),
        ("blättern", "листать"),
        ("blasen", "дуть"),
        ("bleiben", "оставаться"),
        ("blenden", "ослеплять"),
        ("blicken", "смотреть"),
        ("blitzen", "сверкать"),
        ("blockieren", "блокировать"),
        ("blühen", "цвести"),
        ("bohren", "сверлить"),
        ("bombardieren", "бомбить"),
        ("borgen", "занимать"),
        ("boxen", "боксировать"),
        ("braten", "жарить"),
        ("brauchen", "нуждаться"),
        ("brechen", "ломать"),
        ("brennen", "гореть"),
        ("bringen", "приносить"),
        ("brüllen", "реветь"),
        ("buchstabieren", "писать"),
        ("bücken", "наклоняться"),
        ("buddeln", "копать"),
        ("büßen", "искупать"),
        ("bürgen", "гарантировать"),
        ("bürsten", "чистить"),
        
        # Прилагательные
        ("abenteuerlich", "приключенческий"),
        ("abhängig", "зависимый"),
        ("abstrakt", "абстрактный"),
        ("aktuell", "актуальный"),
        ("allgemein", "общий"),
        ("allein", "одинокий"),
        ("angenehm", "приятный"),
        ("ängstlich", "боязливый"),
        ("anstrengend", "утомительный"),
        ("angenehm", "приятный"),
        ("ärmlich", "бедный"),
        ("attraktiv", "привлекательный"),
        ("aufmerksam", "внимательный"),
        ("ausführlich", "подробный"),
        ("ausländisch", "иностранный"),
        ("ausreichend", "достаточный"),
        ("ausgezeichnet", "отличный"),
        ("äußerlich", "внешний"),
        ("automatisch", "автоматический"),
        ("begeistert", "восторженный"),
        ("bekannt", "известный"),
        ("beliebt", "популярный"),
        ("beruflich", "профессиональный"),
        ("beschäftigt", "занятый"),
        ("besonders", "особенный"),
        ("besser", "лучший"),
        ("beteiligt", "участвующий"),
        ("bewusst", "осознанный"),
        ("billig", "дешевый"),
        ("blond", "блондин"),
        ("blau", "синий"),
        ("breit", "широкий"),
        ("brillant", "блестящий"),
        ("brutto", "брутто"),
        ("buchstäblich", "буквальный"),
        ("bürgerlich", "гражданский"),
        ("charmant", "очаровательный"),
        ("chemisch", "химический"),
        ("christlich", "христианский"),
        ("chronisch", "хронический"),
        ("klassisch", "классический"),
        ("klar", "ясный"),
        ("klein", "маленький"),
        ("klug", "умный"),
        ("komisch", "странный"),
        ("komplett", "полный"),
        ("konkret", "конкретный"),
        ("kostenlos", "бесплатный"),
        ("krank", "больной"),
        ("kritisch", "критический"),
        ("kurz", "короткий"),
        ("kulturell", "культурный"),
        ("künftig", "будущий"),
        ("künstlich", "искусственный"),
        ("lang", "длинный"),
        ("langsam", "медленный"),
        ("laut", "громкий"),
        ("lebendig", "живой"),
        ("lediglich", "лишь"),
        ("leer", "пустой"),
        ("legal", "легальный"),
        ("leicht", "легкий"),
        ("leise", "тихий"),
        ("lernfähig", "способный"),
        ("letzt", "последний"),
        ("liberal", "либеральный"),
        ("lieb", "милый"),
        ("links", "левый"),
        ("literarisch", "литературный"),
        ("logisch", "логический"),
        ("lohnend", "выгодный"),
        ("loyal", "лояльный"),
        ("luftig", "воздушный"),
        ("lustig", "веселый"),
        ("mager", "худой"),
        ("männlich", "мужской"),
        ("materiell", "материальный"),
        ("medizinisch", "медицинский"),
        ("mehrfach", "многократный"),
        ("menschlich", "человеческий"),
        ("militärisch", "военный"),
        ("minimal", "минимальный"),
        ("modern", "современный"),
        ("möglich", "возможный"),
        ("monatlich", "ежемесячный"),
        ("müde", "усталый"),
        ("mündlich", "устный"),
        ("musikalisch", "музыкальный"),
        ("mütterlich", "материнский"),
        ("nachhaltig", "устойчивый"),
        ("naiv", "наивный"),
        ("natürlich", "естественный"),
        ("neben", "рядом"),
        ("negativ", "негативный"),
        ("neu", "новый"),
        ("neugierig", "любопытный"),
        ("niedlich", "милый"),
        ("nützlich", "полезный"),
        ("normal", "нормальный"),
        ("notwendig", "необходимый"),
        ("öffentlich", "общественный"),
        ("offen", "открытый"),
        ("optimistisch", "оптимистичный"),
        ("ordentlich", "опрятный"),
        ("organisch", "органический"),
        ("örtlich", "местный"),
        ("ökologisch", "экологический"),
        ("ökonomisch", "экономический"),
        ("paar", "пара"),
        ("parallel", "параллельный"),
        ("persönlich", "личный"),
        ("pfiffig", "сообразительный"),
        ("pflicht", "обязанный"),
        ("physisch", "физический"),
        ("politisch", "политический"),
        ("populär", "популярный"),
        ("positiv", "позитивный"),
        ("praktisch", "практичный"),
        ("präzise", "точный"),
        ("privat", "частный"),
        ("produktiv", "продуктивный"),
        ("professionell", "профессиональный"),
        ("psychisch", "психический"),
        ("publik", "публичный"),
        ("pünktlich", "пунктуальный"),
        ("qualifiziert", "квалифицированный"),
        ("quantitativ", "количественный"),
        ("radikal", "радикальный"),
        ("rational", "рациональный"),
        ("realistisch", "реалистичный"),
        ("rechtlich", "правовой"),
        ("regelmäßig", "регулярный"),
        ("reich", "богатый"),
        ("rein", "чистый"),
        ("relativ", "относительный"),
        ("relevant", "релевантный"),
        ("religiös", "религиозный"),
        ("romantisch", "романтичный"),
        ("rosa", "розовый"),
        ("rot", "красный"),
        ("ruhig", "спокойный"),
        ("rund", "круглый"),
        ("sauber", "чистый"),
        ("schlecht", "плохой"),
        ("schön", "красивый"),
        ("schwer", "тяжелый"),
        ("schnell", "быстрый"),
        ("schwarz", "черный"),
        ("sehr", "очень"),
        ("selbst", "сам"),
        ("selten", "редкий"),
        ("sensibel", "чувствительный"),
        ("sexuell", "сексуальный"),
        ("sicher", "безопасный"),
        ("sichtbar", "видимый"),
        ("sozial", "социальный"),
        ("spezifisch", "специфический"),
        ("spontan", "спонтанный"),
        ("stabil", "стабильный"),
        ("stark", "сильный"),
        ("stationär", "стационарный"),
        ("statistisch", "статистический"),
        ("stolz", "гордый"),
        ("streng", "строгий"),
        ("strukturiert", "структурированный"),
        ("subjektiv", "субъективный"),
        ("substantiell", "существенный"),
        ("symbolisch", "символический"),
        ("sympathisch", "приятный"),
        ("systematisch", "систематический"),
        ("taktisch", "тактический"),
        ("tatsächlich", "фактический"),
        ("technisch", "технический"),
        ("teuer", "дорогой"),
        ("theoretisch", "теоретический"),
        ("tief", "глубокий"),
        ("tolerant", "толерантный"),
        ("total", "полный"),
        ("traditionell", "традиционный"),
        ("traurig", "грустный"),
        ("treu", "верный"),
        ("trocken", "сухой"),
        ("typisch", "типичный"),
        ("überflüssig", "лишний"),
        ("überzeugt", "убежденный"),
        ("üblich", "обычный"),
        ("ungewöhnlich", "необычный"),
        ("unabhängig", "независимый"),
        ("unendlich", "бесконечный"),
        ("unerwartet", "неожиданный"),
        ("unglaublich", "невероятный"),
        ("unklar", "неясный"),
        ("unmöglich", "невозможный"),
        ("unruhig", "беспокойный"),
        ("unschuldig", "невинный"),
        ("unsicher", "неуверенный"),
        ("unterschiedlich", "различный"),
        ("unzufrieden", "недовольный"),
        ("verantwortlich", "ответственный"),
        ("verbindlich", "обязательный"),
        ("vereinbart", "договоренный"),
        ("verfügbar", "доступный"),
        ("vergnügt", "веселый"),
        ("verheiratet", "женатый"),
        ("verletzt", "раненый"),
        ("verlobt", "помолвленный"),
        ("verrückt", "сумасшедший"),
        ("verschieden", "разный"),
        ("verspätet", "опоздавший"),
        ("verstorben", "покойный"),
        ("vertraut", "знакомый"),
        ("verwandt", "родственный"),
        ("verzweifelt", "отчаянный"),
        ("voll", "полный"),
        ("vollständig", "полный"),
        ("vorbereitet", "подготовленный"),
        ("voraussichtlich", "предполагаемый"),
        ("vorhanden", "имеющийся"),
        ("vorläufig", "временный"),
        ("vornehm", "знатный"),
        ("vorsichtig", "осторожный"),
        ("vorteilhaft", "выгодный"),
        ("warm", "теплый"),
        ("wahr", "истинный"),
        ("wahrscheinlich", "вероятный"),
        ("wach", "бодрый"),
        ("wanderlustig", "странствующий"),
        ("weich", "мягкий"),
        ("weise", "мудрый"),
        ("weit", "далекий"),
        ("weiter", "дальнейший"),
        ("weltlich", "светский"),
        ("wenig", "малый"),
        ("wertvoll", "ценный"),
        ("wichtig", "важный"),
        ("wild", "дикий"),
        ("wirtschaftlich", "экономический"),
        ("wissenschaftlich", "научный"),
        ("witzig", "остроумный"),
        ("wöchentlich", "еженедельный"),
        ("wohnlich", "уютный"),
        ("wunderbar", "замечательный"),
        ("wütend", "разгневанный"),
        ("zahlreich", "многочисленный"),
        ("zart", "нежный"),
        ("zeitlich", "временный"),
        ("zielstrebig", "целеустремленный"),
        ("ziemlich", "довольный"),
        ("zufällig", "случайный"),
        ("zufrieden", "довольный"),
        ("zugänglich", "доступный"),
        ("zukünftig", "будущий"),
        ("zulässig", "допустимый"),
        ("zunehmend", "возрастающий"),
        ("zuständig", "ответственный"),
        ("zuverlässig", "надежный"),
        ("zweckmäßig", "целесообразный"),
        ("zweifelhaft", "сомнительный"),
        ("zwanglos", "непринужденный"),
        ("zwischen", "между"),
        ("zwölf", "двенадцать"),
    ],
    
    'B2': [],  # Пусто ��ля начала
    'C1': [],  # Пусто для начала
}

print("🔍 Проверка и добавление слов Goethe Institut...\n")

total_added = 0
total_existing = 0

for level, words in GOETHE_WORDS.items():
    if not words:
        print(f"⏭️  Уровень {level} пропущен (пустой список)")
        continue
    
    print(f"\n📚 Уровень {level}: {len(words)} слов")
    
    added_count = 0
    existing_count = 0
    
    for de, ru in words:
        # Определяем артикль
        article = None
        if de.startswith("der "):
            article = "der"
            de = de[4:]
        elif de.startswith("die "):
            article = "die"
            de = de[4:]
        elif de.startswith("das "):
            article = "das"
            de = de[4:]
        
        # Проверяем есть ли слово в базе
        cur.execute("""
            SELECT id FROM words 
            WHERE de ILIKE %s AND ru ILIKE %s AND level = %s
        """, (de, ru, level))
        
        if cur.fetchone():
            existing_count += 1
        else:
            # Добавляем слово
            try:
                cur.execute("""
                    INSERT INTO words (de, ru, article, level, topic, verb_forms)
                    VALUES (%s, %s, %s, %s, 'Goethe Institut', NULL)
                """, (de, ru, article, level))
                added_count += 1
            except Exception as e:
                if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                    existing_count += 1
                else:
                    print(f"❌ Ошибка: {e}")
                    conn.rollback()
    
    conn.commit()
    print(f"   ✅ Добавлено: {added_count}")
    print(f"   ✅ Уже есть: {existing_count}")
    
    total_added += added_count
    total_existing += existing_count

print(f"\n📊 Итоги:")
print(f"   Добавлено: {total_added}")
print(f"   Уже было: {total_existing}")
print(f"   Всего проверено: {total_added + total_existing}")

cur.close()
conn.close()
