#!/usr/bin/env python3
"""
Проверить слова A1 из Goethe Institut и добавить отсутствующие
"""

import os, sys, io
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env.local'))

import psycopg2

conn = psycopg2.connect(os.environ.get("POSTGRES_URL"))
cur = conn.cursor()

# Слова A1 из Goethe Institut (полный список)
GOETHE_A1_WORDS = [
    # Существительные
    ("der Abschied", "прощание"),
    ("die Adresse", "адрес"),
    ("der Alltag", "повседневность"),
    ("das Angebot", "предложение"),
    ("die Angst", "страх"),
    ("die Antwort", "ответ"),
    ("der Apfel", "яблоко"),
    ("die Arbeit", "работа"),
    ("der Arzt", "врач"),
    ("der Atem", "дыхание"),
    ("die Auskunft", "информация"),
    ("das Ausland", "зарубежье"),
    ("die Aussage", "высказывание"),
    ("der Ausdruck", "выражение"),
    ("die Ausbildung", "образование"),
    ("die Aufgabe", "задание"),
    ("der Aufenthalt", "пребывание"),
    ("die Aufführung", "представление"),
    ("die Aufgabe", "задача"),
    ("der August", "август"),
    ("die Ausbildung", "обучение"),
    ("der Ausgang", "выход"),
    ("die Ausstellung", "выставка"),
    ("die Ausnahme", "исключение"),
    ("der Ausdruck", "выражение"),
    ("die Art", "вид, способ"),
    ("die Apotheke", "аптека"),
    ("das Auto", "автомобиль"),
    ("der Bahnhof", "вокзал"),
    ("die Bahn", "поезд, путь"),
    ("das Bank", "банк"),
    ("der Baum", "дерево"),
    ("die Bedienung", "обслуживание"),
    ("der Bedarf", "потребность"),
    ("das Bein", "нога"),
    ("der Beruf", "профессия"),
    ("die Besetzung", "занятие"),
    ("der Besuch", "визит"),
    ("das Bett", "кровать"),
    ("das Bild", "картина"),
    ("die Blume", "цветок"),
    ("das Blatt", "лист"),
    ("der Brief", "письмо"),
    ("die Brille", "очки"),
    ("das Brot", "хлеб"),
    ("die Butter", "масло"),
    ("das Buch", "книга"),
    ("das Büro", "офис"),
    ("der Bus", "автобус"),
    ("das Café", "кафе"),
    ("die CD", "диск"),
    ("das Centrum", "центр"),
    ("der Computer", "компьютер"),
    ("die Creme", "крем"),
    ("das Dach", "крыша"),
    ("der Dank", "благодарность"),
    ("der Darm", "кишка"),
    ("der Dezember", "декабрь"),
    ("der Deckel", "крышка"),
    ("der Dienst", "служба"),
    ("der Dienstag", "вторник"),
    ("der Dollar", "доллар"),
    ("der Dom", "собор"),
    ("der Donner", "гром"),
    ("der Donnerstag", "четверг"),
    ("die Dose", "банка"),
    ("die Dusche", "душ"),
    ("das Dorf", "деревня"),
    ("die Drogerie", "драгstore"),
    ("der Durst", "жажда"),
    ("die Ecke", "угол"),
    ("die Ehe", "брак"),
    ("die Eile", "спешка"),
    ("die Eisenbahn", "железная дорога"),
    ("das Eis", "лед, мороженое"),
    ("das Ende", "конец"),
    ("die Entschuldigung", "извинение"),
    ("der Erfolg", "успех"),
    ("die Erfahrung", "опыт"),
    ("das Essen", "еда"),
    ("der Euro", "евро"),
    ("die Fabrik", "фабрика"),
    ("das Fach", "предмет"),
    ("die Fahrt", "поездка"),
    ("das Fall", "случай"),
    ("der Fehler", "ошибка"),
    ("das Fest", "праздник"),
    ("das Fett", "жир"),
    ("das Feuer", "огонь"),
    ("der Film", "фильм"),
    ("der Finger", "палец"),
    ("die Firma", "фирма"),
    ("der Fisch", "рыба"),
    ("die Flasche", "бутылка"),
    ("das Fleisch", "мясо"),
    ("die Frage", "вопрос"),
    ("der Freund", "друг"),
    ("die Freundin", "подруга"),
    ("der Frieden", "мир"),
    ("der Freitag", "пятница"),
    ("die Frucht", "фрукт"),
    ("der Fuß", "нога"),
    ("der Garten", "сад"),
    ("das Gebäude", "здание"),
    ("der Gedanke", "мысль"),
    ("das Gefühl", "чувство"),
    ("das Geld", "деньги"),
    ("das Gemüse", "овощи"),
    ("das Gericht", "блюдо"),
    ("das Geschenk", "подарок"),
    ("das Gesicht", "лицо"),
    ("das Gesetz", "закон"),
    ("die Gesundheit", "здоровье"),
    ("das Gewicht", "вес"),
    ("das Glas", "стакан"),
    ("das Glück", "счастье"),
    ("das Gold", "золото"),
    ("das Gras", "трава"),
    ("die Grenze", "граница"),
    ("die Gruppe", "группа"),
    ("der Gruß", "приветствие"),
    ("der Gürtel", "ремень"),
    ("der Haar", "волос"),
    ("der Hafen", "гавань"),
    ("der Hahn", "петух"),
    ("die Hand", "рука"),
    ("der Handschuh", "перчатка"),
    ("der Hut", "шляпа"),
    ("die Haut", "кожа"),
    ("das Haus", "дом"),
    ("die Heizung", "отопление"),
    ("das Hemd", "рубашка"),
    ("der Herr", "господин"),
    ("das Herz", "сердце"),
    ("die Hilfe", "помощь"),
    ("die Himbeere", "малина"),
    ("der Himmel", "небо"),
    ("der Hund", "собака"),
    ("die Hose", "брюки"),
    ("das Hotel", "отель"),
    ("der Hunger", "голод"),
    ("die Jacke", "куртка"),
    ("die Jacke", "пиджак"),
    ("der Januar", "январь"),
    ("die Jacke", "жилет"),
    ("der Juli", "июль"),
    ("der Juni", "июнь"),
    ("die Jacke", "свитер"),
    ("der Kaffee", "кофе"),
    ("der Kaffee", "кофе"),
    ("der Kamm", "гребень"),
    ("die Karte", "карта"),
    ("der Käse", "сыр"),
    ("der Koffer", "чемодан"),
    ("die Kohle", "уголь"),
    ("der Kollege", "коллега"),
    ("die Kollegin", "коллега"),
    ("die Kommode", "комод"),
    ("die Kopie", "копия"),
    ("der Kopf", "голова"),
    ("die Kartoffel", "картофель"),
    ("der Käfig", "клетка"),
    ("der Kuchen", "пирог"),
    ("die Küche", "кухня"),
    ("der Kühlschrank", "холодильник"),
    ("der Kult", "культ"),
    ("die Kultur", "культура"),
    ("der Kunde", "клиент"),
    ("die Kundin", "клиентка"),
    ("die Kunst", "искусство"),
    ("das Labor", "лаборатория"),
    ("die Lampe", "лампа"),
    ("das Land", "страна"),
    ("die Langeweile", "скука"),
    ("die Laune", "настроение"),
    ("der Laut", "звук"),
    ("das Leder", "кожа"),
    ("die Lehre", "обучение"),
    ("der Lehrer", "учитель"),
    ("die Lehrerin", "учительница"),
    ("das Licht", "свет"),
    ("das Lied", "песня"),
    ("die Linie", "линия"),
    ("die Literatur", "литература"),
    ("der Löffel", "ложка"),
    ("der Lohn", "зарплата"),
    ("die Luft", "воздух"),
    ("der Lärm", "шум"),
    ("das Mädchen", "девушка"),
    ("der Magen", "желудок"),
    ("der Mai", "май"),
    ("der Mann", "мужчина"),
    ("der Mantel", "пальто"),
    ("die Mappe", "папка"),
    ("der Markt", "рынок"),
    ("die Maschine", "машина"),
    ("die Mauer", "стена"),
    ("der Mechaniker", "механик"),
    ("das Medikament", "лекарство"),
    ("die Mehl", "мука"),
    ("das Meer", "море"),
    ("das Messer", "нож"),
    ("die Milch", "молоко"),
    ("der Millionär", "миллионер"),
    ("die Minute", "минута"),
    ("die Mode", "мода"),
    ("der Mond", "луна"),
    ("der Morgen", "утро"),
    ("die Mütze", "шапка"),
    ("der Mund", "рот"),
    ("die Musik", "музыка"),
    ("der Muskel", "мышца"),
    ("die Mutter", "мать"),
    ("die Nacht", "ночь"),
    ("der Nagel", "гвоздь"),
    ("die Nase", "нос"),
    ("der Natur", "природа"),
    ("der Nebel", "туман"),
    ("der Neid", "зависть"),
    ("der November", "ноябрь"),
    ("die Nummer", "номер"),
    ("der Oktober", "октябрь"),
    ("der Ofen", "печь"),
    ("das Obst", "фрукты"),
    ("der Ozean", "океан"),
    ("das Paket", "посылка"),
    ("die Panne", "поломка"),
    ("das Papier", "бумага"),
    ("der Park", "парк"),
    ("der Partner", "партнер"),
    ("die Partnerin", "партнерша"),
    ("die Pause", "пауза"),
    ("die Pension", "пансион"),
    ("die Person", "личность"),
    ("die Pflanze", "растение"),
    ("die Pfeife", "трубка"),
    ("das Pfund", "фунт"),
    ("die Polizei", "полиция"),
    ("der Polizist", "полицейский"),
    ("die Polizistin", "полицейская"),
    ("der Post", "почта"),
    ("die Post", "почта"),
    ("der Preis", "цена"),
    ("die Prüfung", "экзамен"),
    ("das Produkt", "продукт"),
    ("der Professor", "профессор"),
    ("das Programm", "программа"),
    ("der Prospekt", "проспект"),
    ("der Pullover", "пуловер"),
    ("die Pumpe", "насос"),
    ("der Punkt", "точка"),
    ("der Pulli", "пуловер"),
    ("die Quittung", "квитанция"),
    ("der Rad", "колесо"),
    ("der Radio", "радио"),
    ("der Rain", "дождь"),
    ("der Rand", "край"),
    ("der Rat", "совет"),
    ("die Ratte", "крыса"),
    ("der Rauch", "дым"),
    ("die Rechnung", "счет"),
    ("das Recht", "право"),
    ("die Rede", "речь"),
    ("die Reise", "путешествие"),
    ("das Reis", "рис"),
    ("die Reklame", "реклама"),
    ("das Restaurant", "ресторан"),
    ("das Resultat", "результат"),
    ("der Ring", "кольцо"),
    ("die Rock", "юбка"),
    ("der Roller", "скутер"),
    ("die Rose", "роза"),
    ("der Rücken", "спина"),
    ("der Saal", "зал"),
    ("der Saft", "сок"),
    ("der Salz", "соль"),
    ("der Samstag", "суббота"),
    ("der Schaf", "овца"),
    ("der Schal", "шарф"),
    ("der Schatten", "тень"),
    ("der Schauspieler", "актер"),
    ("der Schauspielerin", "актриса"),
    ("der Schere", "ножницы"),
    ("der Schiff", "корабль"),
    ("der Schild", "вывеска"),
    ("der Schinken", "ветчина"),
    ("der Schlaf", "сон"),
    ("der Schlange", "змея"),
    ("der Schluss", "конец"),
    ("der Schlüssel", "ключ"),
    ("der Schmuck", "украшение"),
    ("der Schnee", "снег"),
    ("der Schneider", "портной"),
    ("die Schule", "школа"),
    ("der Schüler", "ученик"),
    ("die Schülerin", "ученица"),
    ("der Schuh", "ботинок"),
    ("der Schrank", "шкаф"),
    ("der Schreck", "испуг"),
    ("der Schritt", "шаг"),
    ("der Schuh", "туфля"),
    ("die Schulter", "плечо"),
    ("die Schüssel", "миска"),
    ("die Schwester", "сестра"),
    ("der Schwamm", "губка"),
    ("der Schwan", "лебедь"),
    ("der Schwarz", "черный"),
    ("der Schwein", "свинья"),
    ("der Schwert", "меч"),
    ("der See", "озеро"),
    ("die Seife", "мыло"),
    ("die Sekunde", "секунда"),
    ("der September", "сентябрь"),
    ("die Sessel", "кресло"),
    ("das Silber", "серебро"),
    ("die Sonne", "солнце"),
    ("der Sommer", "лето"),
    ("der Sonntag", "воскресенье"),
    ("die Sorge", "забота"),
    ("der Spaß", "удовольствие"),
    ("die Speise", "блюдо"),
    ("der Spiegel", "зеркало"),
    ("das Spiel", "игра"),
    ("die Spinne", "паук"),
    ("die Sport", "спорт"),
    ("die Sprache", "язык"),
    ("die Stadt", "город"),
    ("der Stahl", "сталь"),
    ("der Stall", "стойло"),
    ("die Station", "станция"),
    ("der Staub", "пыль"),
    ("der Stecker", "вилка"),
    ("die Stelle", "место"),
    ("der Stiefel", "сапог"),
    ("der Stil", "стиль"),
    ("die Stimme", "голос"),
    ("der Stock", "палка"),
    ("der Stoff", "ткань"),
    ("der Stolz", "гордость"),
    ("der Storch", "аист"),
    ("der Strand", "пляж"),
    ("die Straße", "улица"),
    ("der Strom", "ток"),
    ("der Stuhl", "стул"),
    ("die Stunde", "час"),
    ("der Sturm", "шторм"),
    ("der Sturz", "падение"),
    ("der Sucht", "зависимость"),
    ("der Süd", "юг"),
    ("der Tabak", "табак"),
    ("die Tabelle", "таблица"),
    ("die Tafel", "доска"),
    ("die Tasche", "сумка"),
    ("die Tasse", "чашка"),
    ("die Taube", "голубь"),
    ("der Tee", "чай"),
    ("der Teller", "тарелка"),
    ("der Teppich", "ковер"),
    ("der Termin", "срок"),
    ("der Teufel", "дьявол"),
    ("der Text", "текст"),
    ("die Tiefe", "глубина"),
    ("der Tisch", "стол"),
    ("die Tochter", "дочь"),
    ("der Tod", "смерть"),
    ("der Topf", "горшок"),
    ("die Torte", "торт"),
    ("die Tour", "тур"),
    ("die Treppe", "лестница"),
    ("der Traum", "мечта"),
    ("der Trinken", "напиток"),
    ("der Tropfen", "капля"),
    ("der Truthahn", "индейка"),
    ("der Tuch", "платок"),
    ("die Tür", "дверь"),
    ("der Übung", "упражнение"),
    ("die Uhr", "часы"),
    ("die Universität", "университет"),
    ("der Urlaub", "отпуск"),
    ("der Vater", "отец"),
    ("der Vogel", "птица"),
    ("der Vorhang", "занавес"),
    ("der Vormittag", "перед полуднем"),
    ("der Vorteil", "преимущество"),
    ("der Wald", "лес"),
    ("die Wand", "стена"),
    ("die Wangen", "щеки"),
    ("die Ware", "товар"),
    ("die Wärme", "тепло"),
    ("die Wäsche", "белье"),
    ("die Wasser", "вода"),
    ("die Wege", "пути"),
    ("der Wein", "вино"),
    ("die Wiese", "луг"),
    ("der Wind", "ветер"),
    ("der Winter", "зима"),
    ("die Woche", "неделя"),
    ("die Wohnung", "квартира"),
    ("der Wolf", "волк"),
    ("die Wolke", "облако"),
    ("das Wort", "слово"),
    ("die Wurst", "колбаса"),
    ("die Wurzel", "корень"),
    ("die Zahl", "число"),
    ("der Zahn", "зуб"),
    ("der Zaun", "забор"),
    ("das Zeug", "вещь"),
    ("das Zimmer", "комната"),
    ("der Zucker", "сахар"),
    ("der Zug", "поезд"),
    ("die Zukunft", "будущее"),
    ("die Zwiebel", "лук"),
    
    # Глаголы
    ("antworten", "отвечать"),
    ("arbeiten", "работать"),
    ("atmen", "дышать"),
    ("backen", "печь"),
    ("baden", "купаться"),
    ("bauen", "строить"),
    ("bedanken", "благодарить"),
    ("beginnen", "начинать"),
    ("bekommen", "получать"),
    ("besuchen", "посещать"),
    ("bezahlen", "платить"),
    ("bitten", "просить"),
    ("bleiben", "оставаться"),
    ("brauchen", "нуждаться"),
    ("bringen", "приносить"),
    ("buchstaben", "писать"),
    ("danken", "благодарить"),
    ("denken", "думать"),
    ("diskutieren", "обсуждать"),
    ("dienen", "служить"),
    ("drucken", "печатать"),
    ("drücken", "давить"),
    ("dürfen", "мочь"),
    ("eilen", "спешить"),
    ("einkaufen", "покупать"),
    ("einladen", "приглашать"),
    ("einsteigen", "садиться"),
    ("empfehlen", "рекомендовать"),
    ("enden", "заканчивать"),
    ("entschuldigen", "извинять"),
    ("erfahren", "узнавать"),
    ("erhalten", "получать"),
    ("erinnern", "помнить"),
    ("erklären", "объяснять"),
    ("erlauben", "разрешать"),
    ("erreichen", "достигать"),
    ("erzählen", "рассказывать"),
    ("essen", "есть"),
    ("fahren", "ехать"),
    ("fallen", "падать"),
    ("fehlen", "отсутствовать"),
    ("feiern", "праздновать"),
    ("finden", "находить"),
    ("fischen", "ловить рыбу"),
    ("fliegen", "лететь"),
    ("fragen", "спрашивать"),
    ("freuen", "радоваться"),
    ("frühstücken", "завтракать"),
    ("fühlen", "чувствовать"),
    ("geben", "давать"),
    ("gehen", "идти"),
    ("gehören", "принадлежать"),
    ("gelingen", "удаваться"),
    ("genießen", "наслаждаться"),
    ("glauben", "верить"),
    ("gratulieren", "поздравлять"),
    ("greifen", "хватать"),
    ("grüßen", "приветствовать"),
    ("haben", "иметь"),
    ("halten", "держать"),
    ("hängen", "висеть"),
    ("heiraten", "жениться"),
    ("heißen", "называться"),
    ("helfen", "помогать"),
    ("holen", "брать"),
    ("hören", "слышать"),
    ("hoffen", "надеяться"),
    ("kaufen", "покупать"),
    ("kennen", "знать"),
    ("kommen", "приходить"),
    ("können", "мочь"),
    ("kochen", "готовить"),
    ("kosten", "стоить"),
    ("kriegen", "получать"),
    ("lachen", "смеяться"),
    ("laden", "загружать"),
    ("lassen", "оставлять"),
    ("laufen", "бежать"),
    ("leben", "жить"),
    ("legen", "класть"),
    ("lehren", "учить"),
    ("lernen", "учиться"),
    ("lesen", "читать"),
    ("lieben", "любить"),
    ("liegen", "лежать"),
    ("loben", "хвалить"),
    ("lügen", "лгать"),
    ("machen", "делать"),
    ("malen", "рисовать"),
    ("meinen", "считать"),
    ("mieten", "снимать"),
    ("mitbringen", "приносить"),
    ("mitkommen", "приходить"),
    ("mitmachen", "участвовать"),
    ("mitnehmen", "брать"),
    ("müssen", "должен"),
    ("nennen", "называть"),
    ("nehmen", "брать"),
    ("notieren", "записывать"),
    ("öffnen", "открывать"),
    ("ordnen", "сортировать"),
    ("packen", "упаковывать"),
    ("passieren", "случаться"),
    ("planen", "планировать"),
    ("probieren", "пробовать"),
    ("putzen", "чистить"),
    ("rauchen", "курить"),
    ("rechnen", "считать"),
    ("reden", "говорить"),
    ("regnen", "идти дождь"),
    ("reisen", "путешествовать"),
    ("reiten", "кататься"),
    ("rennen", "бежать"),
    ("reparieren", "ремонтировать"),
    ("riechen", "нюхать"),
    ("rufen", "звать"),
    ("sagen", "говорить"),
    ("salzen", "солить"),
    ("sammeln", "собирать"),
    ("saugen", "сосать"),
    ("schaffen", "создавать"),
    ("schlafen", "спать"),
    ("schlagen", "бить"),
    ("schmecken", "вкусить"),
    ("schneiden", "резать"),
    ("schreiben", "писать"),
    ("schreien", "кричать"),
    ("schützen", "защищать"),
    ("schütteln", "трясти"),
    ("schwimmen", "плавать"),
    ("sehen", "видеть"),
    ("sein", "быть"),
    ("singen", "петь"),
    ("sitzen", "сидеть"),
    ("sollen", "должен"),
    ("spielen", "играть"),
    ("sprechen", "говорить"),
    ("springen", "прыгать"),
    ("stehen", "стоять"),
    ("steigen", "подниматься"),
    ("stellen", "ставить"),
    ("sterben", "умирать"),
    ("stimmen", "соглашаться"),
    ("stören", "мешать"),
    ("streiten", "ссориться"),
    ("studieren", "учиться"),
    ("suchen", "искать"),
    ("tanzen", "танцевать"),
    ("tauchen", "нырять"),
    ("teilen", "делить"),
    ("telefonieren", "звонить"),
    ("tragen", "нести"),
    ("trainieren", "тренировать"),
    ("träumen", "мечтать"),
    ("treffen", "встречать"),
    ("treiben", "гнать"),
    ("trinken", "пить"),
    ("trocknen", "сушить"),
    ("turnen", "заниматься"),
    ("übernachten", "ночевать"),
    ("überqueren", "переходить"),
    ("übersetzen", "переводить"),
    ("überweisen", "переводить"),
    ("umsteigen", "пересаживаться"),
    ("unterschreiben", "подписывать"),
    ("untersuchen", "исследовать"),
    ("verdienen", "зарабатывать"),
    ("vergessen", "забывать"),
    ("vergleichen", "сравнивать"),
    ("verkaufen", "продавать"),
    ("verlieren", "терять"),
    ("vermieten", "сдавать"),
    ("verpassen", "пропускать"),
    ("verstehen", "понимать"),
    ("versuchen", "пытаться"),
    ("vertrauen", "доверять"),
    ("verwenden", "использовать"),
    ("vorstellen", "представлять"),
    ("wachsen", "расти"),
    ("wagen", "рисковать"),
    ("wandern", "гулять"),
    ("warten", "ждать"),
    ("waschen", "мыть"),
    ("wechseln", "менять"),
    ("wecken", "будить"),
    ("weggehen", "уходить"),
    ("weinen", "плакать"),
    ("werfen", "бросать"),
    ("wiederholen", "повторять"),
    ("wissen", "знать"),
    ("wohnen", "жить"),
    ("wollen", "хотеть"),
    ("wünschen", "желать"),
    ("zahlen", "платить"),
    ("zeigen", "показывать"),
    ("zuhören", "слушать"),
    ("zurückkommen", "возвращаться"),
    ("zusammenarbeiten", "сотрудничать"),
    
    # Прилагательные
    ("alt", "старый"),
    ("arm", "бедный"),
    ("billig", "дешевый"),
    ("blond", "блондин"),
    ("blau", "синий"),
    ("breit", "широкий"),
    ("dick", "толстый"),
    ("dunkel", "темный"),
    ("einfach", "простой"),
    ("einzig", "единственный"),
    ("elektrisch", "электрический"),
    ("eng", "узкий"),
    ("ernst", "серьезный"),
    ("falsch", "неправильный"),
    ("faul", "ленивый"),
    ("fein", "тонкий"),
    ("fleißig", "прилежный"),
    ("fremd", "чужой"),
    ("frisch", "свежий"),
    ("froh", "радостный"),
    ("gesund", "здоровый"),
    ("glatt", "гладкий"),
    ("gleich", "одинаковый"),
    ("glücklich", "счастливый"),
    ("groß", "большой"),
    ("gut", "хороший"),
    ("heiß", "горячий"),
    ("hell", "светлый"),
    ("höflich", "вежливый"),
    ("hübsch", "красивый"),
    ("jung", "молодой"),
    ("klar", "ясный"),
    ("klein", "маленький"),
    ("klug", "умный"),
    ("krank", "больной"),
    ("kalt", "холодный"),
    ("komisch", "странный"),
    ("kostenlos", "бесплатный"),
    ("kurz", "короткий"),
    ("lang", "длинный"),
    ("langsam", "медленный"),
    ("leicht", "легкий"),
    ("leise", "тихий"),
    ("lustig", "веселый"),
    ("mager", "худой"),
    ("modern", "современный"),
    ("müde", "усталый"),
    ("nett", "милый"),
    ("neu", "новый"),
    ("nass", "мокрый"),
    ("nützlich", "полезный"),
    ("offen", "открытый"),
    ("ordentlich", "опрятный"),
    ("prima", "отличный"),
    ("pünktlich", "пунктуальный"),
    ("quiet", "тихий"),
    ("reich", "богатый"),
    ("rein", "чистый"),
    ("richtig", "правильный"),
    ("rund", "круглый"),
    ("sauber", "чистый"),
    ("schlecht", "плохой"),
    ("schön", "красивый"),
    ("schwer", "тяжелый"),
    ("schnell", "быстрый"),
    ("stark", "сильный"),
    ("still", "тихий"),
    ("stolz", "гордый"),
    ("sympathisch", "приятный"),
    ("teuer", "дорогой"),
    ("toll", "отличный"),
    ("tot", "мертвый"),
    ("traurig", "грустный"),
    ("trocken", "сухой"),
    ("überrascht", "удивленный"),
    ("unglücklich", "несчастный"),
    ("unhöflich", "невежливый"),
    ("unmöglich", "невозможный"),
    ("unruhig", "беспокойный"),
    ("unsicher", "неуверенный"),
    ("voll", "полный"),
    ("warm", "теплый"),
    ("weich", "мягкий"),
    ("weise", "мудрый"),
    ("weit", "далекий"),
    ("wichtig", "важный"),
    ("wild", "дикий"),
    ("wunderbar", "замечательный"),
    ("zufrieden", "довольный"),
    ("zuverlässig", "надежный"),
    ("zweites", "второй"),
]

print(f"🔍 Проверка {len(GOETHE_A1_WORDS)} слов A1...\n")

added_count = 0
existing_count = 0

for de, ru in GOETHE_A1_WORDS:
    # Определяем артикль
    article = None
    if de.startswith("der "):
        article = "der"
        de = de[4:]
    elif de.startswith("die "):
        article = "die"
        de = de[4:]
    elif de.startswith("das "):
        article = "das"
        de = de[4:]
    
    # Проверяем есть ли слово в базе
    cur.execute("""
        SELECT id FROM words 
        WHERE de ILIKE %s AND ru ILIKE %s AND level = 'A1'
    """, (de, ru))
    
    if cur.fetchone():
        existing_count += 1
    else:
        # Добавляем слово
        try:
            cur.execute("""
                INSERT INTO words (de, ru, article, level, topic, verb_forms)
                VALUES (%s, %s, %s, 'A1', 'Goethe A1', NULL)
            """, (de, ru, article))
            added_count += 1
            print(f"✅ Добавлено: {de} = {ru}" + (f" (артикль: {article})" if article else ""))
        except Exception as e:
            if "duplicate" in str(e).lower() or "unique" in str(e).lower():
                existing_count += 1
            else:
                print(f"❌ Ошибка: {e}")
                conn.rollback()

conn.commit()

print(f"\n📊 Итоги:")
print(f"   Уже в базе: {existing_count}")
print(f"   Добавлено: {added_count}")
print(f"   Всего: {len(GOETHE_A1_WORDS)}")

cur.close()
conn.close()
