# Goethe-Institut Vocabulary Dataset (A1, A2, B1)

GOETHE_WORDS = [
    # === A1: BASIC VOCABULARY (Survival) ===
    {"level": "A1", "topic": "Личные данные", "de": "Vorname", "ru": "Имя", "article": "der", "example_de": "Mein Vorname ist Thomas.", "example_ru": "Моё имя — Томас."},
    {"level": "A1", "topic": "Личные данные", "de": "Familienname", "ru": "Фамилия", "article": "der", "example_de": "Mein Familienname ist Müller.", "example_ru": "Моя фамилия — Мюллер."},
    {"level": "A1", "topic": "Личные данные", "de": "Geburtsort", "ru": "Место рождения", "article": "der", "example_de": "Mein Geburtsort ist Berlin.", "example_ru": "Место моего рождения — Берлин."},
    {"level": "A1", "topic": "Личные данные", "de": "Wohnort", "ru": "Место жительства", "article": "der", "example_de": "Mein Wohnort ist Hamburg.", "example_ru": "Моё место жительства — Гамбург."},
    {"level": "A1", "topic": "Личные данные", "de": "ledig", "ru": "холост/незамужем", "article": "", "example_de": "Ich bin ledig.", "example_ru": "Я холост."},
    {"level": "A1", "topic": "Личные данные", "de": "verheiratet", "ru": "женат/замужем", "article": "", "example_de": "Wir sind verheiratet.", "example_ru": "Мы женаты."},
    
    {"level": "A1", "topic": "Числа", "de": "eins", "ru": "один", "article": "", "example_de": "Eins plus eins ist zwei.", "example_ru": "Один плюс один — два."},
    {"level": "A1", "topic": "Числа", "de": "zehn", "ru": "десять", "article": "", "example_de": "Ich habe zehn Euro.", "example_ru": "У меня есть десять евро."},
    {"level": "A1", "topic": "Числа", "de": "hundert", "ru": "сто", "article": "", "example_de": "Das kostet hundert Euro.", "example_ru": "Это стоит сто евро."},
    
    {"level": "A1", "topic": "Время", "de": "Uhr", "ru": "час (время)", "article": "die", "example_de": "Es ist vier Uhr.", "example_ru": "Сейчас четыре часа."},
    {"level": "A1", "topic": "Время", "de": "Stunde", "ru": "час (продолжительность)", "article": "die", "example_de": "Eine Stunde hat 60 Minuten.", "example_ru": "В часе 60 минут."},
    {"level": "A1", "topic": "Время", "de": "Minute", "ru": "минута", "article": "die", "example_de": "Warten Sie eine Minute.", "example_ru": "Подождите минуту."},
    {"level": "A1", "topic": "Время", "de": "Tag", "ru": "день", "article": "der", "example_de": "Der Tag war lang.", "example_ru": "День был длинным."},
    {"level": "A1", "topic": "Время", "de": "Morgen", "ru": "утро", "article": "der", "example_de": "Am Morgen trinke ich Kaffee.", "example_ru": "Утром я пью кофе."},
    {"level": "A1", "topic": "Время", "de": "Mittag", "ru": "полдень", "article": "der", "example_de": "Zu Mittag esse ich Brot.", "example_ru": "В полдень я ем хлеб."},
    {"level": "A1", "topic": "Время", "de": "Abend", "ru": "вечер", "article": "der", "example_de": "Guten Abend!", "example_ru": "Добрый вечер!"},
    {"level": "A1", "topic": "Время", "de": "Nacht", "ru": "ночь", "article": "die", "example_de": "Gute Nacht!", "example_ru": "Спокойной ночи!"},
    {"level": "A1", "topic": "Время", "de": "heute", "ru": "сегодня", "article": "", "example_de": "Heute ist Montag.", "example_ru": "Сегодня понедельник."},
    {"level": "A1", "topic": "Время", "de": "morgen", "ru": "завтра", "article": "", "example_de": "Bis morgen!", "example_ru": "До завтра!"},
    {"level": "A1", "topic": "Время", "de": "gestern", "ru": "вчера", "article": "", "example_de": "Gestern war Sonntag.", "example_ru": "Вчера было воскресенье."},
    
    {"level": "A1", "topic": "Семья", "de": "Mutter", "ru": "мать", "article": "die", "example_de": "Meine Mutter kocht gern.", "example_ru": "Моя мама любит готовить."},
    {"level": "A1", "topic": "Семья", "de": "Vater", "ru": "отец", "article": "der", "example_de": "Mein Vater ist Lehrer.", "example_ru": "Мой отец — учитель."},
    {"level": "A1", "topic": "Семья", "de": "Eltern", "ru": "родители", "article": "die (Pl.)", "example_de": "Meine Eltern leben in Berlin.", "example_ru": "Мои родители живут в Берлине."},
    {"level": "A1", "topic": "Семья", "de": "Sohn", "ru": "сын", "article": "der", "example_de": "Mein Sohn ist fünf Jahre alt.", "example_ru": "Моему сыну пять лет."},
    {"level": "A1", "topic": "Семья", "de": "Tochter", "ru": "дочь", "article": "die", "example_de": "Unsere Tochter geht zur Schule.", "example_ru": "Наша дочь ходит в школу."},
    {"level": "A1", "topic": "Семья", "de": "Bruder", "ru": "брат", "article": "der", "example_de": "Hast du einen Bruder?", "example_ru": "У тебя есть брат?"},
    {"level": "A1", "topic": "Семья", "de": "Schwester", "ru": "сестра", "article": "die", "example_de": "Meine Schwester studiert Medizin.", "example_ru": "Моя сестра изучает медицину."},
    {"level": "A1", "topic": "Семья", "de": "Geschwister", "ru": "братья и сестры", "article": "die (Pl.)", "example_de": "Ich habe drei Geschwister.", "example_ru": "У меня трое братьев и сестер."},
    {"level": "A1", "topic": "Семья", "de": "Oma", "ru": "бабушка", "article": "die", "example_de": "Meine Oma ist 70.", "example_ru": "Моей бабушке 70."},
    {"level": "A1", "topic": "Семья", "de": "Opa", "ru": "дедушка", "article": "der", "example_de": "Mein Opa erzählt Geschichten.", "example_ru": "Мой дедушка рассказывает истории."},
    
    {"level": "A1", "topic": "Дом", "de": "Tisch", "ru": "стол", "article": "der", "example_de": "Der Tisch ist aus Holz.", "example_ru": "Стол сделан из дерева."},
    {"level": "A1", "topic": "Дом", "de": "Stuhl", "ru": "стул", "article": "der", "example_de": "Ich brauche einen Stuhl.", "example_ru": "Мне нужен стул."},
    {"level": "A1", "topic": "Дом", "de": "Bett", "ru": "кровать", "article": "das", "example_de": "Das Bett ist bequem.", "example_ru": "Кровать удобная."},
    {"level": "A1", "topic": "Дом", "de": "Schrank", "ru": "шкаф", "article": "der", "example_de": "Der Schrank ist weiß.", "example_ru": "Шкаф белый."},
    {"level": "A1", "topic": "Дом", "de": "Lampe", "ru": "лампа", "article": "die", "example_de": "Die Lampe ist hell.", "example_ru": "Лампа яркая."},
    {"level": "A1", "topic": "Дом", "de": "Bild", "ru": "картина", "article": "das", "example_de": "Das Bild an der Wand ist schön.", "example_ru": "Картина на стене красивая."},
    {"level": "A1", "topic": "Дом", "de": "Küche", "ru": "кухня", "article": "die", "example_de": "Die Küche ist modern.", "example_ru": "Кухня современная."},
    {"level": "A1", "topic": "Дом", "de": "Bad", "ru": "ванная", "article": "das", "example_de": "Das Bad ist klein.", "example_ru": "Ванная маленькая."},
    {"level": "A1", "topic": "Дом", "de": "Wohnzimmer", "ru": "гостиная", "article": "das", "example_de": "Wir sitzen im Wohnzimmer.", "example_ru": "Мы сидим в гостиной."},
    
    {"level": "A1", "topic": "Еда и напитки", "de": "Essen", "ru": "еда", "article": "das", "example_de": "Das Essen schmeckt gut.", "example_ru": "Еда вкусная."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Trinken", "ru": "напитки", "article": "das", "example_de": "Möchten Sie etwas trinken?", "example_ru": "Хотите чего-нибудь попить?"},
    {"level": "A1", "topic": "Еда и напитки", "de": "Frühstück", "ru": "завтрак", "article": "das", "example_de": "Das Frühstück ist fertig.", "example_ru": "Завтрак готов."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Mittagessen", "ru": "обед", "article": "das", "example_de": "Was gibt es zum Mittagessen?", "example_ru": "Что на обед?"},
    {"level": "A1", "topic": "Еда и напитки", "de": "Abendessen", "ru": "ужин", "article": "das", "example_de": "Wir kochen Abendessen.", "example_ru": "Мы готовим ужин."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Brot", "ru": "хлеб", "article": "das", "example_de": "Ein frisches Brot, bitte.", "example_ru": "Свежий хлеб, пожалуйста."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Brötchen", "ru": "булочка", "article": "das", "example_de": "Ich esse zwei Brötchen.", "example_ru": "Я съем две булочки."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Käse", "ru": "сыр", "article": "der", "example_de": "Der Käse ist mild.", "example_ru": "Сыр мягкий."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Wurst", "ru": "колбаса", "article": "die", "example_de": "Möchten Sie etwas Wurst?", "example_ru": "Хотите немного колбасы?"},
    {"level": "A1", "topic": "Еда и напитки", "de": "Fleisch", "ru": "мясо", "article": "das", "example_de": "Ich esse viel Fleisch.", "example_ru": "Я ем много мяса."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Gemüse", "ru": "овощи", "article": "das", "example_de": "Das Gemüse ist frisch.", "example_ru": "Овощи свежие."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Obst", "ru": "фрукты", "article": "das", "example_de": "Obst ist gesund.", "example_ru": "Фрукты полезны."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Apfel", "ru": "яблоко", "article": "der", "example_de": "Ein roter Apfel.", "example_ru": "Красное яблоко."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Banane", "ru": "банан", "article": "die", "example_de": "Die Banane ist gelb.", "example_ru": "Банан желтый."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Milch", "ru": "молоко", "article": "die", "example_de": "Ein Glas Milch, bitte.", "example_ru": "Стакан молока, пожалуйста."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Kaffee", "ru": "кофе", "article": "der", "example_de": "Ich trinke Kaffee mit Milch.", "example_ru": "Я пью кофе с молоком."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Tee", "ru": "чай", "article": "der", "example_de": "Möchten Sie Tee?", "example_ru": "Хотите чаю?"},
    {"level": "A1", "topic": "Еда и напитки", "de": "Wasser", "ru": "вода", "article": "das", "example_de": "Mineralwasser ohne Gas.", "example_ru": "Минеральная вода без газа."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Saft", "ru": "сок", "article": "der", "example_de": "Orangensaft ist lecker.", "example_ru": "Апельсиновый сок вкусный."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Bier", "ru": "пиво", "article": "das", "example_de": "Ein kühles Bier.", "example_ru": "Холодное пиво."},
    {"level": "A1", "topic": "Еда и напитки", "de": "Wein", "ru": "вино", "article": "der", "example_de": "Ein Glas Weißwein.", "example_ru": "Бокал белого вина."},
    
    {"level": "A1", "topic": "Одежда", "de": "Kleidung", "ru": "одежда", "article": "die", "example_de": "Die Kleidung ist sauber.", "example_ru": "Одежда чистая."},
    {"level": "A1", "topic": "Одежда", "de": "Hose", "ru": "брюки", "article": "die", "example_de": "Die Hose passt mir gut.", "example_ru": "Брюки мне впору."},
    {"level": "A1", "topic": "Одежда", "de": "Rock", "ru": "юбка", "article": "der", "example_de": "Der Rock ist kurz.", "example_ru": "Юбка короткая."},
    {"level": "A1", "topic": "Одежда", "de": "Kleid", "ru": "платье", "article": "das", "example_de": "Das Kleid ist blau.", "example_ru": "Платье синее."},
    {"level": "A1", "topic": "Одежда", "de": "Hemd", "ru": "рубашка", "article": "das", "example_de": "Das Hemd ist weiß.", "example_ru": "Рубашка белая."},
    {"level": "A1", "topic": "Одежда", "de": "T-Shirt", "ru": "футболка", "article": "das", "example_de": "Ein bequemes T-Shirt.", "example_ru": "Удобная футболка."},
    {"level": "A1", "topic": "Одежда", "de": "Jacke", "ru": "куртка", "article": "die", "example_de": "Zieh deine Jacke an.", "example_ru": "Надень куртку."},
    {"level": "A1", "topic": "Одежда", "de": "Schuh", "ru": "ботинок", "article": "der", "example_de": "Das sind meine neuen Schuhe.", "example_ru": "Это мои новые ботинки."},
    
    # === A2: EXTENDED VOCABULARY (Daily Life) ===
    {"level": "A2", "topic": "Работа", "de": "Arbeit", "ru": "работа", "article": "die", "example_de": "Ich habe viel Arbeit.", "example_ru": "У меня много работы."},
    {"level": "A2", "topic": "Работа", "de": "Beruf", "ru": "профессия", "article": "der", "example_de": "Was sind Sie von Beruf?", "example_ru": "Кто вы по профессии?"},
    {"level": "A2", "topic": "Работа", "de": "Arbeitsplatz", "ru": "рабочее место", "article": "der", "example_de": "Mein Arbeitsplatz ist modern.", "example_ru": "Моё рабочее место современное."},
    {"level": "A2", "topic": "Работа", "de": "Chef", "ru": "начальник", "article": "der", "example_de": "Der Chef ist nett.", "example_ru": "Начальник милый."},
    {"level": "A2", "topic": "Работа", "de": "Kollege", "ru": "коллега", "article": "der", "example_de": "Meine Kollegen sind hilfsbereit.", "example_ru": "Мои коллеги всегда готовы помочь."},
    {"level": "A2", "topic": "Работа", "de": "Büro", "ru": "офис", "article": "das", "example_de": "Ich arbeite im Büro.", "example_ru": "Я работаю в офисе."},
    {"level": "A2", "topic": "Работа", "de": "Gehalt", "ru": "зарплата", "article": "das", "example_de": "Das Gehalt ist gut.", "example_ru": "Зарплата хорошая."},
    {"level": "A2", "topic": "Работа", "de": "Überstunde", "ru": "сверхурочный час", "article": "die", "example_de": "Ich mache viele Überstunden.", "example_ru": "Я часто работаю сверхурочно."},
    
    {"level": "A2", "topic": "Здоровье", "de": "Gesundheit", "ru": "здоровье", "article": "die", "example_de": "Gesundheit ist wichtig.", "example_ru": "Здоровье — это важно."},
    {"level": "A2", "topic": "Здоровье", "de": "Krankheit", "ru": "болезнь", "article": "die", "example_de": "Er hat eine schwere Krankheit.", "example_ru": "У него тяжёлая болезнь."},
    {"level": "A2", "topic": "Здоровье", "de": "Arzt", "ru": "врач", "article": "der", "example_de": "Ich gehe zum Arzt.", "example_ru": "Я иду к врачу."},
    {"level": "A2", "topic": "Здоровье", "de": "Krankenhaus", "ru": "больница", "article": "das", "example_de": "Das Krankenhaus ist groß.", "example_ru": "Больница большая."},
    {"level": "A2", "topic": "Здоровье", "de": "Medikament", "ru": "лекарство", "article": "das", "example_de": "Nehmen Sie dieses Medikament.", "example_ru": "Принимайте это лекарство."},
    {"level": "A2", "topic": "Здоровье", "de": "Rezept", "ru": "рецепт", "article": "das", "example_de": "Der Arzt schreibt ein Rezept.", "example_ru": "Врач выписывает рецепт."},
    {"level": "A2", "topic": "Здоровье", "de": "Schmerz", "ru": "боль", "article": "der", "example_de": "Ich habe Kopfschmerzen.", "example_ru": "У меня болит голова."},
    {"level": "A2", "topic": "Здоровье", "de": "Fieber", "ru": "температура", "article": "das", "example_de": "Hast du Fieber?", "example_ru": "У тебя есть температура?"},
    {"level": "A2", "topic": "Здоровье", "de": "Apotheke", "ru": "аптека", "article": "die", "example_de": "Wo ist die nächste Apotheke?", "example_ru": "Где ближайшая аптека?"},
    
    {"level": "A2", "topic": "Путешествие", "de": "Reise", "ru": "путешествие", "article": "die", "example_de": "Die Reise war toll.", "example_ru": "Путешествие было классным."},
    {"level": "A2", "topic": "Путешествие", "de": "Urlaub", "ru": "отпуск", "article": "der", "example_de": "Ich mache Urlaub am Meer.", "example_ru": "Я провожу отпуск на море."},
    {"level": "A2", "topic": "Путешествие", "de": "Hotel", "ru": "отель", "article": "das", "example_de": "Das Hotel ist teuer.", "example_ru": "Отель дорогой."},
    {"level": "A2", "topic": "Путешествие", "de": "Bahn", "ru": "железная дорога", "article": "die", "example_de": "Ich fahre mit der Bahn.", "example_ru": "Я еду поездом."},
    {"level": "A2", "topic": "Путешествие", "de": "Flugzeug", "ru": "самолет", "article": "das", "example_de": "Das Flugzeug fliegt nach Paris.", "example_ru": "Самолет летит в Париж."},
    {"level": "A2", "topic": "Путешествие", "de": "Gepäck", "ru": "багаж", "article": "das", "example_de": "Haben Sie viel Gepäck?", "example_ru": "У вас много багажа?"},
    {"level": "A2", "topic": "Путешествие", "de": "Koffer", "ru": "чемодан", "article": "der", "example_de": "Mein Koffer ist schwer.", "example_ru": "Мой чемодан тяжелый."},
    {"level": "A2", "topic": "Путешествие", "de": "Ausflug", "ru": "экскурсия/вылазка", "article": "der", "example_de": "Wir machen einen Ausflug.", "example_ru": "Мы совершаем прогулку/экскурсию."},
    
    # === B1: ADVANCED VOCABULARY (Communication) ===
    {"level": "B1", "topic": "Общество", "de": "Gesellschaft", "ru": "общество", "article": "die", "example_de": "Unsere Gesellschaft ändert sich.", "example_ru": "Наше общество меняется."},
    {"level": "B1", "topic": "Общество", "de": "Verantwortung", "ru": "ответственность", "article": "die", "example_de": "Das ist deine Verantwortung.", "example_ru": "Это твоя ответственность."},
    {"level": "B1", "topic": "Общество", "de": "Umwelt", "ru": "окружающая среда", "article": "die", "example_de": "Wir müssen die Umwelt schützen.", "example_ru": "Мы должны защищать окружающую среду."},
    {"level": "B1", "topic": "Общество", "de": "Zukunft", "ru": "будущее", "article": "die", "example_de": "Die Zukunft ist ungewiss.", "example_ru": "Будущее неопределенно."},
    {"level": "B1", "topic": "Общество", "de": "Erfolg", "ru": "успех", "article": "der", "example_de": "Ich wünsche dir viel Erfolg.", "example_ru": "Желаю тебе большого успеха."},
    {"level": "B1", "topic": "Общество", "de": "Ziel", "ru": "цель", "article": "das", "example_de": "Was ist dein Ziel?", "example_ru": "Какая у тебя цель?"},
    {"level": "B1", "topic": "Общество", "de": "Erfahrung", "ru": "опыт", "article": "die", "example_de": "Sie hat viel Erfahrung im Beruf.", "example_ru": "У неё большой опыт в работе."},
    
    {"level": "B1", "topic": "Культура", "de": "Kultur", "ru": "культура", "article": "die", "example_de": "Interessieren Sie sich für Kultur?", "example_ru": "Вы интересуетесь культурой?"},
    {"level": "B1", "topic": "Культура", "de": "Museum", "ru": "музей", "article": "das", "example_de": "Das Museum zeigt moderne Kunst.", "example_ru": "В музее представлена современная живопись."},
    {"level": "B1", "topic": "Культура", "de": "Ausstellung", "ru": "выставка", "article": "die", "example_de": "Die Ausstellung war faszinierend.", "example_ru": "Выставка была захватывающей."},
    {"level": "B1", "topic": "Культура", "de": "Geschichte", "ru": "история", "article": "die", "example_de": "Erzähl mir eine Geschichte.", "example_ru": "Расскажи мне историю."},
    {"level": "B1", "topic": "Культура", "de": "Literatur", "ru": "литература", "article": "die", "example_de": "Ich liebe deutsche Literatur.", "example_ru": "Я люблю немецкую литературу."},
    
    {"level": "B1", "topic": "Отношения", "de": "Freundschaft", "ru": "дружба", "article": "die", "example_de": "Freundschaft ist wertvoll.", "example_ru": "Дружба ценна."},
    {"level": "B1", "topic": "Отношения", "de": "Beziehung", "ru": "отношения", "article": "die", "example_de": "Sie haben eine gute Beziehung.", "example_ru": "У них хорошие отношения."},
    {"level": "B1", "topic": "Отношения", "de": "Vertrauen", "ru": "доверие", "article": "das", "example_de": "Vertrauen ist die Basis.", "example_ru": "Доверие — это основа."},
    {"level": "B1", "topic": "Отношения", "de": "Ehrlichkeit", "ru": "честность", "article": "die", "example_de": "Ehrlichkeit ist mir wichtig.", "example_ru": "Честность для меня важна."},
    
    {"level": "B1", "topic": "Работа и образование", "de": "Ausbildung", "ru": "обучение/образование", "article": "die", "example_de": "Meine Ausbildung dauert drei Jahre.", "example_ru": "Моё обучение длится три года."},
    {"level": "B1", "topic": "Работа и образование", "de": "Fortbildung", "ru": "повышение квалификации", "article": "die", "example_de": "Ich mache eine Fortbildung.", "example_ru": "Я прохожу курсы повышения квалификации."},
    {"level": "B1", "topic": "Работа и образование", "de": "Studium", "ru": "учёба в вузе", "article": "das", "example_de": "Das Studium ist anstrengend.", "example_ru": "Учёба в университете утомительна."},
    {"level": "B1", "topic": "Работа и образование", "de": "Prüfung", "ru": "экзамен", "article": "die", "example_de": "Ich muss eine Prüfung bestehen.", "example_ru": "Я должен сдать экзамен."},
    {"level": "B1", "topic": "Работа и образование", "de": "Bewerbung", "ru": "заявление о приёме на работу", "article": "die", "example_de": "Ich schreibe eine Bewerbung.", "example_ru": "Я пишу заявление о приёме на работу."},
    {"level": "B1", "topic": "Работа и образование", "de": "Vorstellungsgespräch", "ru": "собеседование", "article": "das", "example_de": "Das Vorstellungsgespräch war gut.", "example_ru": "Собеседование прошло хорошо."},
    
    # === A1: Additional common words ===
    {"level": "A1", "topic": "Дом", "de": "Haus", "ru": "дом", "article": "das", "example_de": "Mein Haus ist groß.", "example_ru": "Мой дом большой."},
    {"level": "A1", "topic": "Дом", "de": "Wohnung", "ru": "квартира", "article": "die", "example_de": "Die Wohnung hat drei Zimmer.", "example_ru": "В квартире три комнаты."},
    {"level": "A1", "topic": "Дом", "de": "Schlüssel", "ru": "ключ", "article": "der", "example_de": "Wo ist der Schlüssel?", "example_ru": "Где ключ?"},
    {"level": "A1", "topic": "Город", "de": "Straße", "ru": "улица", "article": "die", "example_de": "Die Straße ist gesperrt.", "example_ru": "Улица перекрыта."},
    {"level": "A1", "topic": "Город", "de": "Stadt", "ru": "город", "article": "die", "example_de": "Berlin ist eine große Stadt.", "example_ru": "Берлин — большой город."},
    {"level": "A1", "topic": "Город", "de": "Park", "ru": "парк", "article": "der", "example_de": "Gehen wir in den Park?", "example_ru": "Пойдём в парк?"},
    
    # === A2: Additional common words ===
    {"level": "A2", "topic": "Свободное время", "de": "Hobby", "ru": "хобби", "article": "das", "example_de": "Mein Hobby ist Fotografie.", "example_ru": "Моё хобби — фотография."},
    {"level": "A2", "topic": "Свободное время", "de": "Sport", "ru": "спорт", "article": "der", "example_de": "Ich mache gern Sport.", "example_ru": "Я люблю заниматься спортом."},
    {"level": "A2", "topic": "Свободное время", "de": "Kino", "ru": "кино", "article": "das", "example_de": "Wir gehen heute ins Kino.", "example_ru": "Мы идём сегодня в кино."},
    {"level": "A2", "topic": "Свободное время", "de": "Musik", "ru": "музыка", "article": "die", "example_de": "Ich höre gern Musik.", "example_ru": "Я люблю слушать музыку."},
    
    # === B1: Additional common words ===
    {"level": "B1", "topic": "Мнение", "de": "Meinung", "ru": "мнение", "article": "die", "example_de": "Meiner Meinung nach ist das richtig.", "example_ru": "По моему мнению, это правильно."},
    {"level": "B1", "topic": "Мнение", "de": "Vorschlag", "ru": "предложение", "article": "der", "example_de": "Das ist ein guter Vorschlag.", "example_ru": "Это хорошее предложение."},
    {"level": "B1", "topic": "Мнение", "de": "Grund", "ru": "причина", "article": "der", "example_de": "Was ist der Grund dafür?", "example_ru": "В чём причина этого?"},

    # === Phase 2: Travel, Food, Work (A1-A2) ===
    {"level": "A1", "topic": "Транспорт", "de": "Bus", "ru": "автобус", "article": "der", "example_de": "Der Bus kommt pünktlich.", "example_ru": "Автобус приходит вовремя."},
    {"level": "A1", "topic": "Транспорт", "de": "Zug", "ru": "поезд", "article": "der", "example_de": "Der Zug fährt nach Berlin.", "example_ru": "Поезд едет в Берлин."},
    {"level": "A1", "topic": "Транспорт", "de": "Bahnhof", "ru": "вокзал", "article": "der", "example_de": "Wo ist der Bahnhof?", "example_ru": "Где вокзал?"},
    {"level": "A1", "topic": "Транспорт", "de": "Flughafen", "ru": "аэропорт", "article": "der", "example_de": "Zwei Kilometer bis zum Flughafen.", "example_ru": "Два километра до аэропорта."},
    {"level": "A1", "topic": "Транспорт", "de": "Fahrrad", "ru": "велосипед", "article": "das", "example_de": "Ich fahre gern Fahrrad.", "example_ru": "Я люблю кататься на велосипеде."},
    {"level": "A1", "topic": "Транспорт", "de": "Taxi", "ru": "такси", "article": "das", "example_de": "Wir nehmen ein Taxi.", "example_ru": "Мы возьмём такси."},
    
    {"level": "A2", "topic": "Еда", "de": "Gemüse", "ru": "овощи", "article": "das", "example_de": "Gemüse ist sehr gesund.", "example_ru": "Овощи очень полезны."},
    {"level": "A2", "topic": "Еда", "de": "Obst", "ru": "фрукты", "article": "das", "example_de": "Frisches Obst schmeckt gut.", "example_ru": "Свежие фрукты вкусные."},
    {"level": "A2", "topic": "Еда", "de": "Hähnchen", "ru": "курица (блюдо)", "article": "das", "example_de": "Ich esse gern Hähnchen.", "example_ru": "Я люблю курицу."},
    {"level": "A2", "topic": "Еда", "de": "Rindfleisch", "ru": "говядина", "article": "das", "example_de": "Rindfleisch ist teuer.", "example_ru": "Говядина дорогая."},
    {"level": "A2", "topic": "Еда", "de": "Salz", "ru": "соль", "article": "das", "example_de": "Haben Sie etwas Salz?", "example_ru": "У вас есть немного соли?"},
    {"level": "A2", "topic": "Еда", "de": "Pfeffer", "ru": "перец", "article": "der", "example_de": "Die Suppe braucht Pfeffer.", "example_ru": "В суп нужен перец."},
    {"level": "A2", "topic": "Еда", "de": "Zucker", "ru": "сахар", "article": "der", "example_de": "Kaffee ohne Zucker, bitte.", "example_ru": "Кофе без сахара, пожалуйста."},
    {"level": "A2", "topic": "Еда", "de": "Ei", "ru": "яйцо", "article": "das", "example_de": "Ich möchte ein gekochtes Ei.", "example_ru": "Я хочу варёное яйцо."},
    
    {"level": "A2", "topic": "Работа", "de": "Ausbildung", "ru": "профессиональное обучение", "article": "die", "example_de": "Meine Ausbildung dauert drei Jahre.", "example_ru": "Моё обучение длится три года."},
    {"level": "A2", "topic": "Работа", "de": "Erfahrung", "ru": "опыт", "article": "die", "example_de": "Ich habe viel Erfahrung.", "example_ru": "У меня много опыта."},
    {"level": "A2", "topic": "Работа", "de": "Betrieb", "ru": "предприятие", "article": "der", "example_de": "Der Betrieb ist sehr groß.", "example_ru": "Предприятие очень большое."},
    {"level": "A2", "topic": "Работа", "de": "Kollege", "ru": "коллега", "article": "der", "example_de": "Mein Kollege hilft mir.", "example_ru": "Мой коллега помогает мне."},
    {"level": "A2", "topic": "Работа", "de": "Vorteil", "ru": "преимущество", "article": "der", "example_de": "Das ist ein großer Vorteil.", "example_ru": "Это большое преимущество."},
    {"level": "A2", "topic": "Работа", "de": "Nachteil", "ru": "недостаток", "article": "der", "example_de": "Jeder Job hat Nachteile.", "example_ru": "У любой работы есть недостатки."},
    
    {"level": "A1", "topic": "Магазин", "de": "Geld", "ru": "деньги", "article": "das", "example_de": "Ich habe kein Geld.", "example_ru": "У меня нет денег."},
    {"level": "A1", "topic": "Магазин", "de": "Preis", "ru": "цена", "article": "der", "example_de": "Der Preis ist zu hoch.", "example_ru": "Цена слишком высокая."},
    {"level": "A1", "topic": "Магазин", "de": "billig", "ru": "дешево", "article": "", "example_de": "Das ist sehr billig.", "example_ru": "Это очень дешево."},
    {"level": "A1", "topic": "Магазин", "de": "teuer", "ru": "дорого", "article": "", "example_de": "Das Kleid ist teuer.", "example_ru": "Это платье дорогое."},
    {"level": "A1", "topic": "Магазин", "de": "kaufen", "ru": "покупать", "article": "", "example_de": "Ich kaufe einen Apfel.", "example_ru": "Я покупаю яблоко."},
    {"level": "A1", "topic": "Магазин", "de": "verkaufen", "ru": "продавать", "article": "", "example_de": "Wir verkaufen unser Auto.", "example_ru": "Мы продаём нашу машину."},

    # === Phase 3: Society, Technology, Abstract (B1) ===
    {"level": "B1", "topic": "Общество", "de": "Demokratie", "ru": "демократия", "article": "die", "example_de": "Wir leben in einer Demokratie.", "example_ru": "Мы живем в условиях демократии."},
    {"level": "B1", "topic": "Общество", "de": "Gesetz", "ru": "закон", "article": "das", "example_de": "Das Gesetz ist für alle gleich.", "example_ru": "Закон одинаков для всех."},
    {"level": "B1", "topic": "Общество", "de": "Freiheit", "ru": "свобода", "article": "die", "example_de": "Pressefreiheit ist wichtig.", "example_ru": "Свобода прессы важна."},
    {"level": "B1", "topic": "Общество", "de": "Gleichheit", "ru": "равенство", "article": "die", "example_de": "Gleichheit vor dem Gesetz.", "example_ru": "Равенство перед законом."},
    {"level": "B1", "topic": "Общество", "de": "Frieden", "ru": "мир (отсутствие войны)", "article": "der", "example_de": "Alle wollen Frieden.", "example_ru": "Все хотят мира."},
    {"level": "B1", "topic": "Общество", "de": "Sicherheit", "ru": "безопасность", "article": "die", "example_de": "Sicherheit steht an erster Stelle.", "example_ru": "Безопасность на первом месте."},
    
    {"level": "B1", "topic": "Технологии", "de": "Internet", "ru": "интернет", "article": "das", "example_de": "Das Internet ist heute unverzichtbar.", "example_ru": "Интернет сегодня незаменим."},
    {"level": "B1", "topic": "Технологии", "de": "Computer", "ru": "компьютер", "article": "der", "example_de": "Mein Computer ist sehr schnell.", "example_ru": "Мой компьютер очень быстрый."},
    {"level": "B1", "topic": "Технологии", "de": "Smartphone", "ru": "смартфон", "article": "das", "example_de": "Ich habe ein neues Smartphone.", "example_ru": "У меня новый смартфон."},
    {"level": "B1", "topic": "Технологии", "de": "Software", "ru": "программное обеспечение", "article": "die", "example_de": "Die Software muss aktualisiert werden.", "example_ru": "Программное обеспечение нужно обновить."},
    {"level": "B1", "topic": "Технологии", "de": "Daten", "ru": "данные", "article": "die (Pl.)", "example_de": "Ihre Daten sind sicher.", "example_ru": "Ваши данные в безопасности."},
    {"level": "B1", "topic": "Технологии", "de": "Netzwerk", "ru": "сеть", "article": "das", "example_de": "Das Netzwerk ist ausgefallen.", "example_ru": "Сеть вышла из строя."},
    
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Wahrheit", "ru": "правда", "article": "die", "example_de": "Sag mir die Wahrheit.", "example_ru": "Скажи мне правду."},
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Lüge", "ru": "ложь", "article": "die", "example_de": "Das war eine Lüge.", "example_ru": "Это была ложь."},
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Glück", "ru": "счастье/удача", "article": "das", "example_de": "Viel Glück!", "example_ru": "Удачи!"},
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Unglück", "ru": "несчастье", "article": "das", "example_de": "Das war ein großes Unglück.", "example_ru": "Это было большое несчастье."},
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Hoffnung", "ru": "надежда", "article": "die", "example_de": "Die Hoffnung stirbt zuletzt.", "example_ru": "Надежда умирает последней."},
    {"level": "B1", "topic": "Абстрактные понятия", "de": "Angst", "ru": "страх", "article": "die", "example_de": "Ich habe keine Angst.", "example_ru": "Мне не страшно."},

    # === Phase 4: Verbs, Adjectives, Connectors (A1-B1) ===
    {"level": "A1", "topic": "Глаголы", "de": "machen", "ru": "делать", "article": "", "example_de": "Was machst du?", "example_ru": "Что ты делаешь?"},
    {"level": "A1", "topic": "Глаголы", "de": "gehen", "ru": "идти", "article": "", "example_de": "Wir gehen nach Hause.", "example_ru": "Мы идем домой."},
    {"level": "A1", "topic": "Глаголы", "de": "kommen", "ru": "приходить", "article": "", "example_de": "Woher kommst du?", "example_ru": "Откуда ты?"},
    {"level": "A1", "topic": "Глаголы", "de": "sprechen", "ru": "говорить", "article": "", "example_de": "Sprichst du Deutsch?", "example_ru": "Ты говоришь по-немецки?"},
    {"level": "A1", "topic": "Глаголы", "de": "lernen", "ru": "учить", "article": "", "example_de": "Ich lerne viel.", "example_ru": "Я много учусь."},
    
    {"level": "A2", "topic": "Глаголы", "de": "besuchen", "ru": "посещать", "article": "", "example_de": "Ich besuche meine Oma.", "example_ru": "Я навещаю бабушку."},
    {"level": "A2", "topic": "Глаголы", "de": "verstehen", "ru": "понимать", "article": "", "example_de": "Ich verstehe das nicht.", "example_ru": "Я этого не понимаю."},
    {"level": "A2", "topic": "Глаголы", "de": "erzählen", "ru": "рассказывать", "article": "", "example_de": "Erzähl mir eine Geschichte.", "example_ru": "Расскажи мне историю."},
    {"level": "A2", "topic": "Глаголы", "de": "helfen", "ru": "помогать", "article": "", "example_de": "Kann ich dir helfen?", "example_ru": "Я могу тебе помочь?"},
    {"level": "A2", "topic": "Глаголы", "de": "hoffen", "ru": "надеяться", "article": "", "example_de": "Ich hoffe, es geht dir gut.", "example_ru": "Надеюсь, у тебя всё хорошо."},
    
    {"level": "B1", "topic": "Глаголы", "de": "entscheiden", "ru": "решать", "article": "", "example_de": "Du musst dich entscheiden.", "example_ru": "Ты должен решить."},
    {"level": "B1", "topic": "Глаголы", "de": "entwickeln", "ru": "развивать", "article": "", "example_de": "Die Firma entwickelt neue Software.", "example_ru": "Фирма разрабатывает новое ПО."},
    {"level": "B1", "topic": "Глаголы", "de": "empfehlen", "ru": "рекомендовать", "article": "", "example_de": "Was kannst du empfehlen?", "example_ru": "Что ты можешь порекомендовать?"},
    {"level": "B1", "topic": "Глаголы", "de": "vergleichen", "ru": "сравнивать", "article": "", "example_de": "Wir vergleichen die Preise.", "example_ru": "Мы сравниваем цены."},
    
    {"level": "A1", "topic": "Прилагательные", "de": "schön", "ru": "красивый", "article": "", "example_de": "Das Wetter ist schön.", "example_ru": "Погода хорошая."},
    {"level": "A1", "topic": "Прилагательные", "de": "groß", "ru": "большой", "article": "", "example_de": "Die Stadt ist groß.", "example_ru": "Город большой."},
    {"level": "A1", "topic": "Прилагательные", "de": "klein", "ru": "маленький", "article": "", "example_de": "Das Zimmer ist klein.", "example_ru": "Комната маленькая."},
    {"level": "A1", "topic": "Прилагательные", "de": "gut", "ru": "хороший", "article": "", "example_de": "Alles gut.", "example_ru": "Всё хорошо."},
    
    {"level": "A2", "topic": "Прилагательные", "de": "wichtig", "ru": "важный", "article": "", "example_de": "Das ist sehr wichtig.", "example_ru": "Это очень важно."},
    {"level": "A2", "topic": "Прилагательные", "de": "schwierig", "ru": "трудный", "article": "", "example_de": "Die Aufgabe ist schwierig.", "example_ru": "Задание трудное."},
    {"level": "A2", "topic": "Прилагательные", "de": "einfach", "ru": "простой", "article": "", "example_de": "Deutsch ist nicht einfach.", "example_ru": "Немецкий не прост."},
    {"level": "A2", "topic": "Прилагательные", "de": "langsam", "ru": "медленный", "article": "", "example_de": "Fahren Sie bitte langsam.", "example_ru": "Езжайте, пожалуйста, медленно."},
    
    {"level": "B1", "topic": "Прилагательные", "de": "bewusst", "ru": "сознательный", "article": "", "example_de": "Das war eine bewusste Entscheidung.", "example_ru": "Это было осознанное решение."},
    {"level": "B1", "topic": "Прилагательные", "de": "häufig", "ru": "частый", "article": "", "example_de": "Das passiert häufig.", "example_ru": "Это случается часто."},
    {"level": "B1", "topic": "Прилагательные", "de": "selten", "ru": "редкий", "article": "", "example_de": "Ich sehe ihn nur selten.", "example_ru": "Я вижу его редко."},
    
    {"level": "A2", "topic": "Союзы", "de": "weil", "ru": "потому что", "article": "", "example_de": "Ich lerne, weil es Spaß macht.", "example_ru": "Я учусь, потому что это весело."},
    {"level": "A2", "topic": "Союзы", "de": "dass", "ru": "что", "article": "", "example_de": "Ich sage, dass es gut ist.", "example_ru": "Я говорю, что это хорошо."},
    {"level": "B1", "topic": "Союзы", "de": "obwohl", "ru": "хотя", "article": "", "example_de": "Obwohl es regnet, gehen wir raus.", "example_ru": "Хотя идет дождь, мы выходим."},

    # === Phase 5: Massive Bulk Expansion (A1-B1) ===
    # --- Verbs (A1-A2) ---
    {"level": "A1", "topic": "Глаголы", "de": "essen", "ru": "есть", "article": "", "example_de": "Ich esse einen Apfel.", "example_ru": "Я ем яблоко."},
    {"level": "A1", "topic": "Глаголы", "de": "trinken", "ru": "пить", "article": "", "example_de": "Trinkst du Wasser?", "example_ru": "Ты пьешь воду?"},
    {"level": "A1", "topic": "Глаголы", "de": "schlafen", "ru": "спать", "article": "", "example_de": "Das Baby schläft.", "example_ru": "Ребенок спит."},
    {"level": "A1", "topic": "Глаголы", "de": "hören", "ru": "слышать/слушать", "article": "", "example_de": "Ich höre Musik.", "example_ru": "Я слушаю музыку."},
    {"level": "A1", "topic": "Глаголы", "de": "sehen", "ru": "видеть/смотреть", "article": "", "example_de": "Siehst du das Haus?", "example_ru": "Ты видишь этот дом?"},
    {"level": "A1", "topic": "Глаголы", "de": "lesen", "ru": "читать", "article": "", "example_de": "Ich lese ein Buch.", "example_ru": "Я читаю книгу."},
    {"level": "A1", "topic": "Глаголы", "de": "schreiben", "ru": "писать", "article": "", "example_de": "Er schreibt einen Brief.", "example_ru": "Он пишет письмо."},
    {"level": "A1", "topic": "Глаголы", "de": "fahren", "ru": "ехать", "article": "", "example_de": "Wir fahren nach Berlin.", "example_ru": "Мы едем в Берлин."},
    {"level": "A1", "topic": "Глаголы", "de": "fliegen", "ru": "летать", "article": "", "example_de": "Das Flugzeug fliegt hoch.", "example_ru": "Самолет летит высоко."},
    {"level": "A1", "topic": "Глаголы", "de": "schwimmen", "ru": "плавать", "article": "", "example_de": "Ich schwimme im See.", "example_ru": "Я плаваю в озере."},
    
    # --- Adjectives (A1-A2) ---
    {"level": "A1", "topic": "Прилагательные", "de": "alt", "ru": "старый", "article": "", "example_de": "Das Auto ist alt.", "example_ru": "Машина старая."},
    {"level": "A1", "topic": "Прилагательные", "de": "jung", "ru": "молодой", "article": "", "example_de": "Der Mann ist jung.", "example_ru": "Мужчина молодой."},
    {"level": "A1", "topic": "Прилагательные", "de": "neu", "ru": "новый", "article": "", "example_de": "Das ist ein neues Handy.", "example_ru": "Это новый телефон."},
    {"level": "A1", "topic": "Прилагательные", "de": "kalt", "ru": "холодный", "article": "", "example_de": "Das Wasser ist kalt.", "example_ru": "Вода холодная."},
    {"level": "A1", "topic": "Прилагательные", "de": "warm", "ru": "теплый", "article": "", "example_de": "Es ist warm heute.", "example_ru": "Сегодня тепло."},
    {"level": "A1", "topic": "Прилагательные", "de": "heiß", "ru": "горячий", "article": "", "example_de": "Der Kaffee ist heiß.", "example_ru": "Кофе горячий."},
    {"level": "A1", "topic": "Прилагательные", "de": "billig", "ru": "дешевый", "article": "", "example_de": "Das Brot ist billig.", "example_ru": "Хлеб дешевый."},
    {"level": "A1", "topic": "Прилагательные", "de": "teuer", "ru": "дорогой", "article": "", "example_de": "Das Auto ist teuer.", "example_ru": "Машина дорогая."},
    {"level": "A1", "topic": "Прилагательные", "de": "hell", "ru": "светлый", "article": "", "example_de": "Das Zimmer ist hell.", "example_ru": "Комната светлая."},
    {"level": "A1", "topic": "Прилагательные", "de": "dunkel", "ru": "темный", "article": "", "example_de": "Es ist schon dunkel.", "example_ru": "Уже темно."},
    
    # --- Nouns (A1-A2: Body, Clothes, Office) ---
    {"level": "A1", "topic": "Тело", "de": "Kopf", "ru": "голова", "article": "der", "example_de": "Mein Kopf tut weh.", "example_ru": "У меня болит голова."},
    {"level": "A1", "topic": "Тело", "de": "Hand", "ru": "рука (кисть)", "article": "die", "example_de": "Gib mir deine Hand.", "example_ru": "Дай мне свою руку."},
    {"level": "A1", "topic": "Тело", "de": "Arm", "ru": "рука (вся)", "article": "der", "example_de": "Mein Arm ist stark.", "example_ru": "Моя рука сильная."},
    {"level": "A1", "topic": "Тело", "de": "Bein", "ru": "нога", "article": "das", "example_de": "Das Bein ist gebrochen.", "example_ru": "Нога сломана."},
    {"level": "A1", "topic": "Тело", "de": "Fuß", "ru": "ступня", "article": "der", "example_de": "Ich habe große Füße.", "example_ru": "У меня большие ступни."},
    {"level": "A1", "topic": "Тело", "de": "Auge", "ru": "глаз", "article": "das", "example_de": "Ihre Augen sind blau.", "example_ru": "Её глаза голубые."},
    {"level": "A1", "topic": "Тело", "de": "Ohr", "ru": "ухо", "article": "das", "example_de": "Hörst du mit den Ohren?", "example_ru": "Ты слышишь ушами?"},
    {"level": "A1", "topic": "Тело", "de": "Mund", "ru": "рот", "article": "der", "example_de": "Mach den Mund auf.", "example_ru": "Открой рот."},
    
    {"level": "A2", "topic": "Одежда", "de": "Anzug", "ru": "костюм", "article": "der", "example_de": "Der Anzug passt perfekt.", "example_ru": "Костюм сидит идеально."},
    {"level": "A2", "topic": "Одежда", "de": "Mantel", "ru": "пальто", "article": "der", "example_de": "Zieh deinen Mantel an.", "example_ru": "Надень пальто."},
    {"level": "A2", "topic": "Одежда", "de": "Mütze", "ru": "шапка", "article": "die", "example_de": "Es ist kalt, nimm eine Mütze.", "example_ru": "Холодно, возьми шапку."},
    {"level": "A2", "topic": "Одежда", "de": "Handschuh", "ru": "перчатка", "article": "der", "example_de": "Wo sind meine Handschuhe?", "example_ru": "Где мои перчатки?"},
    {"level": "A2", "topic": "Одежда", "de": "Socke", "ru": "носок", "article": "die", "example_de": "Ich brauche neue Socken.", "example_ru": "Мне нужны новые носки."},
    
    {"level": "A2", "topic": "Офис", "de": "Drucker", "ru": "принтер", "article": "der", "example_de": "Der Drucker hat kein Papier.", "example_ru": "В принтере нет бумаги."},
    {"level": "A2", "topic": "Офис", "de": "Bildschirm", "ru": "экран/монитор", "article": "der", "example_de": "Der Bildschirm ist zu hell.", "example_ru": "Экран слишком яркий."},
    {"level": "A2", "topic": "Офис", "de": "Tastatur", "ru": "клавиатура", "article": "die", "example_de": "Die Tastatur ist kabellos.", "example_ru": "Клавиатура беспроводная."},
    {"level": "A2", "topic": "Офис", "de": "Maus", "ru": "мышь", "article": "die", "example_de": "Die Maus liegt auf dem Tisch.", "example_ru": "Мышь лежит на столе."},
    {"level": "A2", "topic": "Офис", "de": "Briefumschlag", "ru": "конверт", "article": "der", "example_de": "Hast du einen Briefumschlag?", "example_ru": "У тебя есть конверт?"},
    
    # --- Abstract & Detailed (B1) ---
    {"level": "B1", "topic": "Бизнес", "de": "Unternehmen", "ru": "предприятие/компания", "article": "das", "example_de": "Das Unternehmen wächst schnell.", "example_ru": "Компания быстро растет."},
    {"level": "B1", "topic": "Бизнес", "de": "Kunde", "ru": "клиент", "article": "der", "example_de": "Der Kunde ist König.", "example_ru": "Клиент — это король."},
    {"level": "B1", "topic": "Бизнес", "de": "Angebot", "ru": "предложение", "article": "das", "example_de": "Wir haben ein gutes Angebot.", "example_ru": "У нас есть хорошее предложение."},
    {"level": "B1", "topic": "Бизнес", "de": "Vertrag", "ru": "контракт/договор", "article": "der", "example_de": "Unterschreiben Sie den Vertrag.", "example_ru": "Подпишите контракт."},
    {"level": "B1", "topic": "Бизнес", "de": "Versicherung", "ru": "страховка", "article": "die", "example_de": "Hast du eine Versicherung?", "example_ru": "У тебя есть страховка?"},
    
    {"level": "B1", "topic": "Природа", "de": "Umweltschutz", "ru": "защита окружающей среды", "article": "der", "example_de": "Umweltschutz geht uns alle an.", "example_ru": "Защита среды касается всех нас."},
    {"level": "B1", "topic": "Природа", "de": "Klimawandel", "ru": "изменение климата", "article": "der", "example_de": "Der Klimawandel ist ein Problem.", "example_ru": "Изменение климата — это проблема."},
    {"level": "B1", "topic": "Природа", "de": "Wald", "ru": "лес", "article": "der", "example_de": "Der Wald ist erholsam.", "example_ru": "Лес помогает отдохнуть."},
    {"level": "B1", "topic": "Природа", "de": "Fluss", "ru": "река", "article": "der", "example_de": "Der Fluss fließt ins Meer.", "example_ru": "Река впадает в море."},
    {"level": "B1", "topic": "Природа", "de": "Berg", "ru": "гора", "article": "der", "example_de": "Der Berg ist sehr hoch.", "example_ru": "Гора очень высокая."},
    
    # --- More Common Words (A1-B1) ---
    {"level": "A1", "topic": "Место", "de": "hier", "ru": "здесь", "article": "", "example_de": "Komm hierher.", "example_ru": "Подойди сюда."},
    {"level": "A1", "topic": "Место", "de": "dort", "ru": "там", "article": "", "example_de": "Dort steht ein Haus.", "example_ru": "Там стоит дом."},
    {"level": "A2", "topic": "Место", "de": "überall", "ru": "везде", "article": "", "example_de": "Ich habe überall gesucht.", "example_ru": "Я искал везде."},
    {"level": "A2", "topic": "Место", "de": "nirgends", "ru": "никуда", "article": "", "example_de": "Ich finde es nirgends.", "example_ru": "Я нигде не могу это найти."},
    
    {"level": "A1", "topic": "Время", "de": "oft", "ru": "часто", "article": "", "example_de": "Ich gehe oft spazieren.", "example_ru": "Я часто хожу гулять."},
    {"level": "A1", "topic": "Время", "de": "manchmal", "ru": "иногда", "article": "", "example_de": "Manchmal regnet es.", "example_ru": "Иногда идет дождь."},
    {"level": "A1", "topic": "Время", "de": "nie", "ru": "никогда", "article": "", "example_de": "Ich war nie dort.", "example_ru": "Я там никогда не был."},
    {"level": "A2", "topic": "Время", "de": "immer", "ru": "всегда", "article": "", "example_de": "Du bist immer pünktlich.", "example_ru": "Ты всегда вовремя."},
    {"level": "A2", "topic": "Время", "de": "selten", "ru": "редко", "article": "", "example_de": "Das passiert selten.", "example_ru": "Это случается редко."},
    
    {"level": "B1", "topic": "Коннекторы", "de": "deshalb", "ru": "поэтому", "article": "", "example_de": "Ich bin krank, deshalb bleibe ich zu Hause.", "example_ru": "Я болен, поэтому остаюсь дома."},
    {"level": "B1", "topic": "Коннекторы", "de": "außerdem", "ru": "кроме того", "article": "", "example_de": "Außerdem möchte ich sagen...", "example_ru": "Кроме того, я хочу сказать..."},
    {"level": "B1", "topic": "Коннекторы", "de": "trotzdem", "ru": "тем не менее", "article": "", "example_de": "Es regnet, trotzdem gehen wir.", "example_ru": "Идет дождь, тем не менее мы идем."},

    # === Phase 6: Final Massive Bulk (A1-B1) - 600+ words goal ===
    # --- Health & Wellness (A2-B1) ---
    {"level": "A2", "topic": "Здоровье", "de": "Krankenhaus", "ru": "больница", "article": "das", "example_de": "Er ist im Krankenhaus.", "example_ru": "Он в больнице."},
    {"level": "A2", "topic": "Здоровье", "de": "Apotheke", "ru": "аптека", "article": "die", "example_de": "Wo ist die Apotheke?", "example_ru": "Где аптека?"},
    {"level": "A2", "topic": "Здоровье", "de": "Medikament", "ru": "лекарство", "article": "das", "example_de": "Nimm deine Medikamente.", "example_ru": "Принимай свои лекарства."},
    {"level": "A2", "topic": "Здоровье", "de": "Schmerz", "ru": "боль", "article": "der", "example_de": "Ich habe Schmerzen.", "example_ru": "У меня боли."},
    {"level": "B1", "topic": "Здоровье", "de": "Untersuchung", "ru": "обследование", "article": "die", "example_de": "Die Untersuchung war gründlich.", "example_ru": "Обследование было тщательным."},
    {"level": "B1", "topic": "Здоровье", "de": "Operation", "ru": "операция", "article": "die", "example_de": "Die Operation war erfolgreich.", "example_ru": "Операция прошла успешно."},
    
    # --- Media & Communication (B1) ---
    {"level": "B1", "topic": "СМИ", "de": "Zeitung", "ru": "газета", "article": "die", "example_de": "Ich lese jeden Tag die Zeitung.", "example_ru": "Я читаю газету каждый день."},
    {"level": "B1", "topic": "СМИ", "de": "Nachricht", "ru": "новость", "article": "die", "example_de": "Hast du die Nachrichten gesehen?", "example_ru": "Ты видел новости?"},
    {"level": "B1", "topic": "СМИ", "de": "Werbung", "ru": "реклама", "article": "die", "example_de": "Die Werbung ist sehr kreativ.", "example_ru": "Реклама очень креативная."},
    {"level": "B1", "topic": "СМИ", "de": "Sendung", "ru": "передача", "article": "die", "example_de": "Das ist eine interessante Sendung.", "example_ru": "Это интересная передача."},
    {"level": "B1", "topic": "СМИ", "de": "Journalist", "ru": "журналист", "article": "der", "example_de": "Der Journalist stellt viele Fragen.", "example_ru": "Журналист задает много вопросов."},
    
    # --- Environment & Nature (B1) ---
    {"level": "B1", "topic": "Природа", "de": "Energie", "ru": "энергия", "article": "die", "example_de": "Wir brauchen grüne Energie.", "example_ru": "Нам нужна зеленая энергия."},
    {"level": "B1", "topic": "Природа", "de": "Abfall", "ru": "отходы/мусор", "article": "der", "example_de": "Vermeiden Sie Abfall.", "example_ru": "Избегайте отходов."},
    {"level": "B1", "topic": "Природа", "de": "Luft", "ru": "воздух", "article": "die", "example_de": "Die Luft ist hier so frisch.", "example_ru": "Воздух здесь такой свежий."},
    {"level": "B1", "topic": "Природа", "de": "Pflanze", "ru": "растение", "article": "die", "example_de": "Diese Pflanze braucht Wasser.", "example_ru": "Этому растению нужна вода."},
    {"level": "B1", "topic": "Природа", "de": "Tierwelt", "ru": "животный мир", "article": "die", "example_de": "Schützen wir die Tierwelt.", "example_ru": "Давайте защищать животных."},
    
    # --- Education & Career (B1) ---
    {"level": "B1", "topic": "Образование", "de": "Kenntnisse", "ru": "знания", "article": "die (Pl.)", "example_de": "Gute Sprachkenntnisse sind wichtig.", "example_ru": "Хорошие знания языка важны."},
    {"level": "B1", "topic": "Образование", "de": "Voraussetzung", "ru": "условие/предпосылка", "article": "die", "example_de": "Das ist eine wichtige Voraussetzung.", "example_ru": "Это важная предпосылка."},
    {"level": "B1", "topic": "Образование", "de": "Abschluss", "ru": "окончание (вуза/школы)", "article": "der", "example_de": "Sie hat einen tollen Abschluss.", "example_ru": "У неё прекрасный диплом/окончание."},
    {"level": "B1", "topic": "Образование", "de": "Berufserfahrung", "ru": "опыт работы", "article": "die", "example_de": "Haben Sie Berufserfahrung?", "example_ru": "У вас есть опыт работы?"},
    
    # --- Feelings & Relationships (A2-B1) ---
    {"level": "A2", "topic": "Чувства", "de": "glücklich", "ru": "счастливый", "article": "", "example_de": "Ich bin so glücklich.", "example_ru": "Я так счастлив."},
    {"level": "A2", "topic": "Чувства", "de": "traurig", "ru": "грустный", "article": "", "example_de": "Warum bist du traurig?", "example_ru": "Почему ты грустный?"},
    {"level": "A2", "topic": "Чувства", "de": "nervös", "ru": "нервный", "article": "", "example_de": "Sei nicht so nervös.", "example_ru": "Не нервничай так."},
    {"level": "B1", "topic": "Чувства", "de": "Enttäuschung", "ru": "разочарование", "article": "die", "example_de": "Das war eine große Enttäuschung.", "example_ru": "Это было большое разочарование."},
    {"level": "B1", "topic": "Чувства", "de": "Eifersucht", "ru": "ревность", "article": "die", "example_de": "Eifersucht ist gefährlich.", "example_ru": "Ревность опасна."},
    
    # --- Verbs (Phase 6 - High Frequency) ---
    {"level": "A1", "topic": "Глаголы", "de": "kochen", "ru": "готовить", "article": "", "example_de": "Ich koche die Suppe.", "example_ru": "Я готовлю суп."},
    {"level": "A1", "topic": "Глаголы", "de": "spielen", "ru": "играть", "article": "", "example_de": "Die Kinder spielen.", "example_ru": "Дети играют."},
    {"level": "A1", "topic": "Глаголы", "de": "suchen", "ru": "искать", "article": "", "example_de": "Ich suche meine Brille.", "example_ru": "Я ищу свои очки."},
    {"level": "A1", "topic": "Глаголы", "de": "finden", "ru": "находить", "article": "", "example_de": "Ich habe es gefunden.", "example_ru": "Я это нашел."},
    {"level": "A1", "topic": "Глаголы", "de": "kaufen", "ru": "покупать", "article": "", "example_de": "Ich kaufe ein Ticket.", "example_ru": "Я покупаю билет."},
    {"level": "A2", "topic": "Глаголы", "de": "erklären", "ru": "объяснять", "article": "", "example_de": "Kannst du das erklären?", "example_ru": "Можешь это объяснить?"},
    {"level": "A2", "topic": "Глаголы", "de": "versuchen", "ru": "пробовать", "article": "", "example_de": "Ich versuche es еще раз.", "example_ru": "Я попробую еще раз."},
    {"level": "A2", "topic": "Глаголы", "de": "passieren", "ru": "случаться", "article": "", "example_de": "Was ist passiert?", "example_ru": "Что случилось?"},
    {"level": "B1", "topic": "Глаголы", "de": "vermeiden", "ru": "избегать", "article": "", "example_de": "Vermeiden Sie Stress.", "example_ru": "Избегайте стресса."},
    {"level": "B1", "topic": "Глаголы", "de": "beeinflussen", "ru": "влиять", "article": "", "example_de": "Das Wetter beeinflusst mich.", "example_ru": "Погода влияет на меня."},
    {"level": "B1", "topic": "Глаголы", "de": "beobachten", "ru": "наблюдать", "article": "", "example_de": "Wir beobachten die Vögel.", "example_ru": "Мы наблюдаем за птицами."},
    
    # --- Adjectives (Phase 6 - Descriptions) ---
    {"level": "A1", "topic": "Прилагательные", "de": "kurz", "ru": "короткий", "article": "", "example_de": "Der Weg ist kurz.", "example_ru": "Путь короткий."},
    {"level": "A1", "topic": "Прилагательные", "de": "lang", "ru": "длинный", "article": "", "example_de": "Die Nacht ist lang.", "example_ru": "Ночь длинная."},
    {"level": "A1", "topic": "Прилагательные", "de": "leicht", "ru": "легкий", "article": "", "example_de": "Deutsch ist leicht.", "example_ru": "Немецкий - это легко."},
    {"level": "A1", "topic": "Прилагательные", "de": "schwer", "ru": "тяжелый", "article": "", "example_de": "Der Koffer ist schwer.", "example_ru": "Чемодан тяжелый."},
    {"level": "A2", "topic": "Прилагательные", "de": "höflich", "ru": "вежливый", "article": "", "example_de": "Er ist sehr höflich.", "example_ru": "Он очень вежлив."},
    {"level": "A2", "topic": "Прилагательные", "de": "freundlich", "ru": "дружелюбный", "article": "", "example_de": "Das Personal ist freundlich.", "example_ru": "Персонал дружелюбный."},
    {"level": "B1", "topic": "Прилагательные", "de": "interessant", "ru": "интересный", "article": "", "example_de": "Ein interessantes Buch.", "example_ru": "Интересная книга."},
    {"level": "B1", "topic": "Прилагательные", "de": "langweilig", "ru": "скучный", "article": "", "example_de": "Der Film war langweilig.", "example_ru": "Фильм был скучным."},
    {"level": "B1", "topic": "Прилагательные", "de": "spannend", "ru": "захватывающий", "article": "", "example_de": "Der Krimi ist spannend.", "example_ru": "Детектив захватывающий."},
    {"level": "B1", "topic": "Прилагательные", "de": "gefährlich", "ru": "опасный", "article": "", "example_de": "Das ist gefährlich.", "example_ru": "Это опасно."},
    
    # --- Everyday Items (A1-A2) ---
    {"level": "A1", "topic": "Предметы", "de": "Auto", "ru": "машина", "article": "das", "example_de": "Das Auto ist neu.", "example_ru": "Машина новая."},
    {"level": "A1", "topic": "Предметы", "de": "Buch", "ru": "книга", "article": "das", "example_de": "Ich lese ein Buch.", "example_ru": "Я читаю книгу."},
    {"level": "A1", "topic": "Предметы", "de": "Handy", "ru": "мобильник", "article": "das", "example_de": "Wo ist mein Handy?", "example_ru": "Где мой мобильник?"},
    {"level": "A1", "topic": "Предметы", "de": "Uhr", "ru": "часы", "article": "die", "example_de": "Die Uhr ist kaputt.", "example_ru": "Часы сломаны."},
    {"level": "A1", "topic": "Предметы", "de": "Brille", "ru": "очки", "article": "die", "example_de": "Ich brauche meine Brille.", "example_ru": "Мне нужны мои очки."},
    {"level": "A2", "topic": "Предметы", "de": "Zeitschrift", "ru": "журнал", "article": "die", "example_de": "Die Zeitschrift ist neu.", "example_ru": "Журнал новый."},
    {"level": "A2", "topic": "Предметы", "de": "Regenschirm", "ru": "зонт", "article": "der", "example_de": "Vergiss deinen Regenschirm nicht.", "example_ru": "Не забудь зонт."},
    
    # --- Travel & Location (A1-B1) ---
    {"level": "A1", "topic": "Город", "de": "Parkplatz", "ru": "парковка", "article": "der", "example_de": "Wo ist der nächste Parkplatz?", "example_ru": "Где ближайшая парковка?"},
    {"level": "A1", "topic": "Город", "de": "Bahnhof", "ru": "вокзал", "article": "der", "example_de": "Wir fahren zum Bahnhof.", "example_ru": "Мы едем на вокзал."},
    {"level": "A2", "topic": "Путешествие", "de": "Flug", "ru": "полет/рейс", "article": "der", "example_de": "Der Flug war angenehm.", "example_ru": "Полет был приятным."},
    {"level": "A2", "topic": "Путешествие", "de": "Gepäck", "ru": "багаж", "article": "das", "example_de": "Warten Sie auf Ihr Gepäck.", "example_ru": "Ждите свой багаж."},
    {"level": "B1", "topic": "Путешествие", "de": "Sehenswürdigkeit", "ru": "достопримечательность", "article": "die", "example_de": "Berlin hat viele Sehenswürdigkeiten.", "example_ru": "В Берлине много достопримечательностей."},
    {"level": "B1", "topic": "Путешествие", "de": "Übernachtung", "ru": "ночевка", "article": "die", "example_de": "Die Übernachtung ist inklusive.", "example_ru": "Ночевка включена."},
    
    # --- Miscellaneous Essential Words ---
    {"level": "A1", "topic": "Разное", "de": "bitte", "ru": "пожалуйста", "article": "", "example_de": "Ein Kaffee, bitte.", "example_ru": "Один кофе, пожалуйста."},
    {"level": "A1", "topic": "Разное", "de": "danke", "ru": "спасибо", "article": "", "example_de": "Vielen Dank.", "example_ru": "Большое спасибо."},
    {"level": "A1", "topic": "Разное", "de": "ja", "ru": "да", "article": "", "example_de": "Ja, das stimmt.", "example_ru": "Да, это верно."},
    {"level": "A1", "topic": "Разное", "de": "nein", "ru": "нет", "article": "", "example_de": "Nein, danke.", "example_ru": "Нет, спасибо."},
    {"level": "A1", "topic": "Разное", "de": "vielleicht", "ru": "может быть", "article": "", "example_de": "Vielleicht komme ich.", "example_ru": "Может быть, я приду."},
    {"level": "A2", "topic": "Разное", "de": "zusammen", "ru": "вместе", "article": "", "example_de": "Wir lernen zusammen.", "example_ru": "Мы учимся вместе."},
    {"level": "A2", "topic": "Разное", "de": "allein", "ru": "один", "article": "", "example_de": "Ich bin allein.", "example_ru": "Я один."},
    {"level": "B1", "topic": "Разное", "de": "während", "ru": "в то время как", "article": "", "example_de": "Während ich arbeite...", "example_ru": "В то время как я работаю..."},
    {"level": "B1", "topic": "Разное", "de": "jedoch", "ru": "однако", "article": "", "example_de": "Er kam, jedoch zu spät.", "example_ru": "Он пришел, однако слишком поздно."},

    # === Phase 7: The "Final Push" to 1000+ words ===
    # --- Household Items (A1-A2) ---
    {"level": "A1", "topic": "Дом", "de": "Löffel", "ru": "ложка", "article": "der", "example_de": "Ich brauche einen Löffel.", "example_ru": "Мне нужна ложка."},
    {"level": "A1", "topic": "Дом", "de": "Gabel", "ru": "вилка", "article": "die", "example_de": "Hier ist eine Gabel.", "example_ru": "Вот вилка."},
    {"level": "A1", "topic": "Дом", "de": "Messer", "ru": "нож", "article": "das", "example_de": "Das Messer ist scharf.", "example_ru": "Нож острый."},
    {"level": "A1", "topic": "Дом", "de": "Teller", "ru": "тарелка", "article": "der", "example_de": "Der Teller ist leer.", "example_ru": "Тарелка пустая."},
    {"level": "A1", "topic": "Дом", "de": "Tasse", "ru": "чашка", "article": "die", "example_de": "Eine Tasse Tee, bitte.", "example_ru": "Чашку чая, пожалуйста."},
    {"level": "A1", "topic": "Дом", "de": "Glas", "ru": "стакан", "article": "das", "example_de": "Ein Glas Wasser.", "example_ru": "Стакан воды."},
    {"level": "A2", "topic": "Дом", "de": "Kühlschrank", "ru": "холодильник", "article": "der", "example_de": "Der Kühlschrank ist voll.", "example_ru": "Холодильник полон."},
    {"level": "A2", "topic": "Дом", "de": "Spülmaschine", "ru": "посудомоечная машина", "article": "die", "example_de": "Die Spülmaschine läuft.", "example_ru": "Посудомойка работает."},
    {"level": "A2", "topic": "Дом", "de": "Bügeleisen", "ru": "утюг", "article": "das", "example_de": "Das Bügeleisen ist heiß.", "example_ru": "Утюг горячий."},
    {"level": "A2", "topic": "Дом", "de": "Staubsauger", "ru": "пылесос", "article": "der", "example_de": "Der Staubsauger ist laut.", "example_ru": "Пылесос шумный."},
    
    # --- Animals (A1-A2) ---
    {"level": "A1", "topic": "Животные", "de": "Hund", "ru": "собака", "article": "der", "example_de": "Mein Hund bellt.", "example_ru": "Моя собака лает."},
    {"level": "A1", "topic": "Животные", "de": "Katze", "ru": "кошка", "article": "die", "example_de": "Die Katze schläft.", "example_ru": "Кошка спит."},
    {"level": "A1", "topic": "Животные", "de": "Pferd", "ru": "лошадь", "article": "das", "example_de": "Das Pferd rennt schnell.", "example_ru": "Лошадь бежит быстро."},
    {"level": "A1", "topic": "Животные", "de": "Vogel", "ru": "птица", "article": "der", "example_de": "Der Vogel singt.", "example_ru": "Птица поет."},
    {"level": "A1", "topic": "Животные", "de": "Fisch", "ru": "рыба", "article": "der", "example_de": "Fische schwimmen.", "example_ru": "Рыбы плавают."},
    {"level": "A2", "topic": "Животные", "de": "Elefant", "ru": "слон", "article": "der", "example_de": "Ein großer Elefant.", "example_ru": "Большой слон."},
    {"level": "A2", "topic": "Животные", "de": "Löwe", "ru": "лев", "article": "der", "example_de": "Der Löwe brüllt.", "example_ru": "Лев рычит."},
    {"level": "A2", "topic": "Животные", "de": "Affe", "ru": "обезьяна", "article": "der", "example_de": "Der Affe isst eine Banane.", "example_ru": "Обезьяна ест банан."},
    {"level": "A2", "topic": "Животные", "de": "Schlange", "ru": "змея", "article": "die", "example_de": "Ich habe Angst vor Schlangen.", "example_ru": "Я боюсь змей."},
    {"level": "A2", "topic": "Животные", "de": "Biene", "ru": "пчела", "article": "die", "example_de": "Bienen machen Honig.", "example_ru": "Пчелы делают мед."},
    
    # --- Nature & Weather (A1-B1) ---
    {"level": "A1", "topic": "Погода", "de": "Sonne", "ru": "солнце", "article": "die", "example_de": "Die Sonne scheint.", "example_ru": "Солнце светит."},
    {"level": "A1", "topic": "Погода", "de": "Regen", "ru": "дождь", "article": "der", "example_de": "Der Regen ist stark.", "example_ru": "Дождь сильный."},
    {"level": "A1", "topic": "Погода", "de": "Schnee", "ru": "снег", "article": "der", "example_de": "Es liegt viel Schnee.", "example_ru": "Лежит много снега."},
    {"level": "A1", "topic": "Погода", "de": "Wind", "ru": "ветер", "article": "der", "example_de": "Der Wind weht.", "example_ru": "Ветер дует."},
    {"level": "A2", "topic": "Погода", "de": "Gewitter", "ru": "гроза", "article": "das", "example_de": "Ein heftiges Gewitter.", "example_ru": "Сильная гроза."},
    {"level": "A2", "topic": "Погода", "de": "Nebel", "ru": "туман", "article": "der", "example_de": "Es ist neblig heute.", "example_ru": "Сегодня туманно."},
    {"level": "B1", "topic": "Погода", "de": "Luftfeuchtigkeit", "ru": "влажность воздуха", "article": "die", "example_de": "Hohe Luftfeuchtigkeit ist anstrengend.", "example_ru": "Высокая влажность утомительна."},
    {"level": "B1", "topic": "Погода", "de": "Klimaschutz", "ru": "защита климата", "article": "der", "example_de": "Klimaschutz ist eine globale Aufgabe.", "example_ru": "Защита климата - глобальная задача."},
    
    # --- More Verbs (Mixed Levels) ---
    {"level": "A1", "topic": "Глаголы", "de": "können", "ru": "мочь", "article": "", "example_de": "Ich kann Deutsch.", "example_ru": "Я знаю немецкий."},
    {"level": "A1", "topic": "Глаголы", "de": "müssen", "ru": "долженствовать", "article": "", "example_de": "Ich muss gehen.", "example_ru": "Я должен идти."},
    {"level": "A1", "topic": "Глаголы", "de": "wollen", "ru": "хотеть", "article": "", "example_de": "Was willst du?", "example_ru": "Чего ты хочешь?"},
    {"level": "A2", "topic": "Глаголы", "de": "dürfen", "ru": "иметь разрешение", "article": "", "example_de": "Darf ich hier parken?", "example_ru": "Мне можно здесь парковаться?"},
    {"level": "A2", "topic": "Глаголы", "de": "sollen", "ru": "следовать", "article": "", "example_de": "Was soll ich tun?", "example_ru": "Что мне следует сделать?"},
    {"level": "A2", "topic": "Глаголы", "de": "wissen", "ru": "знать", "article": "", "example_de": "Ich weiß es nicht.", "example_ru": "Я этого не знаю."},
    {"level": "B1", "topic": "Глаголы", "de": "vergessen", "ru": "забывать", "article": "", "example_de": "Ich habe meinen Schlüssel vergessen.", "example_ru": "Я забыл свой ключ."},
    {"level": "B1", "topic": "Глаголы", "de": "erinnern", "ru": "напоминать/помнить", "article": "", "example_de": "Erinnerst du dich an mich?", "example_ru": "Ты меня помнишь?"},
    {"level": "B1", "topic": "Глаголы", "de": "versprechen", "ru": "обещать", "article": "", "example_de": "Das kann ich versprechen.", "example_ru": "Это я могу обещать."},
    {"level": "B1", "topic": "Глаголы", "de": "entschuldigen", "ru": "извинять", "article": "", "example_de": "Entschuldigen Sie bitte.", "example_ru": "Извините, пожалуйста."},
    
    # --- More Adjectives (Mixed Levels) ---
    {"level": "A1", "topic": "Прилагательные", "de": "froh", "ru": "рад", "article": "", "example_de": "Ich bin froh, dich zu sehen.", "example_ru": "Я рад тебя видеть."},
    {"level": "A1", "topic": "Прилагательные", "de": "böse", "ru": "злой", "article": "", "example_de": "Sei nicht böse.", "example_ru": "Не злись."},
    {"level": "A2", "topic": "Прилагательные", "de": "müde", "ru": "усталый", "article": "", "example_de": "Ich bin so müde.", "example_ru": "Я так устал."},
    {"level": "A2", "topic": "Прилагательные", "de": "fleißig", "ru": "прилежный", "article": "", "example_de": "Er ist ein fleißiger Student.", "example_ru": "Он прилежный студент."},
    {"level": "A2", "topic": "Прилагательные", "de": "faul", "ru": "ленивый", "article": "", "example_de": "Heute bin ich faul.", "example_ru": "Сегодня я лентяй."},
    {"level": "B1", "topic": "Прилагательные", "de": "berühmt", "ru": "знаменитый", "article": "", "example_de": "Ein berühmter Schauspieler.", "example_ru": "Знаменитый актер."},
    {"level": "B1", "topic": "Прилагательные", "de": "mutig", "ru": "смелый", "article": "", "example_de": "Das war mutig.", "example_ru": "Это было смело."},
    {"level": "B1", "topic": "Прилагательные", "de": "vorsichtig", "ru": "осторожный", "article": "", "example_de": "Sei vorsichtig!", "example_ru": "Будь осторожен!"},
    {"level": "B1", "topic": "Прилагательные", "de": "höchstwahrscheinlich", "ru": "весьма вероятно", "article": "", "example_de": "Das ist höchstwahrscheinlich wahr.", "example_ru": "Это Весьма вероятно правда."},
    
    # --- Common Nouns (A1-B1) ---
    {"level": "A1", "topic": "Разное", "de": "Kindheit", "ru": "детство", "article": "die", "example_de": "Meine Kindheit war schön.", "example_ru": "Мое детство было прекрасным."},
    {"level": "A1", "topic": "Разное", "de": "Freund", "ru": "друг", "article": "der", "example_de": "Das ist mein bester Freund.", "example_ru": "Это мой лучший друг."},
    {"level": "A2", "topic": "Разное", "de": "Geschenk", "ru": "подарок", "article": "das", "example_de": "Danke für das Geschenk.", "example_ru": "Спасибо за подарок."},
    {"level": "A2", "topic": "Разное", "de": "Hoffnung", "ru": "надежда", "article": "die", "example_de": "Ich habe noch Hoffnung.", "example_ru": "У меня еще есть надежда."},
    {"level": "B1", "topic": "Разное", "de": "Erfahrung", "ru": "опыт", "article": "die", "example_de": "Sie hat viel Erfahrung.", "example_ru": "У неё много опыта."},
    {"level": "B1", "topic": "Разное", "de": "Entscheidung", "ru": "решение", "article": "die", "example_de": "Das war eine gute Entscheidung.", "example_ru": "Это было хорошее решение."},
]
